### ISSUE TITLE
Beautify rendered HTML (query from @paulrobertlloyd)

### ISSUE THREAD

**Issue by allmarkedup** [frctl/fractal#10]
Is it possible to beautify rendered HTML markup? For example, should a component include another, the indentation is lost after the first line, e.g. this component markup:

<img width="500" alt="screen shot 2016-03-03 at 13 32 15" src="https://cloud.githubusercontent.com/assets/813383/13495876/09664fb0-e145-11e5-9765-25218ac3b4a5.png">

is rendered as:

<img width="500" alt="screen shot 2016-03-03 at 13 32 54" src="https://cloud.githubusercontent.com/assets/813383/13495889/17144694-e145-11e5-929c-e7b15d4f7103.png">

🙈

**Comment by allmarkedup** [comment]
@paulrobertlloyd this has been added now in release v0.9.5 so all your HTML output should look pretty now :-)

**Comment by paulrobertlloyd** [comment]
Just updated… not entirely sure it’s working, but will do a little testing first.

**Comment by paulrobertlloyd** [comment]
Yeah, this doesn’t seem to be working; no change at all. What might I need to update?

**Comment by allmarkedup** [comment]
Hmm did it defintely update to the latest version? What version number do you have in your package.json?

**Comment by paulrobertlloyd** [comment]
On 0.9.6… reinstalled node modules and still an issue. e.g. 
<img width="320" alt="screen shot 2016-03-05 at 23 30 07" src="https://cloud.githubusercontent.com/assets/813383/13551217/3e99de40-e32a-11e5-828e-812adf682a02.png">

**Comment by allmarkedup** [comment]
Just to be clear - is indentation is still a problem? Or is it just excess new lines? I haven't actually configured it to remove new lines currently because that can get a bit messy, but I will take another look.

Is your repo in github? If so would you object to giving me read access to I can pull it down and have a tinker so i can see what is going on?

**Comment by paulrobertlloyd** [comment]
It’s both indentation and new lines. I’m in the early stages of building a site upon Fractal, whose repo is available at https://github.com/paulrobertlloyd/pick. There’s not a lot of compelling content on there yet, but a good example of this issue can be seen at http://pick.paulrobertlloyd.com/components/detail/dl

**Comment by allmarkedup** [comment]
Ok thanks mate - I'll take a look shortly and see if I can diagnose what is going on!

**Comment by allmarkedup** [comment]
I've made some tweaks to clear up some of the newline issues, but anything more vigorous will likely start to cause other issues (like unintentional one-lining). Most template engines such as Nunjucks offer some degree of [whitespace control](https://mozilla.github.io/nunjucks/templating.html#whitespace-control) around tags which can probably sort out any outstanding issues.
