### ISSUE TITLE
Please remove feat #775: split variant navigation into another panel or make it configurable

### ISSUE THREAD

**Issue by frankl7800** [frctl/fractal#1023]
### What problem would this feature solve?

* The variants columns takes a lot of unnecessary space
* The main status in the left column (often not configured, only status at variants) is visible
* A lot of `collated` components are no longer collated in one view

### What the feature should look like?

I am forced to downgrade to Mandelbrot 1.7.0 in all projects. :-(

**Comment by mihkeleidast** [comment]
I am sorry you dislike the feature, but I'm having a hard time understanding the feature request or issues here.

- The navigation sidebar can be collapsed if there is need for more space to view the components, as it has always been.
- If you don't want components to have a default status, you can disable it by settings `fractal.components.set('default.status', null);` in your config file. The alternative is that you need to define the status appropriately for components.
- Collated components should still be collated in a single view, they just have the option to be previewed one-by-one more visible. Previously the links were hidden in the info tab, I think.

I'm closing this issue for now, but feel free to write up some more concrete examples of what issues the new behavior is causing and maybe we can re-evaluate.
