### ISSUE TITLE
Feature request: Allow for multiple root level ‘component’ folders

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/fractal#103]
Within my components folder, I have a set of components which are top-level (page) assemblies. _Conceptually_, these are still components, but in terms of my deliverable, they are markedly different. Currently I have made the distinction in the navigation by using italics:

<img width="238" alt="screen shot 2016-07-28 at 10 51 56" src="https://cloud.githubusercontent.com/assets/813383/17208770/eb97136c-54b1-11e6-8644-e9993c7bcdc4.png">

Ideally, the Web UI would allow me to place them under a top level heading instead, i.e.:

<img width="238" alt="screen shot 2016-07-28 at 10 51 22" src="https://cloud.githubusercontent.com/assets/813383/17208789/0364a798-54b2-11e6-958d-160bc4641339.png">

This might be a Mandelbrot issue (and one that could be solved by using a custom theme), but it’s worth pointing out that allowing only a single component folder is a notable opinion within Fractal.

**Comment by sbaechler** [comment]
What about even giving up the strict separation between Handlebars 'Components' and Markdown 'Documentation'? Ideally Fractal would render whatever you throw at it.

**Comment by mihkeleidast** [comment]
### Solution proposal

- Allow specifying `root: true` in a collection config.
- By default, `root` is set to false
- If a collection has been set to be root, it will be pulled out from it's filesystem tree location in the navigation to root. It should not be rendered in its original location.
- If there are no non-root collections or no entities left in the default tree, then only the title should not be rendered. E.g. the usecase when I have `src/components` and `src/pages` collections and both have been set to be root.

WDYT?

**Comment by paulrobertlloyd** [comment]
As the person responsible for opening this issue, I guess I should comment.

While it’s great to see these old feature requests get resolved, I haven’t used Fractal in years, so have zero context – or recall – regarding this issue. So, please do go ahead without me. 🙂

**Comment by mihkeleidast** [comment]
Ah don't worry about it - the issue is still open because it looks like a great improvement. The proposal was not directed at you, rather at my co-maintainers. I find it's better to talk through the proposals before diving into code :)

**Comment by LeBenLeBen** [comment]
@mihkeleidast I guess that would work and without requiring any breaking change for a first version.

If we rather want that for the next major version, a single folder (no more components VS docs) that contains the whole tree might be better in the sense that the file system and the UI are perfectly aligned all the time.
