### ISSUE TITLE
Dev mode with output written to disk

### ISSUE THREAD

**Issue by portfolioris** [frctl/fractal#1045]
### What problem would this feature solve?

To integrate Fractal with other asset building tools (Vite), it would be great if Fractal could write it's files to disk _in dev mode_. This way, Fractal provides static HTML with fast (re)compiling, and Vite could use the output folder as it's base for HTML files. Vite's local dev server references js/css files, which it compiles immediately too. Vite also monitors the HTML files, so it reloads the page when Fractal generates an updated file.

### What the feature should look like?

I would assume this can be configured by CLI arguments, but other methods may work too.

I can also image the local webserver can be optionally disabled, and only have Fracal write it's files to disk.

My reason for this option: I have a similar setup in combination with PatternLab, which works great. PatternLab can do super-fast incremental updates of changed patterns and write it to disk. Fracal's full build option is too slow. But I like Fractal's UI and general workflow better!

**Comment by LeBenLeBen** [comment]
Yeah I think you could do the same as I did in the [styleguide starterkit](https://github.com/liip/styleguide-starterkit) using Webpack. Start Fractal server & Vite server in parallel, configure Vite server to proxy all unknown routes to Fractal server and then open Vite server URL in the browser.

**Comment by portfolioris** [comment]
Thanks for your replies. Vite does indeed have proxy settings, and I came up with the following Vite config:
```
  server: {
    proxy: {
      '^(?!\/(src|node_modules|@vite|__vite_ping)).*': {
        target: 'http://localhost:3000',
      },
    }
  },`

Seems to work pretty well. Closing the issue.

Just wondering though: is it that hard for Fractal to write to disk in dev mode instead of a virtual file system?
