### ISSUE TITLE
Bug: Fractal fails on node 16

### ISSUE THREAD

**Issue by khawkins98** [frctl/fractal#1048]
### Steps to reproduce the issue

1. Try to use Fractal with node 16

### Description

I see that this is most likely already a known issue: https://github.com/frctl/fractal/runs/2467468422

However, making this issue it would have been helpful to me to know (and I assume others) that you cannot currently use Node 16 with Fractal until the `istextorbinary` dependency updated is done: https://github.com/bevry/istextorbinary/issues/200

**Comment by mihkeleidast** [comment]
Yeah but adding support for a new Node version is more of a feature request :) But as you said, we're waiting for a dependency update to add Node 16 to our testing matrix.

**Comment by balupton** [comment]
istextorbinary v5.14.0 is now out, which should resolve this problem.

**Comment by khawkins98** [comment]
This should now work as fractl is using comptaible versions:

https://github.com/frctl/fractal/blob/278dd50a16f939c2128891f5eebc14a4f48712d1/package.json#L23
