### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by StephenMeehan2016** [frctl/fractal#105]
Hi 

I've tried to upgrade to 1.0.4, but I received this error message:

` Error: EACCES: permission denied, access '/usr/local/lib/node_modules/@frctl/fractal/node_modules/babel-runtime'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/@frctl/fractal/node_modules/babel-runtime']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/@frctl/fractal/node_modules/babel-runtime' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
`

What's the safest way to change the permissions? 

I could run the command as `sudo` but it looks like that's a [bad idea](http://stackoverflow.com/questions/26612649/please-try-running-this-command-again-as-root-administrator-error-when-trying) - is it?

> An installation can run arbitrary scripts and running it with sudo can be extremely dangerous! 

What would you recommend?

**Comment by sturobson** [comment]
running sudo with something you (may) trust, like this, is fine, imho. This page may be worth a look at, if you want to fix such permission errors for the future – https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by StephenMeehan2016** [comment]
Thanks for the reply. 

I found this article by [Aral Balkan](https://ar.al/scribbles/npm-install-g-please-try-running-this-command-again-as-root-administrator/), it suggests changing the permissions (for the current user) for just the required directory.

I used this `sudo chown -R $USER /usr/local` and I was able to update without any problems.

Thanks again.

**Comment by johannestroeger** [comment]
IMO, i would never install anything npm related globally - imagine you install something like this with sudo rights https://github.com/joaojeronimo/rimrafall
