### ISSUE TITLE
How to reference static files outside the fractal project folder?

### ISSUE THREAD

**Issue by StephenMeehan2016** [frctl/fractal#107]
Hi

Is it possible to reference static files outside the fractal project folder?

I was hoping something like this would work:

`fractal.web.set('static.mount', '../themes');` 

My css is outside the fractal project folder in `themes > css > styles.css`

I'd reference it in `preview.hbs` like this: 

`<link media="all" rel="stylesheet" href="{{ path '/css/styles.css' }}">`

Is this possible, or do all static files need to be inside the fractal project folder?

_I've reset the server each time I made any changes to `fractal.js`_

**Comment by allmarkedup** [comment]
Hi Stephen - currently Fractal does only supports serving files that are within your specified static assets directory. You can tell it which directory to use with the `static. path` web configuration setting, like so:

```js
fractal.web.set('static. path',  'path/to/my/assets');
```

The path can be to any folder in your filesystem, either relative to the directory you are in or an absolute path to a directory somewhere.

The `static.mount` setting is actaully for customising the _URLs_ of any assets that are linked to in that folder. If you have other scattered files outside of that folder then there is no way currently to have the web UI serve them up I'm afraid.

There is a little more detail (if you haven't seen it already) at http://fractal.build/guide/web#static-assets

Does that help at all?
