### ISSUE TITLE
Remove ambiguity from main description

### ISSUE THREAD

**Issue by franktopel** [frctl/fractal#1079]
fractal makes the following claim, both in the introduction of the docs, and in the description field of the github repository:

> Fractal is a tool to help you build and document **web component** libraries, and then integrate them into your projects.

The term **web component** is highly misleading here, as Fractal is obviously not dedicated to what most developers understand as a **[web component](https://developer.mozilla.org/en-US/docs/Web/Web_Components)**.

Please instead use the term you already use in other places of the documentation:

> Fractal helps you assemble, preview and document **website component** libraries [...]

I'd love to see how Fractal can be used for and integrated into existing web component libraries (to see if it can be an alternative to Storybook).

**Comment by mihkeleidast** [comment]
Ack, agreed, and PRs welcome to improve the wording 👍

**Comment by mihkeleidast** [comment]
> I'd love to see how Fractal can be used for and integrated into existing web component libraries (to see if it can be an alternative to Storybook).

Regarding this, I don't think Fractal needs to support anything special (unless trying to achieve server-side rendering of web components), as custom elements can be used through any of the template adapters.

**Comment by franktopel** [comment]
It might be worth to have an explicit chapter (and maybe demo) on this. Please note that most web component libraries use `lit-html` to generate dynamic HTML.
