### ISSUE TITLE
URL inconsitency dev-server/build 

### ISSUE THREAD

**Issue by tomgross** [frctl/fractal#1094]
I use fractal for a clickable HiFi-prototype und realized the following inconsistency: The URLs of the components differ if the project is built by the included development server `yarn run start` or if it is statically built `yarn run build`.

### Steps to reproduce the issue

Things I tried:

1. Using standard build extenision _.html_

```
fractal.web.set('builder.urls.ext', '.html');
fractal.web.set('builder.ext', '.html');
```

and

`<a href="./pagexy{{ _config.web.builder.ext }}">Link</a>`

This gives a ` ‼︎ 404: Component 'pagexy.html' not found.`, if a link to another page-component is clicked using the development server but works if built statically.

2. Using no build extension

```
fractal.web.set('builder.urls.ext', '');
fractal.web.set('builder.ext', '');
```

and

`<a href="./pagexy">Link</a>`

This works using the development server but works if built statically the build fails with these errors:

```
⚑ Exported 5 of 120 items
✘ Failed to export url /components/preview/widgetxy - ENOTDIR: not a directory, mkdir 'C:\Users\user\VC\fractal-bs\build\components'
```

**Proposed solution**

I see a workaround, if at runtime the template sees, if it is a development or static built and add or omit the builder extension accordingly.

The solution I guess would be to add the builder extension consistent for the development build too.

**Reproduces how often:**

100%

### Context

-   Fractal version: @frctl/fractal@1.5.11
-   Node version: 14.17.5
-   OS: Windows 10

**Comment by mihkeleidast** [comment]
Have you tried using the `path` filter with the URL? E.g. `<a href="{{path './pagexy' }}">Link</a>`.

**Comment by mihkeleidast** [comment]
Duplicate of #658.

**Comment by tomgross** [comment]
Works with `path`-filter. Since I use nunjucks it's `<a href="{{ './pagexy' | path }}">Link</a>`

**Comment by mihkeleidast** [comment]
Glad you got it working!
