### ISSUE TITLE
Fractal version mismatch! Global: 1.0.6 / Local: 1.0.4

### ISSUE THREAD

**Issue by StephenMeehan2016** [frctl/fractal#110]
Hi

I was hoping you may be able to help...

I've updated to 1.0.6, received this message:

`Fractal version mismatch! Global: 1.0.6 / Local: 1.0.4`

I thought I could update `Local` by `cd` to my folder project and run `npm i -g @frctl/fractal` but it doesn't work?

Any ideas? :)

**Comment by allmarkedup** [comment]
`npm i -g @frctl/fractal` will update your global version, not the local one. To update your local version you can run `npm update` from within your project root directory - that should do it!
