### ISSUE TITLE
How to run build?

### ISSUE THREAD

**Issue by StephenMeehan2016** [frctl/fractal#111]
Hi

How do I get `fractal build` to work?

I've created a folder called `build` in the Fractal project folder.

I've added this to fractal.js `fractal.web.set('builder.dest', __dirname + '/build');`

Restarted Fractal in the Terminal and run `fractal build`

Nothing happens?

Not sure what I'm missing...

**Comment by allmarkedup** [comment]
Hmm that should be all you need to do! In fact you don't even need to create the build folder yourself, that will be created automatically.

Do you get any feedback from the terminal at all? Is this on OSX or windows?

**Comment by allmarkedup** [comment]
@StephenMeehan2016 I'm assuming that this is a windows issue as I've had other reports of it failing on there (i.e. #118). Will close this to track it via that issue but if it's _not_ windows that you are having a problem with please feel free to re-open.

**Comment by StephenMeehan2016** [comment]
Hi, It is on OSX.

I figured out my problem. 

This is how I usually start my local Fractal server

- `cd` to my Fractal folder
- type `fractal start` press return
- local server starts

Fractal works until I try to run `fractal build`. Nothing happens?

* `fractal build` does work if I start it like this:*

- `cd` to my Fractal folder
- type `fractal` press `return`
- Then type `build` press `return`

It's a small difference, but I can now successfully export a static build.

Thanks for making Fractal!

**Comment by allmarkedup** [comment]
@StephenMeehan2016 if you start a server in one command line window using `fractal start` then you won't be able to run subsequent commands in that window - this is the same for long-running foreground tasks (like gulp/grunt watch tasks).

You should be able to run a build in a new terminal window/tab however, even whilst the server is running in the other one. If not please let me know!

The second way you describe definitely works too however - that is Fractal's interactive command line mode (http://fractal.build/guide/cli/interactive) and lets you start servers, run builds etc all without having to leave the window you are working on.

Hope that helps clear things up!
