### ISSUE TITLE
Ability to use .md files for notes on non compound components

### ISSUE THREAD

**Issue by pete-hotchkiss** [frctl/fractal#115]
Feature request here. 

Would _love_ to be able to author the contents of a components _notes_ tab using a separate .md file when it is part of a collection. 

Would be doubly cool if we could set this on a group _collection_ level or on an individual component level depending on how files are named - eg.

```
├── components
│   ├── modals
│   │   ├── default.config.yml
│   │   ├── default.hbs
│   │   ├── save.hbs
│   │   ├── save.config.yml
│   │   ├── cancel.hbs
│   │   ├── cancel.config.yml
│   │   └── README.md
```

The above applying the contents of `README.md` to all notes tabs for the components in a collection.

Alternatively on a hyper local level

```
├── components
│   ├── modals
│   │   ├── default.config.yml
│   │   ├── default.hbs
│   │   ├── default.md
│   │   ├── save.hbs
│   │   ├── save.config.yml
│   │   ├── save.md
│   │   ├── cancel.hbs
│   │   ├── cancel.config.yml
│   │   └── cancel.md
```

Rendering the MD for each components page info box uniquely

**Comment by allmarkedup** [comment]
@pete-hotchkiss I definitely like the idea of being able to add READMEs at the collection level and then have them render in the notes panel for each component. Would that also propagate to sub-collections do you imagine? Or only one level deep?

Regarding the 'hyper local level' - I could certainly add that in, but this is really the intention of [compound components](http://fractal.build/guide/components#compound-components) (i.e. a component with a collection of related files) within which you can have a README.md for each component. Although there is no harm in supporting it for non-folder-based components using the syntax you suggest I guess.

Is there any reason why you don't want to organise your modals collection in the 'compound component' style? i.e:

```
├── components
│   ├── modals
│   │   ├── default
│   │   │   ├── default.config.yml
│   │   │   ├── default.hbs
│   │   │   └── README.md
│   │   ├── save
│   │   │   ├── save.hbs
│   │   │   ├── save.config.yml
│   │   │   └── README.md
│   │   ├── cancel
│   │   │   ├── cancel.hbs
│   │   │   ├── cancel.config.yml
│   │   │   └── README.md
```

Too much overhead creating/naming/renaming the extra directories perhaps? Definitely interested to understand people's pain points when creating and updating components so would be good to know.

**Comment by nicklemmon** [comment]
+1!
