### ISSUE TITLE
Make front page editable

### ISSUE THREAD

**Issue by martindelima** [frctl/fractal#116]
First of all, congrats on Fractal! It's the most mature styleguide generator I've seen so far.

I noticed that the generated frontpage is [static content hard-coded into Mandelbrot](https://github.com/frctl/mandelbrot/blob/master/views/partials/content/overview.nunj). Can this be separated to use its own Markdown file? I fully expected it to be a doc page, but this wasn't the case. Thanks!

**Comment by allmarkedup** [comment]
Hey @martindelima - thanks, really glad you are enjoying using it!

If you have a [documentation pages directory](http://fractal.build/guide/docs), placing an `index.md` file in the top level will replace the contents of that generated overview page with whatever you put in that page.

Currently however you'll lose the generated status table - there will soon be a way to add that in to your own pages as a drop-in module but that is not possible with the current release I'm afraid.

**Comment by martindelima** [comment]
That's all I needed, thanks!
