### ISSUE TITLE
BUG: fractal build not running on Windows

### ISSUE THREAD

**Issue by pete-hotchkiss** [frctl/fractal#117]
Currently experiencing an issue trying to generate a static HTML site instance.

Running ```fractal build``` results in the following being returned to the command prompt

```
✔ Build started...
✘ EBUSY: resource busy or locked, rmdir 'C:\Users\phk\Documents\workspaces\foo project\scaffolding\fractal-test'
✘ Error: EBUSY: resource busy or locked, rmdir 'C:\Users\phk\Documents\workspaces\foo project\scaffolding\fractal-test'
```

I have the following in my _*fractal.js*_ config file

```javascript
/* Tell Fractal where to put a static build for hosting */
fractal.web.set('builder.dest', __dirname, '/build'); 
```

**Comment by allmarkedup** [comment]
@pete-hotchkiss ok, thanks for this. I'm unfortunately on holiday at the moment and without access to a Windows machine or VM but I'll look into this as a priority as soon as I can.

Can you try deleting the build destination folder manually before running the build task and let me know if that helps at all?

**Comment by pete-hotchkiss** [comment]
holiday ! Why you checking git issues. You should be enjoying a break !

removing build destination folder has no effect ...

what did do though was fix the typo in my config file

Its

```javascript
fractal.web.set('builder.dest', __dirname + '/build');
```
not
```javascript
fractal.web.set('builder.dest', __dirname, '/build');
```

**Comment by allmarkedup** [comment]
No rest for the wicked.... or those who release software! ;-)

Glad that sorted it - I didn't spot that in your code sample either!
