### ISSUE TITLE
Can't figure out how to register helper libraries for handlebars.

### ISSUE THREAD

**Issue by custa1200** [frctl/fractal#119]
I have tried to install [handlebars-helpers](https://github.com/assemble/handlebars-helpers) and am unable to get them to register with fractals instance of handlebars.

**Comment by custa1200** [comment]
Tried the following:
```
const handlebarHelpers = require('handlebars-helpers');
const hbs = require('@frctl/handlebars')({});
const engine = hbs.engine;
engine.registerHelper(handlebarHelpers);
```
but when I try to run fractal I get:
```
Error: Cannot find module '@frctl/handlebars'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/mjohnston/projects/styleglide2/fractal.js:44:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/@frctl/fractal/bin/fractal:53:19)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/@frctl/fractal/node_modules/liftoff/index.js:202:12)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/@frctl/fractal/node_modules/liftoff/index.js:169:7)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

I also tried the suggestion by @allmarkedup  pasted in the Slack group: 
```
const handlebarHelpers = require('handlebars-helpers');
const hbs = require('@frctl/handlebars')({
    /* config */
});

let adapter = fractal.docs.engine(hbs);

handlebarHelpers.register(adapter.engine);
```
but with no success.

**Comment by radarseven** [comment]
@custa1200 Try running `npm install --save @frctl/handlebars`. This solved the issue for me.

**Comment by custa1200** [comment]
can I see the code you used to register helpers for the components @radarseven ?

**Comment by radarseven** [comment]
@custa1200 Sure thing! This is an abbreviated version of my `fractal.js` config file. Note, I've removed only more sensitive config settings, such as project name, etc. All the critical stuff is there.

The important part is `require('@frctl/handlebars')`. That library isn't installed by default when you install `Fractal` via `npm`, which makes `npm install --save @frctl/handlebars` critical. At least, that's how I understand it.

```
'use strict';

/* Create a new Fractal instance and export it for use elsewhere if required */
const fractal = module.exports = require('@frctl/fractal').create();

/* Tell Fractal where the components will live */
fractal.components.set('path', __dirname + '/fractal/src');

/* Tell Fractal where the documentation pages will live */
fractal.docs.set('path', __dirname + '/fractal/docs');

/* Web assets */
//fractal.web.set('static.path', __dirname + '/public/assets');
fractal.web.set('static.path', __dirname + '/public');

/* Preview layout */
fractal.components.set('default.preview', '@preview');

/* Static build directory */
fractal.web.set('builder.dest', __dirname + '/fractal/build');

const hbs = require('@frctl/handlebars')({
    helpers: {
        uppercase: function(str) {
            return str.toUpperCase();
        },
		moduloIf: function(index_count,mod,block) {
			if (parseInt(index_count)%(mod)=== 0) {
				if (index_count===0) {
					return null;
				} else {
					return block.fn(this);
				}
			}
		}
    }
    /* other configuration options here */
});

fractal.components.engine(hbs); /* set as the default template engine for components */
fractal.docs.engine(hbs); /* you can also use the same instance for documentation, if you like! */

```

Hope that helps you!

**Comment by allmarkedup** [comment]
Hey @custa1200 - sorry for the slow replies, I'm on holiday at the moment so with limited access to my laptop. @radarseven thanks for jumping in and helping out!

You do indeed need to run `npm install --save @frctl/handlebars` before you can customise it. I've added a note about that to the docs.

I've also just pushed a very small update to the `@frctl/handlebars` library (1.0.2) and also updated the documentation on how to use the underlying handlebars instance with other helper libraries.

Have a look at the 'Accessing the underlying Handlebars instance' section  at the bottom of the page here: http://fractal.build/guide/core-concepts/views#customising-handlebars once you have updated to the latest version and let me know if anything still isn't clear or doesn't work for you.
