### ISSUE TITLE
Blacklist for file extensions, which should not be copied as assets.

### ISSUE THREAD

**Issue by LostKobrakai** [frctl/fractal#120]
In processwire I'm using the templates folder as static file root, but this folder does also include .php files, which should obviously not be copied when building the static fractal page. It would be really nice to simply have a blacklist by file extension, where I can simply exclude like this: `fractal.web.set('builder.exclude', ['inc', 'php']);`

**Comment by allmarkedup** [comment]
Yes this would definitely be handy and should pretty easy to add in too. I'll try and get it in to a release sometime soon 👍
