### ISSUE TITLE
Needs a demo.

### ISSUE THREAD

**Issue by ghost** [frctl/fractal#121]
Love the idea of this, would it not be a great idea to have a demo?

**Comment by paulrobertlloyd** [comment]
I know @allmarkedup has this on his (ever growing) to-do list, but feel free to contribute: https://github.com/frctl/demo

**Comment by simonmacfadyen** [comment]
What would be your requirements for a solid demo?

**Comment by allmarkedup** [comment]
@simonmacfadyen I couldn't agree more, I just need the time to do it! The demo repo that @paulrobertlloyd linked to is a little out of date now but I'll hopefully have time to get something up once I'm back from holiday, in the next few weeks.

**Comment by vdecree** [comment]
This would be great
