### ISSUE TITLE
Example of how to expose other folders

### ISSUE THREAD

**Issue by custa1200** [frctl/fractal#122]
I would like to be able to expose bower_components in the public folder. I have tried the following but with no luck:

```
fractal.web.set('/bower_components', path.join(__dirname, '/bower_components'));
```

**Comment by allmarkedup** [comment]
Hey @custa1200, I'm afraid this isn't possible... currently you can only expose one public directory.   You can think of this as the 'webroot' directory for the server, so anything that is outside of it (i.e. not publicly accessible) needs to be copied into it using a build step.

Alternatively, in the bower example, you could also change the bower_components directory to be _within_ your static (public) assets directory by using a `.bowerrc` file (assuming in this example your static assets directory is called 'public' :

```
{
  "directory" : "public/bower_components"
}
```

And then register the static assets dir as usual:

```
fractal.web.set('static.path', path.join(__dirname, 'public') );
```

Would that help solve your issue?

**Comment by custa1200** [comment]
I have been able to expose bower previously using another express app, I would have though that being based on express it would have been possible :(

**Comment by allmarkedup** [comment]
It's certainly something I could add if it's useful to people.

It's slightly more complicated than with 'vanilla' Express because it needs to support the static build process. Really what that means is just that if there were multiple static directories then each one would need to have a 'url namespace' ('mount' in Express terms) specified for them (i.e. not all mounted at the root) so that there are not clashes when files are copied in the build. No big deal though I think.

I'll open a feature request to add it in :-)

**Comment by allmarkedup** [comment]
Actually, having thought about this, you can do this already with a little more work, in a similar way to the way you can [customise theme templates](http://fractal.build/guide/web/default-theme#template-customisation).

This should work:

```js
const path = require('path');
const fractal = module.exports = require('@frctl/fractal').create();

// setup....

const myCustomisedTheme = require('@frctl/mandelbrot')({
    // theme config here
});

// add an additional static assets path
const dir = path.join(__dirname, 'bower_components');
const mount = 'bower_components';
myCustomisedTheme.addStatic(dir, mount);  

fractal.web.theme(myCustomisedTheme);
```

Let me know how you get on!

**Comment by allmarkedup** [comment]
(I'll still leave the issue #128 open about making this more straightforward (i.e. taking an array in the `static.paths` config or something similar.)
