### ISSUE TITLE
Require is not defined - new Fractal installation

### ISSUE THREAD

**Issue by Radu033** [frctl/fractal#1222]
Hello,

I just started with Fractal, I installed everything as instructed by the documentation, but when I type in "fractal start --sync" in the terminal, I get the following error message: ReferenceError: required is not defined
![image](https://user-images.githubusercontent.com/6954983/193555034-d00f97cc-0ca9-46d5-a756-846c8550f671.png)

### Steps to reproduce the issue

1. Install Fractal using the teminal as written in the documentation
2. After installation type in "fractal start --sync"
3. See the error in the terminal

I tried 3 times, always get the same result.

### Context

-   Fractal version: 1.5.14
-   Node version: v16.17.1
-   OS: Mac OS 12.3.1

**Comment by mihkeleidast** [comment]
It seems like the error is coming from your own config file, can you post the contents so we could take a look?

**Comment by Radu033** [comment]
@mihkeleidast  you are right, I found the issue and fixed it. Thanks
