### ISSUE TITLE
Allow multiple static asset paths

### ISSUE THREAD

**Issue by allmarkedup** [frctl/fractal#128]
Each one would probably need to be url-namespaced so that there are no clashes when copying files over during the build process.

**Comment by julmot** [comment]
Need this too, because I have a `dist` folder of automatically generated compiled files, but also a `static` folder with static assets.

**Comment by julmot** [comment]
For everyone interested in this issue. I'm using `http-server` as a workaround to initialize a second server for static files.

**Comment by luksak** [comment]
This would be really useful.

**Comment by ma-vo** [comment]
use serveStatic if you you fractal with the default webserver integration (browserSync)

`fractal.web.set('server.syncOptions', {
    serveStatic: [{
        route: 'YOUR_ROUTE',
        dir: 'PATH_TO_FILES_YOU_WANT_TO_SERVE'
    }]
});`
