### ISSUE TITLE
Improvement: Don’t prefix theme folder in static build with underscore (GitHub Pages)

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/fractal#13]
Folders and files prefixed with an underscore cause issues with static sites published using GitHub pages. You can get around this by including a `.nojekyll` file in the root of the repo being published, but this is an extra step, a potential pinch point. Is there another symbol prefix that can be used for this folder instead?

**Comment by allmarkedup** [comment]
Ah ok sure, I hadn't considered this. To be honest I don't think there is any problem in just removing the underscore altogether and leaving it as `/theme`. I can always make it configurable too if that is a problem for people.

**Comment by allmarkedup** [comment]
This has been done in the latest release of the Mandlebrot theme. Default theme folder name is not `/theme` instead of `/_theme`.

**Comment by raphaellarrinaga** [comment]
I would just specify it is possible to use the option `static.mount` [explained here](http://fractal.build/guide/web/default-theme).
Thank you for that.
