### ISSUE TITLE
Control version of components

### ISSUE THREAD

**Issue by viktortomilin** [frctl/fractal#136]
Are you planning create a system for controlling versions of components? I want to have a different versions of my UI library and I don't know how I can do it in current version.

Thx.

**Comment by allmarkedup** [comment]
@viktortomilin I'd love to have some sort of version control or at least integration with version control systems. However I'm not sure yet of the best way to implement this so it's on the sidelines for now.

There is already an issue open to track this as a feature request here: https://github.com/frctl/fractal/issues/81 - if you have any thoughts on how it could be implemented in a un-opinionated, flexible way then please do add a comment on that thread!
