### ISSUE TITLE
Preview layout doesn't seem to be working?

### ISSUE THREAD

**Issue by mariusz** [frctl/fractal#139]
I have created a `source/components/layouts/_preview.hbs` in my source directory and added `fractal.components.set('default.preview', '@preview');` to my config and yet I keep getting `‼ Preview layout @preview not found. Rendering component without layout.` error. Any ideas what could be going on? 

### Preview layout: 

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link media="all" rel="stylesheet" href="{{ path '/css/build.css' }}">
    <title>Preview Layout</title>
</head>
<body>

{{{ yield }}}

</body>
</html>
```

### fractal.js

```javascript
'use strict';

/* Create a new Fractal instance and export it for use elsewhere if required */
const fractal = module.exports = require('@frctl/fractal').create();
const mandelbrot = require('@frctl/mandelbrot');

const customTheme = mandelbrot({
    skin: "black",
    styles: [
      "default",
      "/css/lsg.css"
    ]
});

fractal.set('project.title', 'anynines Living Style Guide');
fractal.set('project.version', '1.0');

fractal.components.set('path', __dirname + '/source/components');
fractal.components.set('default.preview', '@preview');

fractal.docs.set('path', __dirname + '/source/docs');

fractal.web.set('static.path', __dirname + '/public');
fractal.web.set('server.sync', true);
fractal.web.set('builder.dest', 'build');

fractal.web.theme(customTheme);
```

**Comment by sturobson** [comment]
Hi @mariusz, just doing some sense-checking ... is your `.css` file in `/public/css/`

taking 
```fractal.web.set('static.path', __dirname + '/public');```
and 
```{{ path '/css/build.css' }}``` 

from the above codes? :)

**Comment by allmarkedup** [comment]
@mariusz Hmm that is odd - doesn't look like there is anything obviously wrong there. Can you run the command `fractal info` from within your project directory and let me know what local + global version you are running?

Also, if you remove the `_` prefix from the `_preview.hbs`, does it show up as a component in the sidebar in web UI? It should do, if not something funny is going on.

@sturobson I don't think it's an issue with the assets - if he is seeing the `Preview layout @preview not found. Rendering component without layout.` that means that fractal can't find the template itself.

**Comment by mariusz** [comment]
@allmarkedup no, when I remove the `_` prefix from `_preview.hbs`, it doesn't show up as a component. It's in `layouts` directory though — so should it? I'm new to all of this and can't really tell.

When I run `fractal info`, I get: 

    ┌────────────────────────────────┐
    │ Fractal install info           │
    │────────────────────────────────│
    │ Project Fractal version: 1.0.8 │
    │ CLI helper version:      1.0.8 │
    └────────────────────────────────┘

**Comment by sturobson** [comment]
@mariusz as far as I know, and @allmarkedup will be bound to correct me, the _preview.hbs needs to be in the top level of whatever you're calling the folder that houses your components... so in your case, I'd try to have it as `/source/components/_preview.hbs`

I hope this helps 😄

**Comment by mariusz** [comment]
@sturobson actually, that's exactly what I did — moved it to `/source/components` and it seems to work :+1:
