### ISSUE TITLE
Possibility to export components only as rendered HTML files

### ISSUE THREAD

**Issue by captainh2ok** [frctl/fractal#140]
For better code exchange with clients, it would be a nice feature to implement an "export" command for exporting/building components only, without the web-ui (like in the "render" folder inside the static build). And as an additional feature: export/build only components which have the status "ready".
These files can then be versioned and the clients can easily make "diffs" with different release states.

Do you plan something like this? Or is it eventually possible with the next 1.1.x release?

Thanks so much for devloping Fractal. It's really a great tool!

**Comment by allmarkedup** [comment]
Hey @captainh2ok - really sorry for how long it has taken to reply to you but glad that you are liking Fractal.

What you describe is already possible using a custom CLI command (http://fractal.build/guide/cli/custom-commands). You could add something like the following to your fractal.js file:

```
const fs = require('fs');
function exportComponents(args, done){
    const app = this.fractal;
    for (let item of app.components.flatten()) {
        if (item.status.label === 'Ready') {
            item.render().then(function(html){
                fs.writeFile('./completed-components/' + item.handle + '.html', html);
            });
        }
    }
    done();
};

fractal.cli.command('export-components', exportComponents, 'Export completed components');
```

And the run it from you project directory with the command `fractal export-components`

Obviously it's a very rough example but hopefully helps to point you in the right direction.

**Comment by captainh2ok** [comment]
I've tried your approach before (thanks to the good documentation!), but was stuck by making the "for" loop work. Maybe it's because i've every task fired by a GULP task (which indeed works for all other tasks like a charm). Here is my setup so far:

Gulp Task:
```
const gulp = require( 'gulp' );
const fs = require('fs');
const fractal = require('../fractal-config.js');

gulp.task('fractal:exportComponents', function(){
    console.log(fractal);
    for (let item of fractal.components.flatten()) {
        if (item.status.label === 'Ready') {
            item.render().then(function(html){
                fs.writeFile('./completed-components/' + item.handle + '.html', html);
            });
        }
    }
});
```

The console statement shows that the fractal instance is initialized:

```
Fractal {
  _config: 
   { version: '1.0.8',
     env: 'production',
     project: 
      { title: 'Company Website Patterns',
        version: 'v0.0.1',
        info: '2016, company name',
        url: 'www.companyname.de',
        author: 'XXXXXXX',
        buildDate: Thu Oct 20 2016 09:08:15 GMT+0200 (CEST),
        namespace: 'AP_',
        exportdir: '/loremIpsum' },
     components: 
      { engine: '@frctl/handlebars',
        path: 'LoremIpsum',
        label: 'components',
        title: 'Patterns',
        yield: 'yield',
        splitter: '--',
        ext: '.hbs',
        resources: [Object],
        default: [Object],
        statuses: [Object] },
     docs: 

.....
```

But the "for" loop does nothing and there is no error message.  There must be something wrong...

Thanks in advance, Oliver

**Comment by allmarkedup** [comment]
Ah ok, if you are running it in a Gulp task you will need to make sure that the initial load/parse of the components directory has run first (the fractal CLI does this automatically before running tasks).

Try this (note the `fractal.components.load()` addition):

```
const gulp = require( 'gulp' );
const fs = require('fs');
const fractal = require('../fractal-config.js');

gulp.task('fractal:exportComponents', function(){
    fractal.components.load().then(() => {
        for (let item of fractal.components.flatten()) {
            if (item.status.label === 'Ready') {
                item.render().then(function(html){
                    fs.writeFile('./completed-components/' + item.handle + '.html', html);
                });
            }
        }
    });
});
```

**Comment by captainh2ok** [comment]
I see, now it's clear. Works perfect. Thanks so much!

**Comment by allmarkedup** [comment]
Excellent, great to hear 👍

**Comment by acespace90** [comment]
Hi I have same necessity of @captainh2ok. I tried with @allmarkedup suggestion but I have this error in console. Can you help me guys?

```
[00:39:16] Starting 'fractal:exportComponents'...
[00:39:16] Finished 'fractal:exportComponents' after 1.51 ms
(node:20460) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1159:14)
    at /Users/antoniomatera/Sites/iamatek/lib/gulp/fractal.js:123:22
(node:20460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by acespace90** [comment]
I want to export my components like in the "preview" folder but without fractal UI.

**Comment by acespace90** [comment]
Ok I solved with
```
gulp.task('fractal:exportComponents', function(){
  fractal.components.load().then(() => {
      for (let item of fractal.components.flatten()) {
          if (item.status.label === 'Ready') {
              item.render().then(function(html){
                  fs.writeFile('./completed-components/' + item.handle + '.html', html, function(err, result) {
                    if(err) console.log('error', err);
                  });
              });
          }
      }
  });
});
```

And it exports html page in `completed-components` folder but it ignores the inclusion if`_preview.hbs` file as page wrapper.

```
<!DOCTYPE html>
<html lang="it" class="{{ _target.context.layoutCss }}">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="format-detection" content="telephone=no">
	<title>{{ _config.project.title }}</title>
	<meta name="description" content="{{ _config.project.title }} frontend">
	<link rel="stylesheet" href="{{ path '/css/main.css' }}" />
	<link href="https://fonts.googleapis.com/css?family=Lato:400,700&amp;subset=latin-ext" rel="stylesheet">
</head>

<body class="{{ _target.context.layoutCss }}">

	{{{ yield }}}
	{{> @svgsprite }}

	<script src="{{ path '/js/footer.min.js' }}"></script>

</body>

</html>
``` 

So what it renders is the only the content of `{{{ yield }}}`.

And then, what about the assets folders (css, images, js)?

**Comment by martinjagodic** [comment]
Is there a way to render components with the preview wrapper, like @acespace90 was asking?

**Comment by ruurdv** [comment]
I hope it's still possible to request assistance regarging this same issue.

I'm doing exactly what allmarkedup is suggesting (thank you for that, allmarkedup), but unfortunately this item.render() function is not doing anything at all on my side. 
My logs before and after the promise are showing up in the terminal on execution, but a log inside the function is not.  Any idea why this is / how to solve it? 

Getting this to work will have massive impact inside our organisation. Thank you in advance.
