### ISSUE TITLE
Cannot add notes to notes tab?

### ISSUE THREAD

**Issue by blaasvaer** [frctl/fractal#145]
I've tried to both add a "notes" to the config file, and also tried a README.md file. But I cannot make anything show up in the "notes" tab ... what am I missing? Been through the documentation on notes several times, but can't seem to make it work.

Great project, by the way ; )

**Comment by zackphilipps** [comment]
@blaasvaer what did you find out? I got single-line notes to finally work in a YAML file, but still can't get multi-line notes to work...

**Comment by blaasvaer** [comment]
@zackphilipps I didn't get anywhere with, unfortunately. Other issues came up ... But I'm getting back at some point in a near future.

**Comment by zackphilipps** [comment]
@blaasvaer I could not get a README.md to work at all... but, in the config file, if you want to do multiline notes, just make sure your notes are in quotes and use the newline character `\n` like so (YAML):

```yaml
notes: "Line one.\n\nLine two. `code.js` \"quote\" **bold**"
```
