### ISSUE TITLE
How to generate docs?

### ISSUE THREAD

**Issue by blaasvaer** [frctl/fractal#146]
I cannot guess from the documentation how to actually output docs.

How is it done? From the CLI, automatically or ... ?

**Comment by ethikz** [comment]
Did you figure this out?

**Comment by blaasvaer** [comment]
You tell fractal where the docs live in the fractal.js file in your project with this line:
`/* Tell Fractal where the documentation pages will live */
fractal.docs.set('path', __dirname + '/src/docs');`

You then create that folder at /src/docs. And in there you put stuff like:
`01-my-component-library.md`
`02-my-modules.md`

And you can add config files as well:
`01-my-component-library.config.json`

When running fractal (from the terminal) it generates the docs, and (the point I missed in the first place) puts a link in the left menu in the generated ouput (below Components).

http://fractal.build/guide/docs
