### ISSUE TITLE
Add multiple extension?

### ISSUE THREAD

**Issue by blaasvaer** [frctl/fractal#147]
Is it possible to add more extension using some sort of:
fractal.components.set('ext', '.hbs|.htm');

I've also tried multiple lines:
fractal.components.set('ext', '.htm');
fractal.components.set('ext', '.hbs');

... in the hope that it was appended.

**Comment by johannestroeger** [comment]
i have similar situation:

```
fractal.components.set('ext', '.js')
```

this means `component.config.js` is interpreted as "component.config". 
should the pattern `\.config.js\` be always excluded?

**Comment by allmarkedup** [comment]
@blaasvaer you cannot register multiple extensions at the moment I'm afraid. It's an open feature request but supporting it would be a pretty large change to the way Fractal parses the component directory so it may be a while before it's implemented.

@johannestroeger - can you clarify the issue that you are having? You should be able to set the extension to `.js` without it picking up config files, if not it is a bug!

**Comment by johannestroeger** [comment]
@allmarkedup i wasn't aware that e.g. Icon.js and Icon.config.js must have the same case-sensitivity.

**Comment by allmarkedup** [comment]
@johannestroeger ah ok - actually that is unintentional if that is the case! I'll add this as a separate issue to be tracked as a bug as I think that the case shouldn't matter in examples like this. Thanks for the update :-)

**Comment by johannestroeger** [comment]
just as a ref my env:

| software         | version
| ---------------- | -------
| fractal            |  v1.0.8
| node             | v6.8.1
| npm              | v3.10.3
| Operating System | macOS 10.12.1 (16B2327e)
