### ISSUE TITLE
Feature Request: Show SCSS and parsed CSS directly in components panel

### ISSUE THREAD

**Issue by jackblackCH** [frctl/fractal#150]
Copy / Pasting of css and/or scss snippets is a must have for a lot of integrators.
So I think it would be nice to see the scss & css files directly as first level items as well instead of hiding them in the "assets file list"

i.e: HTML - SCSS - CSS - View - Context - Assets - Info - Notes

**Comment by custa1200** [comment]
Personally I think there are too many asset types that would make up the components SVGs, Images, SCSS, JSON, etc it would become a mess in a hurry I feel. I think @allmarkedup has hit the right balance.

**Comment by ixley** [comment]
This sounds like something that could be relevant at the template level, but my guess is that it's not high priority enough to make it into Mandelbrot in the near future. That said, I agree that there could be value in allowing people to have more control over which asset files get displayed and where.

**Comment by allmarkedup** [comment]
@jackblackCH what you are trying to do is actually already possible via a 'hidden' (i.e. undocumented) configuration setting. Try doing (adjust as needed):

```
fractal.components.set('resources', {
    scss: {
        label: 'SCSS',
        match: ['**/*.scss']
    },
    css: {
        label: 'CSS',
        match: ['**/*.css']
    },
    other: {
        label: 'Other Assets',
        match: ['**/*', '!**/*.scss', '!**.css']
    }
});
```

 Be warned however - this is undocumented because I'm not quite sure that the implementation/api won't change in the future, so use at your own risk :-)
