### ISSUE TITLE
Adding new panels

### ISSUE THREAD

**Issue by dexster** [frctl/fractal#152]
I’m trying to add a new panel to show the contents of a .controller.js file that resides in the relevant component’s dir. I've managed to add the panel tab by adding to the panels array  and I have overridden an existing panel by using the theme-overrides method but is it possible to get access to the controller.js file and its contents or would this require source code modification?
| my-component
|---my-component-config.js
|---my-component-controller.js
|---my-component.hbs

**Comment by allmarkedup** [comment]
@dexster - apologies for taking so long to get back to you on this! What exactly do you mean by 'get access to the controller.js file and its contents'? Do you want to _display_ the contents of the file in the tab or include the JS in the theme to add some functionality to the tab?

**Comment by dexster** [comment]
I just want to display the contents. What I meant by 'get access ' was whether the existing API will read this file and I can get access via the API.

**Comment by allmarkedup** [comment]
@dexster I realise that this response is probably far to late to be useful to you... but any assets (resources) of the current component are available as a collection that you can access via `entity.resources()` in the panels. So to output the contents of that file you could use:

```
{{ entity.resources().find('base', 'my-component-controller.js').contents }}
```

Hope that helps if it's not all too late!
