### ISSUE TITLE
Process SCSS Variables

### ISSUE THREAD

**Issue by ethikz** [frctl/fractal#153]
I'm currently checking out Fractal and like it so far. The one issue i'm seeing, whether it is a bug or a feature request is the ability to process/parse the SCSS variables.

`variables.config.yml`
```
{
  "title": "Variables",
  "status": "ready",
  "default": "core",
  "variants": [
    {
      "name": "core",
      "context": {
        "variable": "$primary-color"
      }
    }
  ]
}
```

`variables.hbs`
```
<div style="background-color: {{ variable }}">{{ variable }}</div>
```

But of course it parses it as a string.  Is there something I am missing or is it just not possible?

**Comment by allmarkedup** [comment]
Hi @ethikz - Fractal doesn't have any way to parse SCSS (or do any other kind of asset pre-processing). It's possible that this sort of functionality could be implemented as a plugin in the future but right now it's not possible I'm afraid.

**Comment by ethikz** [comment]
@allmarkedup Thanks!
