### ISSUE TITLE
How to use fractal on multiple individual project running on localhost?

### ISSUE THREAD

**Issue by blaasvaer** [frctl/fractal#156]
Hi,
How could I implement fractal, so that I can use it on multiple DIFFERENT projects ALL running from their own respective directory on localhost:
`<webroot>/project_one`
`<webroot>/project_two`
`<webroot>/project_three`
etc.
`localhost:80/project_name/fractal` // would be nice, and should be possible as I'm starting fractal from within a certain directory, right?

My goal here is to have as little double maintenance as possible.

**Comment by allmarkedup** [comment]
@blaasvaer You can configure each project to run on a different port if you want to run multiple projects at the same time, but you can't use one port for multiple projects I'm afraid.

See the docs for info on how to pass a port option when starting a new dev server instance: http://fractal.build/guide/web/server#starting-the-server
