### ISSUE TITLE
_preview.hbs in one module folder is added to all other modules?

### ISSUE THREAD

**Issue by blaasvaer** [frctl/fractal#157]
Hi,
When I add a _preview.hbs file to ONE module, it gets added to ALL OTHER modules.

What am I missing here? Yes, read the docs over and over ...

**Comment by ethikz** [comment]
Did you set a default preview in the config?

Where is the `_preview.hbs` in the structure?

From my understanding, if you set a default preview in the config and then don't overwrite it per component then it will inherit the default preview

**Comment by blaasvaer** [comment]
I've put it in my components folder (I'm using an npm structure to get the benefits) /src/admin/node_modules/pages/_preview.hbs.

I haven't done anything besides that. But I see now, that it actually acts as a placeholder for ALL components ... my bad. I instinctively thought I would have to create a _preview.hbs file in all component directories. It states to place it in the root of the folder ... 48 hours in front of the screen makes your eyes hurt and brain boil.

**Comment by ethikz** [comment]
Hehehe ok, so you're set then?

**Comment by allmarkedup** [comment]
Preview files are just components themselves. They don't have to be called `_preview.hbs`, they can be called whatever you like - and then you reference them using their handle - i.e. `@preview`, or '@my-preview-file` if it's called `my-preview-file.hbs`. Thus you can have multiple previews and reference the appropriate ones from within your component or collection configurations as needed.

If you have defined a default preview layout in your `fractal.js` file then this will be used by all  components unless specifically overridden with a configuration file.

Does that help at all? Or just make things more confusing? ;-)

**Comment by blaasvaer** [comment]
Well, reading the docs a couple of times or more does help : ).

**Comment by allmarkedup** [comment]
Closing this as it sounds like it's resolved now, but feel to re-open if not!
