### ISSUE TITLE
Adding Docs Question

### ISSUE THREAD

**Issue by ethikz** [frctl/fractal#158]
I'm trying to add docs and the `buttons` doc from example shows up but it's showing the wrong information.

My structure is as follows:

```
app
  --- components
    --- 6-components
      --- buttons
        _buttons.scss
        buttons.config.yml
        buttons.hbs
      _preview.hbs
docs
  buttons.md
```

I'm using the supplied code:

```
## Button component

The button component can be included within other components like this:

\{{> @buttons }}

This template for this component looks like this:

{{view @buttons}}

and it therefore expects a set of data to render it that is in the following format:

{{context @buttons}}

```

But what is being output for `view` and `context` is completely different.

Below is coming from my `settings` component

```
app
  --- components
    --- 1-settings
      --- colors
        colors.config.yml
      _variables.scss
    ...
```

```
{{#each variables}}
<div style="{{#if color}}background-color: #{{ color }};{{/if}} {{#if font}}color: #{{ font }};{{/if}}">{{ name }}</div>
{{/each}}
```

It is coming from the `colors.config.yml` file.

Is there something I'm missing or doing wrong?

**Comment by ethikz** [comment]
Figured it out.

In the `buttons.md` i had tp surround the partial with single quotes.

```
## Button component

The button component can be included within other components like this:

\{{> @buttons}}

This template for this component looks like this:

{{render '@buttons'}}

and it therefore expects a set of data to render it that is in the following format:

{{context '@buttons'}}
```

**Comment by allmarkedup** [comment]
@ethikz The `view` helper is intended just to fetch and output the contents of the view template for that component. The `render` helper is intended to render that view template with either the default set of data or the data you specify.

The quote issue I'll need to look into - certainly it should be the same behaviour no matter where the helper is being used or which helper it is!

**Comment by ethikz** [comment]
@allmarkedup Awesome!  Thanks for the information!

**Comment by armstrongb** [comment]
The quote issue causes some strange behaviour in my project. If they are not included then it picks the next sibling (in docs) and renders that instead.

If using the `{{render '@component-name'}}` is there a way of making the helper render all variants which exist within the config.json for the referenced component?

**Comment by armstrongb** [comment]
This is pertinent in my case as I was creating a hidden component (which had its own preview file) to create colour chips which I didn't want listed in the component folder but would like to include into the colour documentation page. Currently I'm calling each individual variant via separate `{{render '@component-name--variant-name'}}` calls.
