### ISSUE TITLE
default.context array/object values overridden downstream

### ISSUE THREAD

**Issue by rocketspops** [frctl/fractal#159]
In `./fractal.js` I have:

``` javascript
fractal.components.set('default.context', {
  'scripts': ['/javascripts/jquery-3.1.1.min.js','/javascripts/yellow.js']
});
```

In `./components/example/example.config.js` I have:

``` javascript
module.exports = {
    title: 'Example Component',
    context: {
      'scripts': ['/javascripts/test.js'],
    }
};
```

In `./components/example/example.hbs` I have:

``` html
{{#each scripts}}
<p>{{ this }}</p>
{{/each}}
```

Having read through the docs about context data inheritance, my expectation was that all three script URLs (as defined by the scripts array) would appear in my output. However, the actual result is: 

``` html
<p>/javascripts/test.js</p>
<p>/javascripts/yellow.js</p>
```

It would seem that the downstream context array is replacing items in the `default.context` array. Any ideas? Have I done something incorrectly? 

Thanks!

**Comment by allmarkedup** [comment]
@rocketspops you are not doing anything wrong! This is currently a bug in the way that arrays are merged in context data (related to the somewhat - IMHO - unexpected behaviour of lodash's `defaultsDeep()` method. Unfortunately it's also a behaviour that people are now relying on so it will now require a major version bump to fix in order not to break people's existing code. This will happen but I need some time to work on some other fixes too before I'm able to release that.

Apologies if it's causing you headaches!

**Comment by Chapabu** [comment]
Closing as more discussion is now happening on #123
