### ISSUE TITLE
fractal start --sync does not load local server

### ISSUE THREAD

**Issue by DadaConsultant** [frctl/fractal#160]
On windows environment - when you set up fractal using the guide provided on the site. Running fractal start --sync only try to open fractal.js but fails to launch the web server UI.

**Comment by DadaConsultant** [comment]
Ever mind, resolved the issue. I wasn't running the command from the 'public/' folder created in my root dir

**Comment by allmarkedup** [comment]
@DadaConsultant Glad you got it working - however it shouldn't actually need to be run from the public directory, it should work from the project root directory, so that may be a bug - I'll look into it.

**Comment by schnubb** [comment]
It mustn't be the public directory, but on cmd you have to start fractal from a subdirectory.
Anything new on this bug?

**Comment by siiron** [comment]
Having the same issue on Windows 10 running node v6.9.5 and fractal v1.1.3. Any progress investigating fixing this?

**Comment by mja202** [comment]
Having the same problem on Mac. Work around for me is to start the Fractal CLI and then start the server from there.

Using yarn:
`yarn run fractal`

Within fractal:
` start --sync`

**Comment by serslon** [comment]
I fixed this problem after run command 
`npm install vorpal@1.11.4`

But I have fractal version 1.0.8

**Comment by dkhuntrods** [comment]
@mja202 @serslon There was an issue with an updated version of vorpal, see this thread for more details: #232

**Comment by trickydisco78** [comment]
I#'m having the same issue on windows.

Jsut tried the same as mj202 recommended and it worked!

**Comment by julmot** [comment]
Just went into this issue too. Fractal seems to be a great idea, but it needs more love. The approach of @mja202 isn't a solution, just a workaround.

**Comment by julmot** [comment]
Btw: What you can do to speed it up in one command is: `yarn run fractal -- start --sync`

**Comment by mja202** [comment]
Yes, it was a workaround. However, the current fractal (@1.1.4) works as it should (at least for me).

When fractal is installed globally (`yarn global add @frctl/fractal`) then `fractal start sync` within a project should just work.

**Comment by allmarkedup** [comment]
@julmot @trickydisco78 can you confirm that you are using the latest release (`1.1.4`)? This was caused by a breaking change in the version of Vorpal that was used but it was bumped in the latest release and should work now.

**Comment by julmot** [comment]
@allmarkedup I was using 1.1.4, yes.

**Comment by julmot** [comment]
I was able to get it to work with [this workaround](https://github.com/frctl/fractal/issues/118#issuecomment-255254117).

**Comment by ten1seven** [comment]
After using Fractal on a project for about 9 months, I'm suddenly experiencing this, using version 1.1.5.

I've verified this issue by installing a brand new blank Fractal site on my machine and on a colleague's machine who's never run Fractal before. As the below screenshot shows, after running `fractal start --sync`, Fractal starts, shows a localhost address, then the process seems to quit silently.

<img width="402" alt="2017-09-18 01 52 38 pm" src="https://user-images.githubusercontent.com/137020/30561554-a62cc1d6-9c78-11e7-9b3e-6338f086d3c7.png">

**Comment by julmot** [comment]
I'm experiencing the same. Here's something strange going on, probably due to #346.

**Comment by meerestier** [comment]
Same here

**Comment by dkhuntrods** [comment]
@ten1seven @meerestier 
An unsupervised Greenkeeper update broke 1.1.6 - I've just pushed v1.1.7 that rolls back that update, so if it was due to that, this version should fix it.

**Comment by davidDuymelinck** [comment]
The update fixes the problem for me on macos
