### ISSUE TITLE
fractal with angular application

### ISSUE THREAD

**Issue by tomani77** [frctl/fractal#161]
Hi,
Need help. could you please help me with the sample code to integrate fractal component  into Angular application.

**Comment by allmarkedup** [comment]
Hi @tomani77 - sorry to take so long to get back to you either here or via reply to your email. I don't have a whole lot of Angular experience I'm afraid but I'm not sure that it is the best fit for using with Fractal in it's current form. Fractal renders all templates server-side (although I hope to add client-side rendering in the future) so it may be difficult to integrate in a way that fits with the Angular way of working/organising things.

People _have_ been using it with React, using simple, stateless components (rendered server-side) but I'm not sure if Angular could be integrated in the same way. If you have any thoughts on the matter though I'd definitely appreciate someone with Angular knowledge contributing ideas on how they could work toegther!
