### ISSUE TITLE
Path not working in preview?

### ISSUE THREAD

**Issue by StephenMeehan2016** [frctl/fractal#164]
Hi

I'm struggling to get `path` to work in preview.

I'm using `path` to reference my images in my `public` folder

```
  <img src="{{path '/img/home/commercial-760.jpg'}}" alt="Test"> 
```

This doesn't work? 

`view > source` shows this:

```
   <img src="img/home/commercial-760.jpg" alt="Test">
```

But Google Developer tools shows this error:

```
  GET http://localhost:3000/components/preview/img/home/commercial-760.jpg 404 (Not Found)
```

However, it does work if I add this directly to my `preview.hbs` file:

```
<img src="{{path '/img/home/commercial-760.jpg'}}" alt="Test"> 
```

I can't see where I'm going wrong?

If it helps, I'm using this config in `fractal.js`

```
 fractal.web.set('static.path', path.join(__dirname, 'public'));
```

Is `{{path}} only supposed to work for`preview.hbs`?

Fractal install info  
Project Fractal version: 1.0.8
CLI helper version:  1.0.8

**Comment by custa1200** [comment]
Actually I also just came across this with 
```
<img src="{{path '/images/icon-cc-{{this.cardType}}.svg'}}" />
```
rendering as 
```
<img src="images/icon-cc-visa.svg" />
```
Which means they are broken in the preview, but when I do a static build they are showing up as expected.

Pretty sure I'm on the latest beta.

**Comment by StephenMeehan2016** [comment]
Hi

I've made some progress with this. 

Reading the [docs](http://fractal.build/guide/web) I found this:
     
     fractal.web.set('static.path', __dirname + '/public');

I added it to `fractal.js` and restarted the localhost

When I use this in my component `sector.hbs`

     <img src="{{path '/img/home/commercial-760.jpg'}}" alt="Test">

It outputs this

     <img src="/img/home/commercial-760.jpg" alt="Test">

Notice the `/` at the start of 'src'. This means the image works when I preview the component.

But

When I try to use the component (`sector.hbs`) in a layout, like this:

    {{render '@sector'}}

The component displays as expected, except the 'img' is missing the  `/` meaning the image path is broken.

      <img src="img/home/commercial-760.jpg" alt="Test">

**Is this a bug?**


As a workaround, I'm using `../../` at the start of the `src` instead of the `{{path}}` helper.

    <img src="../../img/home/commercial-760.jpg" alt="Test">

This seems to work in both the component preview, layout preview and when I run `build`

It'd be nice to get the `{{path}}` working though

**Comment by allmarkedup** [comment]
hey @StephenMeehan2016 yes that is definitely a bug in the handlebars adapter (and possibly also the other adapters!) - I will try and get a fix out as soon as I can but I'm pretty behind on all things Fractal at the moment as you can probably tell :-( Glad you have a workaround for now though.

**Comment by allmarkedup** [comment]
Sorry for the long delay in getting to this issue! It should now be fixed in the latest release of `@frctl/handlebars` (v1.1.2). If you still have any issues please let me know.

**Comment by StephenMeehan2016** [comment]
Hi

Unfortunatley, I'm still having a problem with this. I'm running 

- Project Fractal version: 1.1.3 
- CLI helper version: 1.1.3 

I'm using this: `href="{{ path 'article--post' }}"`

In **preview** the output is: `href="article--post"` link works.

In **build** the output is: `href="../../article--post.html"` link doesn't work.

The extra `../../` isn't required. Is there a way to make the build output `href="article--post.html"` instead?

**Comment by dkhuntrods** [comment]
Hi @StephenMeehan2016 I believe that the path helper does require an initial '/' to work correctly, can you try this and see if it helps?
i.e.
```
href="{{ path '/article--post' }}"
```

**Comment by StephenMeehan2016** [comment]
Thanks for the reply, unfortunately it's still not working.

If I add a `/` to the path helper like this: `href="{{ path '/article--post' }}"`

In **preview** the output is: href="/article--post" link doesn't work.

In **build** the output is _still_: href="../../article--post.html" link doesn't work.

I'll have some time next week to record a quick screencast, that will show exactly what I'm doing (wrong).

**Comment by aozora** [comment]
Why this issue is closed? This is still happening in latest stable!!

**Comment by blaasvaer** [comment]
I'm having huge issues here as well, any attention paid to this?

**Comment by blaasvaer** [comment]
I can see in the 24ways example, that they have:

`fractal.components.set('default.preview', '@preview');`

in their fractal.js file, and a preview file placed here:

`src/components/_partials/_preview.html`

Now, I don't see anything in the fractal.js file pointing at this dir in particular. What is it that I'm missing. Has things changed and the docs just being updated or?

**Comment by StephenMeehan2016** [comment]
Hi

I managed to get this working in the end. There might be a better way of doing this, but this is what's currently working for me in version 1.1.5

I have a template file called `nav.hbs` in it I have this HTML.

```
<ul>
    <li><a href="{{ path href-1 }}" title="page-1">page-1</a></li>
    <li><a href="{{ path href-2 }}" title="page-2">page-2</a></li>
    <li><a href="{{ path href-2 }}" title="page-3">page-3</a></li>
</ul>
```
I specify the `ahref` in my `nav.config.js` file:

```
module.exports = {
    // config data here
    title: "Nav",
    status: "prototype",
    context: {  
            
            "href-1": "/components/preview/template-page-1",
            "href-2": "/components/preview/template-page-2",
            "href-3": "/components/preview/template-page-3",
        
    },
    
};
```
The `href` links automatically update depending on if I'm using the `preview` or `build` modes.

Something I noticed when trying to get this to work. 

If I added the path helper `{{ path href-1 }}` to `nav.hbs` but it wasn't added to `nav.config.js` Fractal would display an error. Even after I added the `path` to the  `nav.config.js` it wouldn't work until I restarted Fractal.


Hope this helps!
