### ISSUE TITLE
create ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by johannestroeger** [frctl/fractal#166]
i always appreciate a concise way of reporting issues. maybe it is helpful for you, i suggest e.g. the babel issue_template: https://raw.githubusercontent.com/babel/babel/master/.github/ISSUE_TEMPLATE.md

**Comment by dkhuntrods** [comment]
@johannestroeger Thanks for this - we've added it to [the roadmap under 'Better documentation and examples'](https://github.com/frctl/fractal/issues/197) 
Any objections to us closing the issue?

**Comment by johannestroeger** [comment]
thanks!
