### ISSUE TITLE
Updating fractal.js while fractal is running quits fractal

### ISSUE THREAD

**Issue by davidcmoulton** [frctl/fractal#17]
If Fractal is running, saving a change to `fractal.js`causes Fractal to stop with

```✘ ReferenceError: hasChanged is not defined```

Steps to reproduce:

1. `cd` into a Fractal project directory
1. start Fractal with `fractal`: the Fractal server starts and the `fractal ➤` prompt appears
1. edit the `fractal.js` file, and save it
1. notice that fractal has stopped, saying ```✘ ReferenceError: hasChanged is not defined```
<img width="458" alt="screen shot 2016-03-07 at 21 38 45" src="https://cloud.githubusercontent.com/assets/2893480/13584151/01929dbe-e4ad-11e5-8943-dde4ef2b2f08.png">

**Comment by allmarkedup** [comment]
Hi @davidcmoulton - I believe that this issue has been fixed in a recent update. Can you try updating to the latest version and see if it resolves the issue?

**Comment by davidcmoulton** [comment]
Updated to v0.9.10 and it's now fixed. Closing.
