### ISSUE TITLE
Collect templates in a sub-folder (missing helper)?

### ISSUE THREAD

**Issue by blaasvaer** [frctl/fractal#170]
Things quickly starts to get messy with all files, and variants for config etc., in the same directory. So I put all my templates into a sub-folder – templates – within each component.

Now, this cause an error: Error rendering component
Missing helper: "toLowerCase"

This is a helper that I define and use in my index.js file (in the component root). But I guess that Handlebars that generate the component output cannot get to this helper.

How can I fix this issue (somehow point it to the index.js file which contain the defined helper)?

**Comment by allmarkedup** [comment]
Hi @blaasvaer - How/where are you defining and adding the helpers to the handlebars instance? If you are adding them in within your fractal.js file then it should not matter where your component lives in the directory hierarchy.

Can you share you config files (or the relevant parts of them) to help me better understand what is going on here?

**Comment by blaasvaer** [comment]
It's part of my own code. And I wouldn't like to have to recreate all my Handlebars Helpers that I use in my code in fractal.js as well. It should somehow be possible to use Handlebars in your own project without having it collide with the fractal.js instance of Handlebars.

**Comment by blaasvaer** [comment]
Fractal should maybe just load the module code (that is, my code) and take it from there. Maybe even traverse my code and pull out any Handlebars Helpers, and add them whereever it makes sense ...

**Comment by blaasvaer** [comment]
Any new thoughts on this?

**Comment by allmarkedup** [comment]
@blaasvaer - I'm afraid that I'm still a bit unsure of what you are asking for here. If you want to share handlebars helpers, you can always create a separate helpers.js file that exports and object of helpers. Then you can require that both in your fractal.js file and your own application code.

I.e. export something like this that you can then import as required:

```js
// helpers.js
module.exports = {
   toUpperCase: function(str){
       return str.toUpperCase();
   }
}
```

Would that solve it?

**Comment by blaasvaer** [comment]
I don't think so, as I wouldn't like to make that kind of code coupling to a specific library. And it would also mean, that I would have to take fractal into account when developing. I'd like it to stay out of my way as I develop. It's fine that I have to configure a library, but to tie it to my code directly, I don't like.

Wouldn't it somehow be possible for fractal to actually load the corresponding module (js file)? And somehow traverse it for any helpers ... any ideas are welcome.

And I think a great goal for fractal should be to decouple it as much as possible from the project itself.

**Comment by blaasvaer** [comment]
But, just to get on with the project. How would I add the Handlebars helper to the fractal.js file?

module.export doesn't work. And simply adding a named function doesn't either.

**Comment by allmarkedup** [comment]
Docs on adding handlebars helpers to Fractal are here: http://fractal.build/guide/core-concepts/views#customising-handlebars 

And you can find a pretty good overview of how Node module import/exports work here: https://www.sitepoint.com/understanding-module-exports-exports-node-js/

Hopefully that helps :-)

**Comment by blaasvaer** [comment]
Thanks, I'll check it out as soon as I can. There's a typo in the docs (strat):

Note that you will need to run npm install --save @frctl/handlebars to install the @frctl/handlebars package into your project directly before you can strat customising it.
