### ISSUE TITLE
Can the panels shown being customised as per component?

### ISSUE THREAD

**Issue by riccardoerra** [frctl/fractal#171]
I customised the theme in fractal.js because I only need to show few panels.
Is it possible to show only certain panels for some components and other panels for other components?
Asking this because I'm trying to find a workaround to something I don't see Fractal is offering at the moment.
I would like to show in the sidebar the compiled main.css file used for styling all the components. Don't think this is possible at the moment so I thought a solution could be to have a component with no HTML and just main.css and a config file. Because of this "weird" component I only need to show the Assets panel.
In general would nice to have the option to show assets in the sidebar.

**Comment by allmarkedup** [comment]
@riccardoerra you can't currently customise the panels on a per-component basis I'm afraid :-(

Better support for displaying/downloading assets is very high on my list of things to add in though and some sort of sidebar asset listing is definitely on my radar.

**Comment by riccardoerra** [comment]
@allmarkedup thanks anyway.
Found a workaround in the meantime: customising the Nunjucks templates with if/else conditions using the config file of the components.
Something like: if the component has the tag x then render only the panel x. Seems to work fine so far.
Sidebar asset listing would be great!

**Comment by lawlesscreation** [comment]
@riccardoerra could you expand a little on how you did this? I'd also like to be able to disable certain panels on a per-component basis.

Thanks!

**Comment by riccardoerra** [comment]
@lawlesscreation That was months ago. As far as I remember I followed what's in the guide, http://fractal.build/guide/customisation/web-themes , and ended up adding a couple of if/else statements in the some of Mandelbrot Nunjucks templates. Was not that difficult. I suggest to give it a go and see how much you manage to edit.

**Comment by f-g-s** [comment]
I had the same problem. Just use the automatic ID of the page and the class of the panel and override the panel with CSS in a custom theme. Not the best way, but it works in seconds.

```
# browser-2f89ecd869b4fcc17500c5648f9c5015 .Browser-tab - html, # browser-2f89ecd869b4fcc17500c5648f9c5015 .Browser-tab - resources {
     display: none;
}
```
![image](https://user-images.githubusercontent.com/7393703/54787646-ab6f9780-4c2c-11e9-9f3d-bdc55c052042.png)
