### ISSUE TITLE
refs to example projects availability

### ISSUE THREAD

**Issue by cdaringe** [frctl/fractal#174]
hello:

1st, thanks for this great project.  it's already evident that fractal is above-and-beyond the other pattern-lib tools, for reasons which you are already aware!

are there any reference projects that use fractal available for viewing?  i may have already read past one in the docs, but can't seem to find it!

thx!

**Comment by cdaringe** [comment]
if anyone knows of any off hand, a url would be great!

**Comment by allmarkedup** [comment]
@cdaringe I'll try and dig up some URLs for you, some people have linked to theirs in the past - there is no 'official' demo site up yet unfortunately :-(

One i know of offhand is https://ubisend.medium.io/ - it doesn't have any docs but has quite a few components. I'll try and collect some other links and add them to the docs when I can.

**Comment by cdaringe** [comment]
no sweat!
