### ISSUE TITLE
Using Fractal with webpack hotloading

### ISSUE THREAD

**Issue by 1stevengrant** [frctl/fractal#175]
Only been using Fractal for a couple of days but man, I'm so in love. I think this is the best pattern generation tool out there.

I love how bare bones it is compared to the others out there.

So I typically run BrowserSync over the top of an application to give me Sass and JS change injection via Gulp Sass and Webpack. The Sass stuff was easy because it produces a CSS file into a directory but hotloading works a little differently.

This is how I usually integrate webpack with my Browsersync instance. Have tried replacing Browsersync with Fractal instances without much luck, I always get a 404 on my JS.

```
if(global.production) return

var browserSync       = require('browser-sync')
var gulp              = require('gulp')
var webpack           = require('webpack')
var webpackMultiConfig = require('../lib/webpack-multi-config')
var config            = require('../config')
var pathToUrl         = require('../lib/pathToUrl')

var browserSyncTask = function() {

  var webpackConfig = webpackMultiConfig('development')
  var compiler = webpack(webpackConfig)
  var proxyConfig = config.tasks.browserSync.proxy || null;

  if (typeof(proxyConfig) === 'string') {
    config.tasks.browserSync.proxy = {
      target : proxyConfig
    }
  }

  var server = config.tasks.browserSync.proxy || config.tasks.browserSync.server;

  server.middleware = [
    require('webpack-dev-middleware')(compiler, {
      stats: 'errors-only',
      publicPath: pathToUrl('/', webpackConfig.output.publicPath)
    }),
    require('webpack-hot-middleware')(compiler)
  ]

  browserSync.init(config.tasks.browserSync)
}

gulp.task('browserSync', browserSyncTask)
module.exports = browserSyncTask
```

Has anyone managed anything similar?

**Comment by johannestroeger** [comment]
currenlty i am using the "built-in" [browserSync of fractal](https://github.com/frctl/fractal/blob/6831f8000a5ffb9f8ba7d0977f9320dc0d198f49/src/web/server.js#L116) and extending the configuration by my own needs.

**Comment by stevieg83** [comment]
@johannestroeger have an example config I could take a peek at?

**Comment by johannestroeger** [comment]
@stevieg83 https://gist.github.com/johannestroeger/eea66b4a57ad107f9b466fba2b052ae0

**Comment by stevieg83** [comment]
thanks @johannestroeger - will investigate that

**Comment by allmarkedup** [comment]
@stevieg83 great to hear that you are liking Fractal. I have zero webpack experience I'm afraid so can't add much to this - did you manage to get @johannestroeger's setup working in the end?

**Comment by johannestroeger** [comment]
@allmarkedup yes that's a gist we are using in our team.

**Comment by tlenex** [comment]
I've created a #180 PR. It should help with setting/debugging configuration of BrowserSync with custom webpack middleware. Thanks for gist @johannestroeger it was helpfull!

**Comment by simondib** [comment]
hey @stevieg83 or @johannestroeger have either of you successfully got Webpack's HMR working with Gulp/Fractal? I'm almost there but each time Webpack recompiles the bundle it's instead reloading the whole page and therefore losing the HMR instance. Any ideas?

**Comment by magicspon** [comment]
@simondib @stevieg83 have you managed to get this working. I'm no so fussed about hot module reloading, but I would like my bundle to be found by fractal.

code
```
import fractal from '../fractal'
import gulp from 'gulp'
import webpack from 'webpack'
import webpackConfig from './webpack.config.babel'
import {
	pathToUrl
} from '../libs/utils'
import path from 'path'

export default function browserSyncTask() {


	const env = global.production ? 'production' : 'development'
	const config = webpackConfig(env)
	const compiler = webpack(config)
	const proxyConfig = SERVER.proxy || null
	const logger = fractal.cli.console

	if(typeof proxyConfig === 'string') {
		SERVER.proxy = {
			target: proxyConfig
		}
	}

	// Resolve path from PWD
	if(SERVER.server && SERVER.server.baseDir) {
		SERVER.server.baseDir = path.resolve(process.env.PWD, SERVER.server.baseDir)
	}

	// Resolve files from PWD
	if(SERVER.files) {
		SERVER.files = SERVER.files.map(function (glob) {
			return path.resolve(process.env.PWD, glob)
		})
	}

	const _server = SERVER.proxy || SERVER.server

	_server.middleware = [
		require('webpack-dev-middleware')(compiler, {
			stats: 'errors-only',
			publicPath: pathToUrl('/', config.output.publicPath)
		}),
		require('webpack-hot-middleware')(compiler)
	]

	const server = fractal.web.server({
		..._server,
		sync: true,
		port: 3000
	})

	server.on('error', err => logger.error(err.message))

	return server.start().then(() => {
		logger.success(`Fractal server is now running at ${server.url}`)
	})
}

gulp.task('browserSync', browserSyncTask)
```

**Comment by magicspon** [comment]
@simondib did you ever get anywhere with this?

**Comment by simondib** [comment]
@magicspon unfortunately not, the above suggestions didn't work for me but have seemed to work for others.
