### ISSUE TITLE
Container components

### ISSUE THREAD

**Issue by ugreen** [frctl/fractal#177]
Is it possible to create some kind of container component? For instance, bootstraps collapsibles.

I have a collapsible component that renders other components inside, so I can demonstrate the show/hide functionality?

Cant find anything in the docs about it, so I guess its a feature request :)

**Comment by johannestroeger** [comment]
i think what you are looking for is #93

**Comment by ugreen** [comment]
While #93 is definitely useful, its not what im looking for.

Simplified example:

Container component:
```
<div class="accordion">
    <h3 class="accordion-title">Title</h3>
    <div class="accordion-content">
        {{ other components rendered here }}
    </div>
</div>
```
I would like to use that in another component like so (semi pseudo code):
```
{{> @accordion start}}
    {{ render '@someComponent' }}
    {{ render '@someOtherComponent' }}
    {{> @banner-big}}
{{> @accordion end}}
```
Another way to use it could be soemthing like:
```
{{ render '@accordion' dataContainingOtherComponentHandles }}
```
But that would make it harder to see the immediate structure of the component.

**Comment by allmarkedup** [comment]
hey @ugreen - I think what you are looking for can be achieved using the [Handlebars layouts](https://www.npmjs.com/package/handlebars-layouts) helpers for Handlebars. 

You can read more on how to add helpers etc to the Handlebars instance that Fractal uses here: http://fractal.build/guide/core-concepts/views#customising-handlebars (in fact towards the bottom of that page is an example that references `handlebars-layouts` specifically).

Would that solve your issue?

**Comment by ugreen** [comment]
Yes! Exactly! I knew my brain went of on the wrong tangent. It should be handled by handlebars (harr harr) - and not by fractal. Thanks

**Comment by allmarkedup** [comment]
Excellent! I'll close this now then :-)
