### ISSUE TITLE
Component resources in subfolder?

### ISSUE THREAD

**Issue by ugreen** [frctl/fractal#179]
Is it me or is it impossible to have a component's resources in a subfolder of the component folder?
It would really help organisation if I could put a components images in a images folder.

If it is impossible, can it be implementet? Im thinking it might collide with the whole collections thing.

**Comment by allmarkedup** [comment]
@ugreen Yes you are correct, at the moment the parser only looks at the immediate children of the component folder. It shouldn't collide with collections so this is definitely something that could be added as it would definitely be a useful improvement.
