### ISSUE TITLE
Make it easy to turn off statuses feature

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/fractal#181]
If I don’t want to use the statuses feature on my project, how I might I turn this off (and easily)? Providing an empty object for the `statuses` setting doesn’t seem to work.

Also, should statuses be set by default? Probably, but it’s worth asking.

**Comment by allmarkedup** [comment]
@paulrobertlloyd you can them disable globally by using: `fractal.components.set('default.status', null);` If you add a specific status to an item that will then show up just for that item only.

As they are already set by default I think they should probably stay that way, especially as they are pretty easy to disable.

**Comment by paulrobertlloyd** [comment]
Ah, fantastic. Thanks Mark!

**Comment by paulrobertlloyd** [comment]
…and now I see the bit in the docs where this is mentioned. Doh!

**Comment by allmarkedup** [comment]
:-) I couldn't remember if it was in the docs or not myself tbh!
