### ISSUE TITLE
Setting `hidden` on a collection doesn't hide it's children.

### ISSUE THREAD

**Issue by jamesgorrie** [frctl/fractal#182]
I would expect all children to be hidden.
An example of it not working can be seen at wellcometrust/wellcomecollection.org#113.

**Comment by allmarkedup** [comment]
Ah yes good catch, thanks - that is indeed a bug. It should be inherited the same way that setting the property via the `_` prefix in the filename is.

**Comment by jamesgorrie** [comment]
Brilliant - I couldn't quite find in the code where it might be doing that - I'll see if I can take a look later.

**Comment by allmarkedup** [comment]
@jamesgorrie the code around all the filesystem/config parsing is a little 'convoluted' right now to say the least... something I want to get simplified as soon as possible. Let me know if you do dig any have any questions in the meantime however.

**Comment by allmarkedup** [comment]
This should be fixed now by 188df19a6d29bddefc747fe71f1e009ececda31f - I'll get a new release out shortly.

**Comment by jamesgorrie** [comment]
@allmarkedup nice! Thanks, I'll more than likely be digging through some of the code as we're using fractal quite extensively.
