### ISSUE TITLE
Naming components via 'handle' makes variants two directories deep

### ISSUE THREAD

**Issue by davidpmccormick** [frctl/fractal#183]
We've chosen to name each of our components `index.njk` and supply the `handle` property for Fractal to resolve. This seems to force an unwanted second level of nesting when viewing variants of components:

![screen shot 2016-11-29 at 12 13 15](https://cloud.githubusercontent.com/assets/1394592/20709476/9182c190-b62d-11e6-9900-6c1e480f1615.png)

We only want the top-level 'Page Description' in the screenshot above and can't see a way around it in the docs?

**Comment by allmarkedup** [comment]
Hi @davidpmccormick - that definitely sounds like a bug! I'll try and dig into it and see if I can get a fix out at some point soon.

**Comment by allmarkedup** [comment]
@davidpmccormick I'm just trying to recreate this - do you think you give me a little more detail? A screenshot of the relevant bit of folder/file structure would be great, plus any config that might be useful. Thanks!

**Comment by davidpmccormick** [comment]
@allmarkedup – sure. Here's the view file structure with the page-description component inside the components directory:

![screen shot 2016-12-01 at 10 21 37](https://cloud.githubusercontent.com/assets/1394592/20790491/71fc1338-b7b0-11e6-8039-33060e4566d2.png)

and this is the contents of the page-description's index.config.json:

```json
{
  "name": "page description",
  "handle": "page-description",
  "label": "Page description",
  "variants": [{
    "name": "default",
    "label": "A (article)",
    "notes": "Article title lock-up.",
    "context": {
      "modifiers": ["a"],
      "intro": "States of Mind",
      "title": "Inspired: Alchemists and housewives around a long table",
      "outro": "September 9th 2016",
      "icon": "Clock"
    }
  }, {
    "name": "hn",
    "label": "B (library item)",
    "notes": "Library item title.",
    "context": {
      "modifiers": ["b"],
      "intro": null,
      "title": "On the Origin of Species by Means of Natural Selection, or the Preservation of Favoured Races in the Struggle for Life",
      "outro": null,
      "icon": null
    }
  }]
}
```

**Comment by dkhuntrods** [comment]
@davidpmccormick Just a quick check, adding `collated: true` in the `*.config.json` file doesn't do what you need in this case?
/cc @allmarkedup

**Comment by davidpmccormick** [comment]
@dkhuntrods Thanks – I had thought it might, but that outputs each variant on the one page. We'd still like individual pages for each variant (in this instance).

**Comment by dkhuntrods** [comment]
@davidpmccormick Fair enough! So in that case it still outputs the doubly nested folders for you?

**Comment by davidpmccormick** [comment]
No, that's a good point – with `collated: true`, we don't get nested folders:

![screen shot 2016-12-14 at 11 59 49](https://cloud.githubusercontent.com/assets/1394592/21181260/f845a1ae-c1f4-11e6-89c2-7cd387f25fb0.png)

But we (obviously) only get the one view for all variants.

**Comment by dkhuntrods** [comment]
Hi @davidpmccormick, apologies we've taken so long on this. I'm going to take a look at this today.

**Comment by dkhuntrods** [comment]
@davidpmccormick Ok, what's happening here is that as far as Fractal is concerned, this is a collection called 'Page Description' (the top level folder) with a component inside it called 'Page Description'. Because the template file has a different name than its folder, Fractal has no way of knowing that they're associated. Adding a handle allows you to give what would normally be an 'Index' component the same name as the folder, but it doesn't directly associate it.
Unfortunately, while this doesn't help you right now, we've got some plans for future updates that should make this easier in future!
