### ISSUE TITLE
Fractal with PostCSS ?

### ISSUE THREAD

**Issue by ethyde** [frctl/fractal#184]
Hi,

I try to use Fractal on a project who use webpack and PostCSS, but at this moment I don't find how to do it, can you help me ? I have to make an adapter ?

**Comment by tlenex** [comment]
You can build scss files outside fractal structure and include it to your `_preview.hbs` or built by fractal html page component.

**Comment by ethyde** [comment]
@tlenex Why not, but with BrowserSync/HMR I have to re-build and re-inject all components stylesheets for every modification ?

**Comment by johannestroeger** [comment]
@ethyde you might have a look at #175

**Comment by tlenex** [comment]
@ethyde when you `serve` files you have to inject css only once to `_preview.hbs` and thats it, each component you create using that preview should have access to your (re)compiled css file, then css watch and BrowserSync's `reaload()` should be enought to refersh styles for your components. 
I hope you don't use hashes in filenames for developing stage of application - after each hash change you will have to reinject files into preview.

At `build` task in your `dist` folder you need do inject css/js after (1)fractal was built and (2)webpack compiled, into all of your built html fractal "page" components. I did it with simple gulp tasks - first copy all assets and `page-*.html` -> `*.html` files into new `public_html` dir, then inject is made for every html in that dir. Just pay attention to your relative paths.
