### ISSUE TITLE
Trying to use with Handlebars PHP

### ISSUE THREAD

**Issue by rogden** [frctl/fractal#190]
I would like to include our Fractal component site as a dependency in a WordPress site we are building. We are going to use Handlebars PHP so that we can render the components we created in Fractal. However,  referencing partials using their handle in Fractal is not supported (since it seems custom to Fractal). Can you point me in the direction of the code that is handling that so we can look to implement it in Handlebars PHP?

Thanks,
Ryan

**Comment by allmarkedup** [comment]
@rogden - We have just done something similar, and the approach that worked the best for us was to use Fractal to generate a JSON file of `@handle` => path mappings. Then you can pull that JSON file in to your site and use an Handlebars PHP 'array loader' (or other custom loader) to fetch the correct file when it comes across the handle.

If you add the following to your fractal.js file then Fractal will regenerate a mapping file each time the components change when 'watching', and it will also give you a custom command (`fractal pathmap`) that you can run at any time to manually generate the mapping.

You may well need to customise it to your exact needs but it should hopefully get you started!

```js
const path = require('path');
const fs = require('fs');

function exportPaths() {
    const map = {};
    for (let item of fractal.components.flatten()) {
        map[`@${item.handle}`] = path.relative(process.cwd(), item.viewPath);
    }
    fs.writeFileSync('components-map.json', JSON.stringify(map, null, 2), 'utf8');
}

fractal.components.on('updated', function(){
    exportPaths();
});

fractal.cli.command('pathmap', function(opts, done){
    exportPaths();
    done();
});
```

Let me know how you get on.

**Comment by rogden** [comment]
This is great. Thanks for the info. I'll let you know how we make out.

**Comment by vincentvpham** [comment]
@allmarkedup: do you have an example how to accomplish what you described in handlebars php? I can get the filepath to the component to render in place of the @handle, but can't get the hbs file to render

**Comment by rogden** [comment]
@vincentvpham I created a Gist with some files I created in order to use the Fractal .hbs files in PHP (A WordPress site specifically). https://gist.github.com/rogden/6ca5062d4512a1b11dafa6747348735e

**Comment by vincentvpham** [comment]
@rogden Thanks! We were able to get it working in our setup with a few adjustments. Much appreciated!
