### ISSUE TITLE
Fractal gets label vs title the wrong way around in sidebar nav

### ISSUE THREAD

**Issue by emilbjorklund** [frctl/fractal#193]
It seems fractal gets the purpose of `title` vs `label` settings mixed up: the Fractal.build docs say `label` should be used for navigation, and `title` for `<title>` (?) but I get the opposite result when using them. Using: 

```
fractal.docs.set('label', 'Foo');
fractal.docs.set('title', 'Bar');
```
...gets me ”Bar” as the navigation label in the sidebar. Same thing goes for `components.set`.
Am I misreading docs or is this the wrong way around?

I tested this by creating a new project from scratch, installing fractal (v. 1.0.11) and using the following `fractal.js`-file:

```javascript
const fractal = module.exports = require('@frctl/fractal').create();
fractal.set('project.title', 'Test');
fractal.web.set('builder.dest', __dirname + '/www');
fractal.components.set('path', __dirname + '/components');
fractal.components.set('ext', '.html');
fractal.components.set('label', 'Bar components');
fractal.components.set('title', 'Foo components');
fractal.docs.set('path', __dirname + '/docs');
fractal.docs.set('label', 'Foo docs');
fractal.docs.set('title', 'Bar docs');
```

That gets me a label of ”Foo components” and ”Bar docs” in the sidebar.

**Comment by dkhuntrods** [comment]
@emilbjorklund This has been fixed at the origin in the [Mandelbrot theme](https://github.com/frctl/mandelbrot) and a patch will be released shortly.
