### ISSUE TITLE
I want to render a particular component variant based on context data

### ISSUE THREAD

**Issue by custa1200** [frctl/fractal#195]
I am managing multiple brands and want to be able to load or a variant of a different brand throughout my components.

I have a bunch of links that are contained in the polling component
```  
{{render '@o-aem-footer-social-links' pageContext merge=true}}
```

But I'd like to be able to load a specific retailer variant based on "retailer" context data like 
```
{{render '@o-aem-footer-social-links--{{retailer}}' pageContext merge=true}}
```

**Comment by jveens** [comment]
I'm trying to do something similar with rendering different icons in a component, based on context data. We were using the handlebars 'lookup' function to render out the partials, but since we want to now integrate fractal this is an issue. Any suggestions are welcome.

**Comment by kingmauri** [comment]
same here. any soloutions?
not even the loopup function works for me. :(

`{{render '{{myspecialComp}}' }}` doesnt work...

**Comment by tlenex** [comment]
Check this out #239 but this solution might be unstable in the future. Use this on your own risk.

**Comment by dkhuntrods** [comment]
A lookup helper might work better here, see here: https://github.com/frctl/fractal/issues/278#issuecomment-316977660
