### ISSUE TITLE
Nunjucks recommend the .njk extension

### ISSUE THREAD

**Issue by robinwhittleton** [frctl/fractal#196]
https://mozilla.github.io/nunjucks/templating.html#file-extensions

>Although you are free to use any file extension you wish for your Nunjucks template files, the Nunjucks community has adopted `.njk`. If you are developing tools or editor syntax helpers for Nunjucks, please include recognition of the `.njk` extension.

Currently [Fractal uses `.nunj`](https://github.com/search?q=repo%3Afrctl%2Ffractal+extension%3Anunj&ref=searchresults&type=Code&utf8=%E2%9C%93), it might be worth fixing this (although presumably for a breaking future 2.0 release).

**Comment by paulmsmith** [comment]
I've seen `.nunj` in the wild but if that's the recommendation then probably good make this change. I had to add the following to atom config to get it to use the correct syntax for the extension:

```cson
"*":
  core:
    customFileTypes:
      "text.html.nunjucks": [
        "nunj"
        "nhtml"
      ]
```

**Comment by allmarkedup** [comment]
Hey guys, yes I'm all for moving to `.njk` but it will definitely have to be a major version bump. Unfortunately I either missed this recommendation or it didn't exist when I was first putting the Nunjucks support for Fractal together. `.nunj` always sounded a little wrong though :-)

I'll make sure that this change gets factored in to the appropriate future release.

**Comment by paulmsmith** [comment]
The documentation for nunjucks has been changing since you started Fractal. Imagine it wasn't there.
