### ISSUE TITLE
Documentation: How to enable (and configure) template helpers (where applicable)

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/fractal#2]
*Adding as an issue if only to serve as a reminder to add to documentation.*

If I wish to add additional helpers for my template language (i.e. handlebars), how would I enable (and optionally configure) these?

**Comment by paulrobertlloyd** [comment]
[From Mark](https://gist.github.com/allmarkedup/4f9e42592157894ec7d4):

> You can register as main helpers as you like in the 'helpers' object - the name you give them there will be the name that they are referenced by in your templates.

```js
'use strict';

const fractal  = require('@frctl/fractal');
const markdown = require('helper-markdown');

// other fractal config here...

fractal.engine('handlebars', '@frctl/handlebars-adapter', {
    helpers: {
        markdown: markdown()
    }
});
```

**Comment by allmarkedup** [comment]
Thanks mate - will be adding a section on template engines to the docs soon. Will leave this open as a reminder :-)

**Comment by allmarkedup** [comment]
Added to docs in 12198a82a3c6e16a27e27d8322c4d72fe9d48844
