### ISSUE TITLE
Webpack HMR forcing full page reload

### ISSUE THREAD

**Issue by simondib** [frctl/fractal#203]
Loving Fractal, however I can't seem to get Webpack's hot module replacement working as expected. On my previous Gulp/BrowserSync/Webpack setup it works perfectly.

HMR reports as loaded in the console, but whenever I re-save any .js, Fractal will reload the entire page, defeating the purpose of HMR. 

Any ideas why this might happen? Here's snippets from my Fractal task in Gulp.

```
fractal.web.set('builder.dest', 'build-fractal'); 

fractal.web.set('server.syncOptions', {
  middleware: [
    require('webpack-dev-middleware')(compiler, {
      stats: 'errors-only',
      publicPath: pathToUrl('/', webpackConfig.output.publicPath)
    }),
    require('webpack-hot-middleware')(compiler)
  ]
})

const server = fractal.web.server({
    port: 3333,
    sync: true,
    watch: true,
    notify: true,
    browser: ['google chrome']
  });

  server.on('error', err => logger.error(err.message));

  return server.start().then(() => {
    logger.success(`Fractal server is now running at ${server.url}`);
  });

**Comment by allmarkedup** [comment]
hey @simondib - I'm afraid that I don't have much experience with webpack but [this issue](https://github.com/frctl/fractal/issues/175) has some discussion + a gist that people seem to have been using to configure it to work correctly with Fractal. Is that of any help in your situation?

**Comment by simondib** [comment]
Thanks @allmarkedup, I did take a look at that thread but I'll have another read now and see if it makes any more sense.

**Comment by dkhuntrods** [comment]
@simondib were you able to find a configuration that worked for you?

**Comment by simondib** [comment]
Unfortunately not @dkhuntrods. On file save, HMR reports as rebundling on save, but then the page reloads immediately after. So it looks like HMR is working but a reload is still being triggered either through Webpack or BrowserSync..

**Comment by yhuard** [comment]
@simondib Fractal monitors file changes internally and triggers a full page reload when it detects an event (`source:updated`, `add` or `change`). Fortunately, [you can bypass](https://github.com/frctl/fractal/blob/7aa6a0fdcd15ea1060ee6c659387c6b716e93ac3/src/web/server.js#L169) this full reload by setting the `ignored` parameter of [watchOptions](https://www.browsersync.io/docs/options#option-watchOptions) correctly.

Here's a configuration I use that allows webpack HMR to update the page without doing a full reload:

```
fractal.web.set('server.syncOptions', {
  middleware: [
    webpackDevMiddleware(bundler, {
      publicPath: webpackConfig.output.publicPath,
      stats: { colors: true },
    }),
    webpackHotMiddleware(bundler),
  ],
  watchOptions: {
    ignoreInitial: true,
    ignored: '**',
  },
});
```

**Comment by yhuard** [comment]
Please note that you will have to manually refresh the page if you want Fractal to show the updated information in the "Assets" tabs (or wherever it might appear)

**Comment by simondib** [comment]
@yhuard thanks for the tip, although it doesn't seem to be honoring the ignore rule and so is still trigger a full reload. 

`fractal.web.set('server.syncOptions', {
  open: true,
  browser: ['google chrome'],
  notify: true,
  middleware: [
    require('webpack-dev-middleware')(compiler, {
      stats: 'errors-only',
      publicPath: pathToUrl('/', webpackConfig.output.publicPath)
    }),
    require('webpack-hot-middleware')(compiler)
  ],
  watchOptions: {
    ignoreInitial: true,
    ignored: ['**/*.js']
  }
})

  const server = fractal.web.server();

  server.on('error', err => logger.error(err.message));

  return server.start().then(() => {
    logger.success(`Fractal server is now running at ${server.url}`);
  });
`

I'll keep playing around as this definitely sounds like it should be possible.

**Comment by dkhuntrods** [comment]
@yhuard @simondib Hmm, strange...the relevant portions of both your configs are almost identical. I'll investigate this a bit more.

**Comment by simondib** [comment]
@yhuard would it be possible to take a peek at your webpack.config?

**Comment by yhuard** [comment]
@simondib sure, [here it is](https://github.com/ec-europa/europa-component-library/blob/chore/webpack/webpack.config.js) (it's still WIP)

**Comment by simondib** [comment]
@yhuard thank you, very much appreciated!

**Comment by dkhuntrods** [comment]
@yhuard @simondib I've been looking at this and can't actually replicate, so just wanted to check a few things, but first, has the config @yhuard posted just above helped?
If not, can you check you're running Fractal > v1.1? The watchOptions/ignore functionality was only added at that point.
Otherwise, your best bet might be to disable Fractal's built in BrowserSync, and add your own config setup. By default, if no server.sync options are set, and if you run `fractal -w` rather than `-s`, fractal won't use it.

**Comment by simondib** [comment]
@dkhuntrods turns out I _was_ using an older version. Using 1.1 it now doesn't do a full page reload, but instead only reloads the iframed portion of the page (ie, the component container).

Here's a console log - highlighted portion is what occurs on file save of my .js (which I've attempted to ignored under the BrowserSync watchOptions)

![image](https://cloud.githubusercontent.com/assets/7483506/22911598/9781c834-f2b4-11e6-8b6c-6d7cacab477a.png)

**Comment by dkhuntrods** [comment]
@simondib Ok, well we're making *some* progress! :)
And don't worry about the troubleshooting, it's not clear where the issue might originate, and if it's a Fractal problem we certainly want to get to the bottom of it. 
Let me know if the separate instance works better for you!

**Comment by 7iomka** [comment]
Я наконец-то избавился от двойной перезагрузки страницы!
Я отключил по умолчанию sync в настройках запускаемого fractal server.
Вот как выглядят функционально важные части:
```
// Serve dynamic site (Fractal)
function serve() {
  const server = fractal.web.server({
     sync: false,
     watch: true,
     injectChanges: true,
     proxy: 'http://localhost:3030/', // localhost served url
  });
// in my build i use main instance of browserSync for use that in custom tasks(!)
  browserSync.init({
      injectChanges: true,
      notify: true,
      port: 3030,
      proxy: 'http://localhost:3000/', // localhost served url of fractal browserSync instance
  });

  const logError = err => logger.error(err.message)
  const logRunning = () => logger.success(`Fractal server is now running at ${server.url}`)

  server.on('error', logError)
        .start()
        .then(logRunning)
};
```
```
/** gulp task for webpack - js files **/
gulp.task('webpack', function(callback) {
  let firstBuildReady = false;
  //
  function done(err, stats) {
    firstBuildReady = true;

    if (err) { // hard error, see https://webpack.github.io/docs/node.js-api.html#error-handling
      return;  // emit('error', err) in webpack-stream
    }

    gulplog[stats.hasErrors() ? 'error' : 'info'](stats.toString({
      colors: true
    }));

  }

  /** Webpack options **/
  let options = Object.create(webpackConfig);
  return gulp.src(`${paths.src}/app.js`)
      .pipe(plumber({
        errorHandler: notify.onError(err => ({
          title:   'Webpack',
          message: err.message
        }))
      }))
      .pipe(webpackStream(options, webpack, done)) 
      .pipe(gulpIf(!isDevelopment, uglify()))
      .pipe(gulp.dest(`${paths.dest}/assets/scripts`))
      .on('data', function() {
        gulplog.debug('callback is called'+ callback.called == true);
        if (firstBuildReady && !callback.called) {
          callback.called = true;
          callback();
        }
      });

});
```
And I watching manually all fractal components with this api callback
```
fractal.components.on('updated', function(e){
    // console.log('fractal components updated', e);
    if(e.event === 'change') {
      if (e.isResource) {
        
          console.log('JS or CSS files changed: ', e.path);
      }
      else {
        console.log('fractal config file or template file changed:  ', e.path);
        browserSync.reload();
      }
    }

});
```

This config make page-reload once, if js files included with require or import in entry js file of webpack.
This config allows me prevent reloading the page if I change the stylesheet file of the component, instead of this browserSync inject changes in the page with last line in my scss task:
```
.pipe(browserSync.stream({ match: '**/*.css' }));
```

**Comment by elisechant** [comment]
Are your sure that your problem isn't as simple as adding `module.hot.accept()` inline?

**Comment by dgautsch** [comment]
@simondib did you ever get this working?
