### ISSUE TITLE
Referencing other docs

### ISSUE THREAD

**Issue by sensecall** [frctl/fractal#205]
I may have missed this in the documentation, but I can't work out how to reference docs from within another doc. I imagine it uses `{{ @[handle] }}` somehow, but can't quite work it out?

**Comment by dkhuntrods** [comment]
Hi @sensecall, unfortunately it's not built in to Fractal, but you could write a custom helper in your template language of choice (looks like you're using handlebars?) that could do this for you.
It would be something along the lines of this: [Using the API](http://fractal.build/guide/docs/dynamic#using-the-api)

**Comment by dkhuntrods** [comment]
@sensecall are you still struggling with this, or do you mind if we close this issue now?

**Comment by sensecall** [comment]
Still struggling but that's my lack of handlebars knowledge. Thanks for the guidance.
