### ISSUE TITLE
It is possible to declare "render" functionality in nunjucks macros?

### ISSUE THREAD

**Issue by 7iomka** [frctl/fractal#206]
It is possible to declare "render" functionality in macro-s(nunjucks templates) ?
For example:
```
{% macro form_input(config) %}
	{% if config.component %}
		{% render "@"+config.component, config.component.config %}
	{% else %}
		{% render "@button" %}
	{% endif %}
{% endmacro %}
```
In this case i see this error:

> 
> **Error rendering component**
> (unknown path) SyntaxError: Unexpected token u in JSON at position 0

I don't know how to resolve this problem...
I found a way out of this situation, but solution is not suitable for all my tasks!(
My solution:
```
{% macro form_input(config) %}
	{% if config.component %}
		{% block config.component %}{% endblock %}
	{% else %}
		{% block button %}{% endblock %}
	{% endif %}
{% endmacro %}

**_//in corresponded component_**
{% from "form-macros.html" import form_input %}
{{ form_input(config) }}
{% block button %}
	{% render "@button", config.component, config.component.config %}
{% endblock %}
```
In this implementation I have to explicitly specify the contents of the blocks each time using a macro(
Help me please!
Thanks!

**Comment by dkhuntrods** [comment]
I suspect you're running into the limitations of variables as inputs at evaluation time.
What happens if you set the name as a variable first? ie. 
```
{% set handle = "@"+config.component %}
{% render handle, config.component.config %}
```
If you can point me to an example repo with your setup, I'll see if I can help out; otherwise, since its mainly related to nunjucks, StackOverflow might be your best bet.

**Comment by 7iomka** [comment]
Well, I took the time and created a repository for testing problems:
https://github.com/7iomka/fractalTest
You offered variant does not solve the problem.
Error still remains:
`Unhandled rejection SyntaxError: Unexpected token u in JSON at position 0`
I would be grateful for any help in this direction.

I also have a question about how do I get the instance browsersync, which is integrated into the fractal, to disable the reload for some file types (eg .scss I need browserSync.stream without reloading the page). More problem [written here,](https://github.com/24ways/frontend/issues/10) but I think I will not get a reply from them as well as integration with browserSync - is part of the fractal core.

And another similar problem, I can not decide which is also related to reload the page. To build js I use webpack 2. If you change any files (css, js, html or another) from the folder that we set as a folder in the components fractal.js configuration (in my case `fractal.components.set( 'path', paths .src + '/ components'`) - there is just 2 things:
1 - fractal makes rebuilding components and reload the browser
2 - webpack watching all files .js including those that are in the components folder and also makes rebuilding when one of them.

It turns a sad situation when I have to change one file .scss styles and instead of that I got a second quick update in the browser I have to wait at least 2 seconds, because:
1 - changing styles of fractal file included browserSync (sync: true), first reload your browser, and secondly - do appear to rebuild the component (.js file will be affected - _may be_)
2 - as the js file affected, webpack makes rebuilding which in turn further reload the browser 1 more time.

I really need your help to figure out how to optimize the assembly process. If necessary, I will open a new issue if that is need.
Thanks!!!

**Comment by dkhuntrods** [comment]
Thanks for making the repo @7iomka .
I've had a quick look; there was one small confounding issue there, `config.component.config` doesn't actually reference anything defined in your config, however `config.config` does.

Aside from that, there does seem to be an issue related to paths in the Nunjucks Adapter.
If you add
```
{% set handle = "@"+config.component %}
{% render handle, config.config, true %}
```
to the actual component file (`test.html`) then it does seem to work.
From the context of the macro however, it fails.

I'll investigate further.

As to the rest, how is it a different issue to #203 ? I apologise if I've misunderstood but it looks like the same underlying issue to me.

**Comment by dkhuntrods** [comment]
@7iomka Unfortunately, this does look like an issue around asynchronous extensions (which `render` is) and macros within Nunjucks (see **Important Note** under **macro**): https://mozilla.github.io/nunjucks/templating.html#macro. 

So, unfortunately, within Nunjucks, it's not possible to use `render` inside a macro.

**Comment by dkhuntrods** [comment]
Closing this as it's a limitation of Nunjucks macros. 

If your webpack/browsersync issues aren't related to #203, do please open a new issue.
