### ISSUE TITLE
link/import components form diffrent directory

### ISSUE THREAD

**Issue by tlenex** [frctl/fractal#207]
I don't know if it's possible, but this might be an interesting feature for fractal.

Let's say I have fractal (lets call it `root fractal`) with installed npm dependencies like jquery etc...
One of those dependencies is my private npm package in `node_modules` dir, in that package there is my second fractal (aka `partial fractal`) with partial components.

Now I'd love to easily configure `root fractal` to use components from `partial fractal`. 
Don't get me wrong, I don't want to copy files from `partial fractal`, just use them in my `root fractal`.

You see the picture? I want to spread my fractal components on many repositories to be reusable and versioned.

I tried to use symlinks, but there are plenty of problems with git and symlinks on windows platform. And I can't move whole team to mac or linux :(

**Comment by dkhuntrods** [comment]
Thanks @tlenex , this is actually part of our roadmap (see [Moving Fractal forwards](https://github.com/frctl/fractal/issues/197) under 'Proposed improvements -> Supporting multiple component source directories.')
Part of supporting multiple component directories will be to allow inclusion from another package.

**Comment by tlenex** [comment]
Oh, I missed that one, thanks!
