### ISSUE TITLE
Changes needed to support React components properly

### ISSUE THREAD

**Issue by allmarkedup** [frctl/fractal#21]
* [x] support non-component preview layouts. Reference by path?
* [x] support for `require`ing and converting JSX files (https://babeljs.io/docs/usage/require/)
* [x] defer rendering of preview layout to adapter, if renderLayout method is defined 
* [x] prevent .config.js files from being parsed as components
* [ ] Figure out how to support FE integration
* [ ] ability to customise UI labels to match the terms that React users would typically use 
* [ ] smarter reloading/invalidating of view cache

**Comment by nchase** [comment]
I'm just starting to dig in here, I see that the project is on 1.0.8 now.

Is this "1.x" milestone still valid?

**Comment by johannestroeger** [comment]
got some status on this topic?

**Comment by aguilera51284** [comment]
+1

**Comment by johannestroeger** [comment]
so actually i've written my own adapter for react based on: [tnottu/fractal-twig-adapter](/tnottu/fractal-twig-adapter) - it's far from perfect but it was not a big challenge to get started with.

**Comment by guzart** [comment]
**For future references**: I built my own adapter as well using babel, you can find the source code here https://github.com/guzart/fain/blob/v0.5.0/packages/fain-src/lib/frctl-react-adapter/index.js

PS: Thank you for open sourcing fractal.

**Comment by custa1200** [comment]
Be cool to see this as a combined project/adapter as a standalone as an extra to Fractal :)

**Comment by sawyerh** [comment]
For those who stumble on this from a Google search like me: There's also an experimental React adapter by Fractal here: https://github.com/frctl/react-adapter
