### ISSUE TITLE
Help with setup filters for assets (paths)

### ISSUE THREAD

**Issue by 7iomka** [frctl/fractal#210]
Hello!
I spent about 4 days to explore issues (open and closed) and examine the source code, but only today received configure gulp-task so that it rendered me the desired components in the desired folder. I use the classic file preparation scheme for the backend developer:
Folder **templateName**, in which the root - all pages (_page1-template.html, page2-template.html ..._) and **assets** folder with images, stylesheets and scripts.
templateName folder can be installed on any CMS, because the reference should not be absolute though, would be for the pictures.

I want to have me in the compiled templates all references look like this:
1 - links to pictures were relative _ ** _ **: ** assets/images/someimg.png **, and that they also worked in the development mode. Now if you use your recommendations I can write this:
`{{assets/images/someimg.png | path}} `and this is normal but is rendered in error development mode, as the picture will not be found on the path` /components/preview/assets/images/someimg.png`

2 - links to internal pages of the site (components) are also relative.
Now I have, for example, in a navigation component, links to internal pages (components), based on your recommendations are as follows:
 `<a class="someClass" href="{{ page.url+'-template' | path }}"> {{page.title}} </a>`
and the context is listed link url: `/components/preview/about`

The reference design time work and I can quickly jump to different pages.
But after rendering as absolute references I can not do without the mini-server.
And I need to figure out how do I make the filter so that:
- Links in development mode were kind of `href="/components/preview/some-template"`
- After the build - `href="some-template"` (according to my structure where all the default page template in the root folder.
I, and I think not only me is critical to have access to the navigation between pages after the build.
I spent a lot of time on code analysis, due to the fact that not much documentation, so I sincerely hope for your help in this matter.
It is desirable as soon as possible, I was looking for a new modular design of sites with a lot of inner pages. Fractal impressed me very much, but as Node.js, I do not know, I lit a deadline and I can not still pass about 16 web pages in normal form with normal links the backend-developer (
Thanks!

**Comment by dkhuntrods** [comment]
Hi @7iomka 

I'm very sorry but I can't quite follow what the issue is here, aside from perhaps urls not rendering as you expect?

Could you please try to describe the issue in the below format? Also, I'm sure you're aware but we can only provide help it its directly related to Fractal - I can't yet tell if this is the case or not.

### Input Code
If you're describing a bug, please let us know which sample code reproduces your problem, eg:

```html
<a class="someClass" href="{{ page.url+'-template' | path }}"> {{page.title}} </a>
```

### Expected Behavior
If you're describing a bug, tell us what should happen
If you're suggesting a change/improvement, tell us how it should work

### Current Behavior
If describing a bug, tell us what happens instead of the expected behavior
If suggesting a change/improvement, explain the difference from current behavior

### Possible Solution
Not obligatory, but suggest a fix/reason for the bug,
or ideas how to implement the addition or change

### Context
How has this issue affected you? What are you trying to accomplish?
Providing context helps us come up with a solution that is most useful in the real world

### Your Environment
Include as many relevant details about the environment you experienced the bug in

**Comment by 7iomka** [comment]
### Input Code (link to images or another ASSETS)

```
 {{assets/images/someimg.png | path}}
```

### Expected Behavior

1. development(components preview with mandelbrot) mode:
 ```
 /components/preview/assets/images/someimg.png
 ```
2. build(after run fractal.web.builder().build()...) mode:
 ```
 assets/images/someimg.png
 ```
### Current Behavior
1. development(components preview with mandelbrot) mode:
 ```
 assets/images/someimg.png  => file not found in the dir: /components/preview/assets/images/
 ```
2. build(after run fractal.web.builder().build()...) mode:
 ```
 assets/images/someimg.png  => file successfuly found because I build all .html in the same folder as the assets folder
 ```
### Possible Solution
It may be possible somehow create an extension of the standard filter path for images, and depending on any environmental variable apply different actions.
The current challenge is to write a filter that will automatically take files of any assets of some global variable in fractal configuration. For example:
```
fractal.components.set('assetsPath', __dirname + '/src/assets');
```
In this case, fractal will have to understand where our assets are physically located and connect them when the server is running - relatively (or absolutely but only for development!)

### Environment 
(my fractal components config (as a part of customized bundle (24-ways))
```
// paths
const paths = {
  build:  __dirname + '/www',
  src:    __dirname + '/src',
  static: __dirname + '/tmp'
};

//Components config
fractal.components.engine(nunjucks);
fractal.components.set('default.preview', '@preview');
fractal.components.set('default.status', 'prototype');
fractal.components.set('ext', '.html');
fractal.components.set('path', paths.src + '/components');

fractal.web.set('static.path', paths.static);
fractal.web.set('builder.dest', paths.build);
fractal.web.set('builder.urls.ext', '.html');


```

### Structure of project for understand
```
/
├─ src/
│  ├─ assets/        # Static…
│  │  ├─ icons/      # Favicon and home screen icons
│  │  ├─ images/     # Raster images (used in component examples)
│  │  ├─ scripts/    # JavaScript files
│  │  ├─ styles/     # CSS files
│  │  └─ vectors/    # SVG images, icons and logos
|  |
│  ├─ components/    # Components…
│  │  ├─ _macros/    # Macros
│  │  ├─ common/     # Common components
│  │  └─ temlates/   # Pages which include common components          
|  |
│  └─ docs/          # Project documentation
│
├─ tmp/              # Files required for dynamic builds (ignored by Git)
├─ www/              # Public build (ignored by Git)
│  ├─ assets/        # Static optimized assets
│   home.html        # Separately rendered pages (fractal components)
│   about.html     
│   contacts.html     
├─ .editorconfig     # Code style definitions
├─ .gitignore        # List of files and folders not tracked by Git
├─ .stylelintrc      # Linting preferences for CSS
├─ LICENSE           # License information for this project
├─ fractal.js        # Configuration for Fractal
├─ gulpfile.js       # Configuration for Gulp tasks
├─ webpack.config.js # Configuration for Webpack js build
├─ package.json      # Project manifest
└─ README.md         # This file
```

**Comment by dkhuntrods** [comment]
Hi @7iomka 

The `path` helper isn't quite being used correctly. [As per the docs](http://fractal.build/guide/core-concepts/views#-path-):


> Takes a root-relative path and re-writes it if required to make it work in static HTML exports.
> ```
> {{path '/css/my-stylesheet.css'}}
> ``` 
> **The path argument should begin with a slash** and be relative to the web root. During a static HTML export this path will then be re-written to be relative to the current page.
> 

That ought to do the trick.

**Comment by 7iomka** [comment]
### Finally, I made sure what he wanted! Fantastic!
To get everything working, you need to follow the following rules (nunjacks syntax):

1. if it's any assets:
```
 {{ '/assets/images/someimg.png' | path }}  
---> The path argument should begin with a slash
```
2. if it's any link to an internal page (fractal component)
```
 {{ 'about' | path }}  
---> NOT need begin with a slash! 

Because, if I start the line with a slash, the dynamic URL-part "components/preview/" 
will not join in the line of finally url! 
But if i will pass clean string with name of fractal component that will be transformed in:

dev: '/components/preview/about'
build: 'about.html' (in my case, because fractal.web.set('builder.urls.ext', '.html');
```
**It is this difference in the logic of the construction of links created this problem, thank you very much for helping with the solution of this complicated situation!
Maybe this will help those who use fractal to create sites, not just individual components!**
