### ISSUE TITLE
Unable to define context of sub-components using parent component's config

### ISSUE THREAD

**Issue by siiron** [frctl/fractal#212]
@frctl/fractal version: **1.1.3** + @frctl/nunjucks version: **1.0.3**

I love Fractal so far, but I'm struggling a bit with including sub-components via method B (define context data in the parent componet's config), documented here http://fractal.build/guide/components/sub-components#b-define-all-context-data-in-the-parent-component-s-config.

I'm using Nunjucks as my template engine, and .js files for component configs. Recreating the doc-example, I'm not able to pass in a different text to my `button` using the parent component's config.

```html
{# button.njk #}
<button type="button" name="submit">{{ text }}</button>
```

```js
// button.config.js
module.exports = {
    title: 'Button',
    context: {
        text: 'A Button'
    }
};
```

```html
{# search-box.njk #}
<div class="searchbox">
    <label for="search">{{ label }}</label>
    <input type="search" name="keywords" id="search">
    {% render '@button' %}
</div>
```

```js
// search-box.config.js
module.exports = {
    title: 'Search Box',
    context: {
        label: 'Search here',
        button: {
            text: 'Go!'
        }
    }
};
```

According to the documentation, I could expect the following result:
```html
<!-- button.html -->
<button type="button" name="submit">A Button</button>
```

```html
<!-- search-box.html -->
<div class="searchbox">
    <label for="search">Search here</label>
    <input type="search" name="keywords" id="search">
    <button type="button" name="submit">Go!</button>
</div>
```

But instead I get the text "A Button" (defined in `button.config.js`) in both cases:
```html
<button type="button" name="submit">A Button</button>
```

```html
<!-- search-box.html -->
<div class="searchbox">
    <label for="search">Search here</label>
    <input type="search" name="keywords" id="search">
    <button type="button" name="submit">A Button</button>
</div>
```

**Comment by 7iomka** [comment]
Just pass the variable you defined in the configuration of the parent component 
```
{% render '@button', button %}
```

**Comment by siiron** [comment]
@7iomka Thx! That helped a lot!

**Comment by lucasctd** [comment]
It seems to not be working anymore. How can I pass a parameter to a sub-component? I have several instances of the same component and I want to pass diferent values for each of them. How can I do it?

**Comment by LeBenLeBen** [comment]
@lucasctd If you use Nunjucks, see [7iomka comment](https://github.com/frctl/fractal/issues/212#issuecomment-282575682), if you use Handlebars:

```hbs
{{render '@example' partialData}}
```

Or to merge with component default context:

```hbs
{{render '@example' partialData merge=true}}
```

See Using Handlebars section on https://fractal.build/guide/core-concepts/views

**Comment by lucasctd** [comment]
Thank you so much. You helped a lot. I actually have started learning Fractal and its stuff 3 days ago and need to get a stuff done today, so I am still figuring out how things work with fractal. Thanks again.

**Comment by lucasctd** [comment]
Also, if you don't mind, I would like to ask you something. I am compiling my component's sass file and importing it inside my component, so it will be styled in fractal. The "problem" is if I am import this component multiple times inside another, I will have a lot of css includes in page (see the picture). Am I doing it in the right way?

![image](https://user-images.githubusercontent.com/5876679/44588592-8ac18b00-a78c-11e8-9e21-71a537472239.png)

**Comment by mikkelrom** [comment]
Hi @lucasctd. It's actually better to include your CSS in the head of the preview layout: https://fractal.build/guide/components/preview-layouts

Hope this helps! :slightly_smiling_face:
