### ISSUE TITLE
Using `contextData` handlebars helper

### ISSUE THREAD

**Issue by maban** [frctl/fractal#213]
I'm trying to override the text in a button in one of my view templates. I'd like to do this using `contextData`, [following the documentation](http://fractal.build/guide/core-concepts/views#-contextdata-):

```
<!--
  The same as above, but passing in some data to override
   some items in the @button-2 data. 'someData' is an
   object, i.e. {text: 'foo'}
-->
{{> '@button-1' (contextData '@button-2' someData) }}
```

When I look at the [example](http://bits.24ways.org/components/detail/field), @paulrobertlloyd has done it like this:

```
{% render "@button", { label: "Search", submit: true } %}
```

How do I write the same thing in Handlebars? I've been trying for quite a while but keep getting syntax errors. Here's what I've tried (including separating with commas, adding double quotes…) but I'm missing _something_.

```
{{> '@button-1' (contextData '@button-2' {text: 'foo'} }}
```

What am I doing wrong here?

Really enjoying using Fractal properly, by the way! :)

**Comment by allmarkedup** [comment]
Hey @maban - unfortunately Handlebars doesn't let you define data objects in-line like this :-( It's one of my main frustrations with Handlebars as a template language for component libraries.

To get something similar to work you'd can define a property in your context with the data you want to merge in, like this: 

```js
{
  context: {
    customButton: {
      text: 'foo'
    }
  }
}
```
 
And then use it like:

```handlebars
{{> '@button-1' (contextData '@button-2' customButton }}
```

Obviously you lose the convenience of being able to define that customButton data on-the-fly in the template but this is unfortunately a Handlebars limitation and so not something that Fractal can do much about!

**Comment by maban** [comment]
Awww maaaaan! Do you know of a helper that will let me do this?

**Comment by allmarkedup** [comment]
No I'm afraid not - it's a language-level limitation so not something that a helper can work around (especially in a subexpression like this). Sorry :-(

**Comment by maban** [comment]
@joshjemerson had a look and helped me write this:

```
{{> @ button label="Search" type="Submit" }}
```

It works! I don't know how but it does 👍
