### ISSUE TITLE
No ability to pass options to default Handlebars compile function

### ISSUE THREAD

**Issue by keenanlawson** [frctl/fractal#215]
First I would like to thank you for creating this fantastic generator.  It serves everything our organization could possibly want and more. The listed future features are even more exciting.
With the addition in Handlebars 4.0.6 to set a compile option of "explicitPartialContext" to change the behavior of sub-components automatically inheriting same named context variables (This post explains the issue very well: [https://github.com/wycats/handlebars.js/issues/1032#issuecomment-130780498](url)), it would be great to be able to send custom compiler configuration options as noted at [http://handlebarsjs.com/reference.html](url).  Currently it appears that in https://github.com/frctl/handlebars/blob/master/src/adapter.js#L33, no options are able to be sent to the compiler.  I have studied the documentation and there seems to be a potential to use the components API resolve() function but I am unsure as to how it could be implemented to enable this feature or other compiler configuration options if possible.  Thoughts?

**Comment by dkhuntrods** [comment]
Hi @keenanlawson, apologies for the delay. We'll probably look at adding this functionality to our V2 Handlebars adapter, but as we're focussed on getting V2 built, it's not terribly high on the priority list to add new features to V1 implementations.
We're definitely open to PRs though, so if you do get time to take a look, please do open one!
