### ISSUE TITLE
Ajax requests not working after fractal build

### ISSUE THREAD

**Issue by Arnano** [frctl/fractal#216]
When using fractal browsersync, all the Mandlebrot scripts are working correctly.
But when using fractal build, the scripts doesn't seem to work properly and fail silently. In particular the ajax requests are not executed anymore. 

Here is the configuration of the theme used: 

``` 
const theme = require('@frctl/mandelbrot')({
      skin: 'teal',
      lang: 'en',
      nav: ['components', 'docs'],
      styles: ['default', this.options.theme.stylePath],
      scripts: ['default', this.options.theme.scriptsPath]
    });

    // Specify a custom views directory to override Mandelbrot theme template.
    theme.addLoadPath(this.options.theme.loadPath);

    /*
     * Specify the static assets directory that contains the custom stylesheet.
     */
    theme.addStatic(this.options.theme.static.folder, this.options.theme.static.path);
```

And here is the configuration for the start and build tasks respectively. The start tasks loads the scripts correctly whereas the build task doesn't work:

```
const gulp = require('gulp');
const fractal = require('@frctl/fractal').create();
const Fractal = require('../fractal');

const fractalServer = new Fractal(fractal);

gulp.task('fractal:start', function(){
  const server = fractalServer.fractal.web.server({
    sync: true,
    notify: true
  });
  server.on('error', err => console.error(err.message));
  return server.start().then(() => {
        console.log(`Fractal server is now running at ${server.url}`);
  });
});

gulp.task('fractal:build', function(){
  const builder = fractalServer.fractal.web.builder();
  builder.on('progress', (completed, total) => console.log(`Exported ${completed} of ${total} items`, 'info'));
  builder.on('error', err => console.error(err.message));
  return builder.build().then(() => {
        console.log('Fractal build completed!');
  });
});
```

Thanks for your help.

**Comment by dkhuntrods** [comment]
Hi @Arnano. How are you serving the built files?
And I understand that you're not getting any error messages, but what are you seeing that you're not expecting?

**Comment by Arnano** [comment]
Thanks for your reply.

I am not sure I understand your question correctly. The built files are served through a gulp task and basically, the things that change are just the fractal:start to fractal:build.
 
No, I am not getting any error messages. I can see however, that the pjax calls are not working. Every time I click on a new component in the navigation, a full page refresh is executed, instead of just reloading the main-frame content.

**Comment by dkhuntrods** [comment]
Ok, I think perhaps you might be misunderstanding what the builder does? 
It just creates and serves static HTML: see http://fractal.build/guide/web/builder. So, this is what would be expected.

**Comment by Arnano** [comment]
So are you suggesting that it is necessary to launch a fractal:start to make the fractal:build serves everything as seen inside a local development environment ? In particular to have the ajax calls working as expected ?

**Comment by dkhuntrods** [comment]
The _build_ task is intended to be run to produce a 'final' version of your library, to go on a server to be shared with others, and the _start_ task is intended to be run to produce files for your local development environment. 

Fractal:start won't load the _build_ files. Once they are built, if you want Ajax to run on them, they need to be served from some kind of server (php simple server, etc), rather than simply viewing the html (as file://) in your browser. This is standard browser behaviour. 

That's why I asked how you're serving them; if you're not using a server then this is expected behaviour but if you are, then there's an issue. Can you confirm how you're viewing them?

**Comment by dkhuntrods** [comment]
Hi @Arnano, have you been able to resolve this?

**Comment by dkhuntrods** [comment]
@Arnano I'm going to close as I've not heard back, and it doesn't look like a bug, but if you've got any more questions do feel free to reopen.
