### ISSUE TITLE
Getting started guide wont work with cmder

### ISSUE THREAD

**Issue by inspiraller** [frctl/fractal#219]
**OS:** Windows 7
**IDE:** Sublime
**CMD:** cmder latest
**Node:** 6.9.4

When following the getting started guide, whether it's the tldr or from scratch method, in both cases, upon running:
$ fractal start --sync
The server doesn't start. Instead, my IDE just opens - sublime.

**Comment by freakyleaf** [comment]
Just ran into the same issue with Windows 10, Sublime, Cmder latest, Node 4.4.7...

The following fix worked for me...

https://github.com/frctl/fractal/issues/118#issuecomment-255254117

**Comment by dkhuntrods** [comment]
Thanks @freakyleaf - did this help @inspiraller?

**Comment by inspiraller** [comment]
Yes @freakyleaf  and @dkhuntrods  Nice job :)
