### ISSUE TITLE
When the side navigation scrolls, its position jumps around after clicking an option

### ISSUE THREAD

**Issue by stowball** [frctl/fractal#220]
I haven't experienced it yet in my new project as I don't have many components, but [in your own pattern library](http://fractal.clearleft.com), clicking components, pages, groups, whatever that were initially out of the viewport make the nav jump around, losing your position.

Tested on Chrome (stable) on macOS Sierra

<img src="https://cloud.githubusercontent.com/assets/853552/23820666/1a63a94a-0672-11e7-87ad-f9e67ebd285b.gif" width="400" alt="Fractal nav position jumps" />

**Comment by dkhuntrods** [comment]
Thanks @stowball, that's not ideal! We'll look into it.

**Comment by risker** [comment]
I'll close this as frctl/mandelbrot#85 has been now merged. hopefully it will get released soon.
