### ISSUE TITLE
Fractal CLI tools don't work from project root on Windows

### ISSUE THREAD

**Issue by nategreen** [frctl/fractal#222]
When I run `fractal start --sync` or `fractal build` from my project's root directory, I get the help output of some other tool:

![image](https://cloud.githubusercontent.com/assets/6674698/24155898/67f1974c-0e2b-11e7-8294-8f9d5ea9119e.png)

But, when I run it from a subdirectory, it works fine. Any ideas? Not completely sure this is a problem with fractal, but it seemed weird that it'd be happening *only in this directory*.

**Comment by allmarkedup** [comment]
Hey @nategreen - have a look at this issue and comment, I think this _should_ fix the issue you are having: https://github.com/frctl/fractal/issues/118#issuecomment-255254117

I need to get this fix into the documentation as people keep running into it!

**Comment by nategreen** [comment]
@allmarkedup Wow, that worked! Thanks for that. Thought I'd searched all the issues, but I guess I missed that one.
