### ISSUE TITLE
Linking to pages within context data?

### ISSUE THREAD

**Issue by citation-nm** [frctl/fractal#223]
Hi all,

I'd like to know whether it is possible to link to a page from context data, i.e. if in a component's context data, I want to be able to link to a page using `{{ path '/components/preview/page-name' }}` so that when it is compiled (and built) it will resolve correctly.

```
file.hbs
<a href="{{ href }}">{{ link }}</a>
```

```
file.config.js
{
  ...
  href: {{ path '/components/preview/page-tasks' }},
  link: "Tasks"
  ...
}
```

I've seen that you can add the above example link within (say a hbs file) and it will compile and build correctly, but I'd like to include a Handlebar expression that will take the context data and use it.

I hope this makes sense.

Many thanks,

Neil

**Comment by dkhuntrods** [comment]
Hi @citation-nm, the `path` helper only works within a handlebars template. Is there a reason you can't use it there? ie
```
file.hbs
<a href="{{ path href }}">{{ link }}</a>
```
```
file.config.js
{
  ...
  href: '/components/preview/page-tasks',
  link: 'Tasks'
  ...
}
```

**Comment by citation-nm** [comment]
Hi @dkhuntrods - I'll check and get back to you, thanks for the reply.

**Comment by citation-nm** [comment]
Hi @dkhuntrods - just made the change, and it works. I'll close this, thanks again.
