### ISSUE TITLE
Toggles in the navigation are not keyboard accessible

### ISSUE THREAD

**Issue by yatil** [frctl/fractal#224]
When trying to navigate the tree on the left with the keyboard, I can’t access the toggles as they are `h4` elements and don’t receive focus.

Use a button element instead and it should work. 

Consider adding aria-expanded="false"/="true" depending on the state to the buttons.

**Comment by paulrobertlloyd** [comment]
Thanks for reporting this @yatil! This is an issue with the UI specifically, so have posted this issue on that repo. Will try and submit a fix PR soon. Let me know if you discover any similar issues. @allmarkedup @dkhuntrods you can close this issue.

**Comment by yatil** [comment]
Thanks for channel that to the right repository, @paulrobertlloyd!

**Comment by dkhuntrods** [comment]
Thanks all! Will do.
