### ISSUE TITLE
How to inject files content in a preview file with gulp and fractal?

### ISSUE THREAD

**Issue by 7iomka** [frctl/fractal#225]
Hello.
I build the lending (one-page-site) on the fractal.
I had a need to put in the head tag the contents of the header.css file (this file is compiled into the dest folder from header.scss)
For this, I want to use the plugin and its configuration: https://github.com/klei/gulp-inject#injecting-files-contents
But the fact is that the fractal in the development mode does not compile the html file, but keeps it in memory. That to me in that case to specify in` .pipe(gulp.dest ('./dest'));` ?
PS: I use [24ways](https://github.com/24ways/frontend) customized by me assembly, and as file for recognizing plugin inject will be the file _preview.html (from the settings of `fractal.components.set ('default.preview', '@preview');`)
Thanks!

**Comment by tlenex** [comment]
I believe your steps for development should be:
1. Inject build files to your's fractal `_preview` files
2. Run fractal dev server
3. On watch, if you add new file to inject, completely rerun the task

For production build try this steps:
1. Build fractal
2. Inject into HTML's components

Try to use fractal's `static.path` to drop your files there.

**Comment by dkhuntrods** [comment]
Thanks @tlenex, that sounds like a reasonable approach. 
@7iomka I'm assuming that was helpful, I'll close this if you have no objections?
