### ISSUE TITLE
Issue updating local copy of Fractal

### ISSUE THREAD

**Issue by StephenMeehan2016** [frctl/fractal#227]
Hi

I'm having a problem updating a local version of Fractal from 1.0.11 to match the Global version 1.1.3

Here's a quick screencast showing what I'm doing.
http://quick.as/rk68s3jex

The steps I follow in the screencast work in other Fractal projects. Are there any known issues - or anything you can think of that might be causing this particular install of Fractal to not update?

**Comment by dkhuntrods** [comment]
Hi @StephenMeehan2016, did you update your global fractal install as well? (`npm install @frctl/fractal -g`)

**Comment by dkhuntrods** [comment]
Hi @StephenMeehan2016 closing this now, but let me know if you're still having trouble.
