### ISSUE TITLE
Compound component resources aren't getting picked up

### ISSUE THREAD

**Issue by jakubfiala** [frctl/fractal#228]
I've attempted to set up Fractal with a Drupal site which uses PHP templates. I've written a custom rendering engine for them, and it seems to work well. This is my `components` folder structure, with a single compound component:

```
├── components
│   └── button
│       ├── README.md
│       ├── button.config.js
│       ├── button.css
│       └── button.tpl.php
```

When I run `fractal start`, the template is rendered with the context from the config, but:

1. the README isn't being parsed into the Notes panel
2. the CSS isn't shown in a Resources panel, in fact there isn't a resources panel.

Any ideas why this might be happening? I'm on v1.1.3

**Comment by dkhuntrods** [comment]
Hi @jakubfiala, can you post your `fractal.js` file? 
Off the bat, I'm not sure why your README isn't being included.
What are you using to compile your css?

**Comment by jakubfiala** [comment]
@dkhuntrods [here's a gist](https://gist.github.com/jakubfiala/404b568797e68a430b2557ecbd215060) containing my fractal config.

Regarding the CSS, I'm not using my actual CSS for now, just added a test file with some dummy styles into the component folder. It should still pop up, right?

**Comment by jakubfiala** [comment]
update: this doesn't seem to occur when using the default Handlebars engine. What does the engine do about the associated resources?

**Comment by jakubfiala** [comment]
Found the problem 🎉

The whole issue stems from the fact that Drupal 7 templates need to have the `.tpl.php` extension. This is confusing to Fractal, because it's not consistent in how it strips extensions from filenames and directory names.

[In `src/api/components/source.js`](https://github.com/frctl/fractal/blob/1537b1d235fbcf831892fa791f3b682e9f3643d6/src/api/components/source.js#L433) the component parser tries to determine whether the current directory is a collection or a compound component. It does so by looking at the files in the dir, finding any *views*, and matching the view names against the dir name.

In my case, we want it to come to the `button` directory, find the `button.tpl.php` view, and match it s name against `button`. However, if the directory is named `button` or `button.tpl`, Fractal strips the end bit from it, always ending up with `button`. For views, however, it only strips the `.php`, so the view name is `button.tpl`. The view name doesn't match the dir name, so we treat the view as a self-contained component, rather than a compound component. Therefore we don't load its resources, as there may be other independent components in the directory.

At the moment, I can get around this by naming the directory `button.tpl.php`, which is a bit silly, but it works.

Obviously this is a crazy edge case, so I won't expect the behaviour to change, but thought describing it might be useful to any other poor souls having to deal with Drupal 7 templates.

**Comment by dkhuntrods** [comment]
@jakubfiala apologies for not getting back sooner - thanks for working through this and writing up what you found.
