### ISSUE TITLE
Path helper in notes doesn't output the right path

### ISSUE THREAD

**Issue by yhuard** [frctl/fractal#229]
In a documentation page, `{{ path '/path/to/static/file.txt' }}` outputs `/path/to/static/file.txt` (expected behaviour). In component's notes on the other hand, `{{ path '/path/to/static/file.txt' }}` outputs `path/to/static/file.txt` (no first slash). 

Is this the normal behaviour or a bug? 

Thanks for the great work

**Comment by dkhuntrods** [comment]
@yhuard The urls are rewritten during export, so this can be expected to occur. Are you seeing errors when viewing the resulting files?

**Comment by dkhuntrods** [comment]
Hi @yhuard, is this still an issue for you, or can I close this down?

**Comment by yhuard** [comment]
Hi @dkhuntrods, you can actually close it, it's not relevant anymore in my case. Thanks for your time!

**Comment by dkhuntrods** [comment]
@yhuard Great, thanks for letting me know! :)
