### ISSUE TITLE
Using promises for context data prevents fractal web UI from starting, exits silently

### ISSUE THREAD

**Issue by mattschloss** [frctl/fractal#233]
I am trying to follow example in Fractal's guide to dynamically populate data with promises.
http://fractal.build/guide/core-concepts/context-data#dynamic-data

Using the request-promise module, I've tried several patterns to handle the responses. I've also tried using bluebird and request separately instead. If fractal is already started, I can modify the component's config file, and successfully get the response, I can get the promise to resolve, and populate the context data. But then `fractal start` doesn't complete "parsing components directory", and exits silently.

Doing console.log from the .then() handler will echo the response in the terminal, twice, as if each context file gets processed twice on startup? And after the logged response, fractal web UI won't start. If I remove the request and promise code from the component's config file, then fractal will start.

I tried this with a fresh fractal install version 1.1.4, and I've tried the latest versions of request-promise, request, and bluebird.

Example of a request-promise pattern I tried (after trying the pattern in the example linked above):
```'use strict';

const rp = require('request-promise'); // require the request-promise module

let makeRequest = function(options) {
	return rp(options)
		.then(function (res) {
			return(res);
		})
		.catch(function (err) {
			console.log(err);
		});
}

const api = {
	uri: 'https://jsonplaceholder.typicode.com/posts/1',
	json: true
};

module.exports = {
	context: {
		results: makeRequest(api)
	}
};
```

**Comment by dkhuntrods** [comment]
Hi @mattschloss. I've created a quick test case, and can't replicate your error. I've used your example file above as-is, aside from logging the result on .then(), as you mentioned you'd tried. 
I do see the double-logging you mentioned, but everything loads and displays ok.
Before you updated Fractal, did you remove the old `node_modules` folder? There was an issue with an newer version of a dependency that I've had to explicitly roll back, and I'm just wondering if it could be related to that.

**Comment by mattschloss** [comment]
Thanks for you help @dkhuntrods.

I'm using:
node 6.10.2
fractal 1.1.4
request-promise 4.2.0
request 2.81.0

I've gone into fractal's package.json, and tried several vorpal versions. 1.11.4, 1.11.2, 1.11.1, 1.10.10, and I get the same results. `fractal start` fails silently. 

Thanks for any help or suggestions.

**Comment by zauni** [comment]
Having the same issue, and even after hours of debugging, I can't find the problem... The server is failing silently like in @mattschloss case.

My versions:
- Node 8.4.0
- Fractal 1.1.7

This is my code of a config file, which is NOT working:

```javascript
context: {
    foo: new Promise((_resolve) => {
        if (!fractal.components.isLoaded) {
            fractal.components.on('loaded', () => {
                console.log('components have loaded', fractal.components.isLoaded);
                _resolve('components loaded');
            });
        } else {
            _resolve('components already loaded');
        }
    })
}
```
I want to render another component inside the config, because the components are nested, so that the normal {{render}} helper can't be used. So I have to wait until all the other components have finished loading, before I can use `fractal.components.render('@xyz', {})`.

The strange thing is, that if I put the _resolve function out of the eventhandler, it is working normally and the eventhandler is invoked 2 times:

```javascript
context: {
    foo: new Promise((_resolve) => {
        if (!fractal.components.isLoaded) {
            fractal.components.on('loaded', () => {
                console.log('components have loaded', fractal.components.isLoaded);
            });
            _resolve('components loaded');
        } else {
            _resolve('components already loaded');
        }
    })
}
```

Maybe you have an idea what I am doing wrong?
