### ISSUE TITLE
A promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by Igloczek** [frctl/fractal#235]
On every page refresh in a console I got those warnings about not returned promises from some Nunjucks related code. That's weird, b/c I'm using Handlebars.
```
(node:21289) Warning: a promise was created in a handler at eval at _compile (/Users/igloczek/Sites/snowdog-theme-components/node_modules/nunjucks/src/environment.js:565:24), <anonymous>:57:1 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/Users/igloczek/Sites/snowdog-theme-components/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:21289) Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
(node:21289) Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
(node:21289) Warning: a promise was created in a handler at Users/igloczek/Sites/snowdog-theme-components/node_modules/nunjucks/src/runtime.js:273:21 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/Users/igloczek/Sites/snowdog-theme-components/node_modules/bluebird/js/release/promise.js:195:13)
```

I'm using Fractal.js v1.1.4 with Handlebars as templating engine, through Gulp tasks.

**Comment by studiomohawk** [comment]
This is happening to me as well.
Does occur even at right after scaffolding(meaning no change to default fractal).

**Comment by colinrotherham** [comment]
Hi @Igloczek, @studiomohawk, are both of your builds using Babel?

I'm getting this too. It's because Babel uses Bluebird as its Promise library, but usefully it adds these warnings to avoid memory links inside V8 which would go unmentioned by native `Promise`.

If you're using ES6 you can turn off using:

```js
import bluebird from 'bluebird';

// Turn off  warnings
bluebird.config({
    warnings: false
});
```

The trace shows `nunjucks/src/environment.js:565:2`, so perhaps [file an issue with Nunjucks](https://github.com/mozilla/nunjucks/issues) instead?

But, for me I'm also seeing a similar Promise warning inside Fractal code:

```
(node:8000) Warning: a promise was created in a handler at /node_modules/@frctl/fractal/src/web/engine/filters/async.js:15:57 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/node_modules/bluebird/js/release/promise.js:196:13)
```

**Comment by Igloczek** [comment]
Nope, I'm not using Babel, b/c Node v6 supports everything I need.

**Comment by colinrotherham** [comment]
@Igloczek Fair enough, we're both using Bluebird though regardless!

**Comment by Igloczek** [comment]
Thanks, the workaround works like a charm!

But still, the question is what is wrong with Fractal core, b/c using Handlebars I shouldn't give a F about nunjucks promises 😞

**Comment by dkhuntrods** [comment]
Fractal uses nunjucks internally for rendering and Bluebird for Promises, which is why some might on occasion run into this issue. If so, [this](https://github.com/frctl/fractal/issues/235#issuecomment-301077470) should do the trick.

**Comment by skoldborg** [comment]
I'm having this same issue and the recommended workaround does nothing. Has anyone found a more solid solution to this? The error really clutters the terminal on each save. 

Using Frctl with Handlebars as view engine. Node version 10.15.1.

**Comment by LeBenLeBen** [comment]
@skoldborg Where did you put the bluebird config code? I've had this issue on a project and putting the following code:

```js
const bluebird = require('bluebird');
bluebird.config({
  warnings: false,
});
```

At the end of my `fractal.js` file fixed the issue.

**Comment by skoldborg** [comment]
@LeBenLeBen Life saver! That did it. Thanks!
