### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Ollie-w** [frctl/fractal#236]
how do you link up the components with a stylesheet?

**Comment by tlenex** [comment]
Best way is to use a preview component.
http://fractal.build/guide/components/preview-layouts

**Comment by kyleknighted** [comment]
I agree that this doesn't seem to be spelled out anywhere.

I just started tinkering and reading the documentation it appears that this should work

```
├── components
│   ├── paragraph
│   │   ├── paragraph.hbs
│   │   ├── paragraph.scss
```

The only thing I have is a simple Lorem Ipsum paragraph and the SCSS is just setting the `font-family` to sans-serif. But it still renders the paragraph as a serif font. Under the "Assets" pane, it shows that the SCSS is there and it shows the proper styles, but it doesn't actually render the paragraph properly.

How do you build `components` with their relevant styles associated to them?

**Comment by lillamiu** [comment]
I've solved it by having scss files in each component directory, and then I use gulp to compile all the individual component styles into a main.css, which I put in the static assets folder. 
this can then be referred to in my _preview.hbs. 

I also have a 'global styles' directory outside of the components directory, where I have a variables.scss , colors.scss, etc. Here I also have a main.scss, where I import all the components' styles as import statements. 

hope that helps! 

there's a section of the documentation that goes through setting up gulp, but let me know if you would like to have a boilerplate project or structure :)

**Comment by dkhuntrods** [comment]
Hi @Ollie-w, Fractal is agnostic as to how you build your files; it's up to you to create your asset pipeline. Once you've got css files being built, you can link them in the preview layouts, as @tlenex and @lillamiu have described. 
I'm closing this as it's not an issue directly, but if you have any more problems please do post again.

**Comment by macandcheese** [comment]
@lillamiu do you mind posting your solution? 

My intent is to have a small set of global variable files (color, type, etc...) that can be referenced w/in each components's unique .scss file. This more closely matches a production paradigm and it would be great to be able to edit and maintain the .scss file at a per-component level while still having access to variables like $color-primary, as an example. Thanks!

**Comment by macandcheese** [comment]
I managed to solve for this by installing: gulp, gulp-rename, gulp-sass, and gulp-sass-glob, and then in my Gulpfile.js:

`var gulp = require('gulp');
var rename = require('gulp-rename');
var sass = require('gulp-sass');
var sassGlob = require('gulp-sass-glob');

gulp.task('styles', function() {
	gulp.src(['basics/import.scss'])
	.pipe(sassGlob())
	.pipe(sass().on('error', sass.logError))
	.pipe(rename('site.css'))
	.pipe(gulp.dest('./public/stylesheets'))
});

gulp.task('watch', function(){
	// don't watch our import file for changes, watch the underlying partials for changes
	gulp.watch(['components/**/*.scss', 'basics/*.scss'] , ['styles']); 
})`

Obviously you can place your files wherever you'd like. The purpose behind having a "basics" import is that you'll want certain mixins and variables imported FIRST, which by default node sass can't handle. So, then in an import.scss located at basics/import.scss, add this to the bottom. This is made possible by the gulp-sass-glob package.

'@import "../components/**/*.scss";'


This should allow you to build your css in component-level partials while still referencing one single set of default global variables.

**Comment by macandcheese** [comment]
Hi @Ollie-w - I was looking for something similar - to be able to have a set of global variables that I can reference in component-level sass, have it auto-compile and update the preview.

I took a stab at creating a Fractal Sass Seed - give it a look here: https://github.com/macandcheese/fractal-sass-seed

Pass along any feedback you might have, hope others can find it useful!
