### ISSUE TITLE
Ish

### ISSUE THREAD

**Issue by custa1200** [frctl/fractal#240]
Just reading Brad Frost's excellent book and noticed he talked about **Ish** which he wrote for Pattern Lab but seems to have it as a standalone that maybe Fractal could incorporate as part of 2.0?

http://bradfrost.com/demo/ish/
https://github.com/bradfrost/ish.

**Comment by dkhuntrods** [comment]
@custa1200 The intention for v2 is to allow flexibility in how you output your build - it's basically a static site generator, so you'll be able to use whatever tools you fancy :)
