### ISSUE TITLE
Incorrect context handling in gulp build

### ISSUE THREAD

**Issue by plumpNation** [frctl/fractal#241]
I have 2 strange issues.

1. When running `gulp watch` and changing fractal files to start a build, the config file that contains the context data is not updated. When I stop the `watch` and start it again, or run the task directly, the change is added to the dist. This does not happen with the main component handlebars file shown rendered in the HTML tab and unrendered in the View tab.

2. If a property in the `context` data is set to the number 0, it is shown as `null` in the Context tab.

I am following the guide found [here](http://fractal.build/guide/integration/build-tools#gulp).

**Comment by plumpNation** [comment]
Another symptom step by step:
1. Start the `gulp watch`.
2. Update the component context data.
3. Open new terminal and run the fractal gulp task.
4. Open the IDE and save the context data file again.
5. The gulp watch will fire and the previous context data is now shown in fractal.

**Comment by FrancisVega** [comment]
Same here with CSS (postcss)

**Comment by anderskleve** [comment]
Same issue for me. Did you happen to find a workaround?

**Comment by plumpNation** [comment]
No, we didn't work around. We started to use the `fractal start --sync` which is great. The gulp watch runs in a different terminal.

When a feature is complete, we do a full build and publish.

**Comment by plumpNation** [comment]
I'm going to close this now, many thanks for fractal.
