### ISSUE TITLE
Variants and SubComponents

### ISSUE THREAD

**Issue by kingmauri** [frctl/fractal#242]
Hello! 

Trying to understand the variants feature but after severals hours of trying and searching I just don't get the solution (maybe because I'm absolutly a handlebar newbie).

I have the following button.hbs:
```html
<div>
    Class: {{ modifier }}
</div>
<a href="#" class="btn btn--{{ modifier }}">{{ text }}</a>
````

// button.config.json:
```json
{
    "title": "Button Variants",
    "status": "ready",
    "default": "alpha",

    "variants": [
        {
            "name": "alpha",
            "context": {
                "modifier": "alpha"
                
            }
        },
        {
            "name": "beta",
            "context": {
                "modifier": "beta"
                
            }
        },
        {
            "name": "gamma",
            "context": {
                "modifier": "gamma"
                
            }
        }
    ],
    "context": {
        "text": "Standard Text"
    }
}
````

// comp1.hbs
```html
<div>
    Without helper:
    {{> @button--beta text="Other Text"}}
<div>

<div>
    With helper:
    {{ render "@button--beta" text="Other Text"}}
</div>
```

// Output
```html
<div>
    Without helper:
    <div>
        Class:
    </div>
    <a href="#" class="btn btn--">Other Text</a>
    <div>

        <div>
            With helper:
            <div>
                Class: beta
            </div>
            <a href="#" class="btn btn--beta">Standard Text</a>

        </div>
```

As you can see the direct @handle doesn't have the "Class" from the variants but I can overwrite the `text`. And the helper `render`have the Class but I can't overwrite the `text`. Did I missed something? 

Thank you very much! Best pattern lib so far!! Keep going! 👍

**Comment by tlenex** [comment]
the `render` helpers has this syntaxes:
- `{{render '@handler'}}`
- `{{render '@handler' myContextObject}}`
- `{{render '@handler' myContextObject merge=true}}`

where:
- `'@handler'` is sub-component handler
- `myContextObject` is an object reference in your component config like:

```json
{
"context": {
  "myContextObject": {
    "text": "Other text"
  }
}
```
- `merge=true` sets up an flag that will cause to merge all other properties from default sub-component context in the resulting render.

**Comment by macandcheese** [comment]
@tlenex so is the only way to override the default context to define alternative context objects in the main config? It would be nice to be able to do so inline as you call a component - if it is possible, what's the correct syntax to do so?

**Comment by dkhuntrods** [comment]
Thanks @tlenex!
@macandcheese, unfortunately, yes. :<
