### ISSUE TITLE
Referencing context data in the same component ?

### ISSUE THREAD

**Issue by alienlebarge** [frctl/fractal#244]
Is there a way to self-referencing context data ?

Let me explain my case:  
I have a `@teaser` component in which a `@figure` is included.

*`figure.html`*
```html
<figure>
  <a href="{{ url }}">
    ...
  </a>
  ...
</figure>
```

*`figure.config.json`*
```json
{
  "context": {
    "url": "#",
    ...
  }
}
```

If I include `@figure` in `@teaser`, I get something like this:

*`teaser.html`*
```html
<article>
  <h3><a href="{{ url }}">...</a></h3>
  ...
  {% render @figure, media %}
  ...
</article>
```

*`teaser.config.json`*
```json
{
  "context": {
    "url": "#",
    ...
    "media": {
      "url": "#"
      ...
    }
  }
}
```

In `teaser.config.json`, the two `url` are the same.Is there a way to use something like `@self.url` ?

![](http://d.pr/i/ZGpeY+)

---

ho and thank you for this awseom tool and the work you do !
We are big fans of fractal [@DSI-VD](https://github.com/DSI-VD)

**Comment by 7iomka** [comment]
I am also interested in this issue!
