### ISSUE TITLE
Fractal build command is not exiting

### ISSUE THREAD

**Issue by jamesgorrie** [frctl/fractal#245]
When running the `fractal build` command we don't seem to exit on success.
Potentially a vorpal update did this?

Here's an example of it hanging:
https://circleci.com/gh/wellcometrust/wellcomecollection.org/1884

**Comment by dkhuntrods** [comment]
Hi @jamesgorrie,
Did you see this thread here: https://github.com/frctl/fractal/issues/232?
If you update to that version, do you still get the errors?

**Comment by jamesgorrie** [comment]
Hi @dkhuntrods - [we are on 1.1.4](https://github.com/wellcometrust/wellcomecollection.org/blob/master/server/package.json#L29) and it didn't seem to solve the error.

[We just did it programmatically in the end](https://github.com/wellcometrust/wellcomecollection.org/blob/master/server/build-cardigan.js).
