### ISSUE TITLE
Undefined identifier error in Internet explorer

### ISSUE THREAD

**Issue by trollsudd** [frctl/fractal#247]
Cant change between tabs (notes,html,view.. ) in gui in internet explorer (version 11).

The console says : SCRIPT5009: Symbol har inte definierats (Undefined indentifier).
edit: mandelbrot.js (1,9747) 

works great in Chrome.

https://docs.microsoft.com/en-us/scripting/javascript/misc/undefined-identifier

**Comment by tlenex** [comment]
https://github.com/frctl/mandelbrot/pull/46 this PR adds support for IE9+
still waiting to get merged
