### ISSUE TITLE
sync reload doesn't occur when changing files in static directory

### ISSUE THREAD

**Issue by BrianWalters** [frctl/fractal#248]
Been playing with Fractal all day and I'm digging it. Going to use it for my next project. I'm running into this issue which feels like a bug:

I have a stylesheet in my static directory (`public/` by default). When I update this file, fractal's browserSync doesn't reload.

1. With a fresh Fractal instance, I started by adding `fractal.components.set('default.preview', '@preview');` to `fractal.js`
1. Then I made a preview layout at `components/_preview.hbs`:
```
<!DOCTYPE html>
<html>
{{{ yield }}}
<link href="{{ path '/styles.css' }}" rel="stylesheet">
</html>
```
3. Now I create `public/styles.css`:

```
body {
    background-color: green;
}
```
4. And finally run `fractal start --sync`

No matter how I edit `public/styles.css` my browser window will never reload. I can hardcode `console.log` calls into the fractal source and see that the changes are being picked up, but no reload occurs. For now, I can manually reload and it seems to pick up the change after that.

Moreover, is this the correct way to handle CSS? There isn't much in the docs on this topic. I would prefer to use Stylus and a watcher to rebuild the static stylesheet, but those aren't mentioned at all. I would also like to keep Stylus sheets relating to each component as siblings to them in the filesystem, but that seems to be discouraged unless I set an ignore in the syncOptions.

**Comment by dkhuntrods** [comment]
Hi @BrianWalters 
There's not much in the docs on this, as Fractal is agnostic as your asset build pipeline, and all it's doing is spinning up a BrowserSync instance and passing the config to it. We could do a better job explaining that - PRs welcome! :)

There's info here regarding the server options: 
http://fractal.build/guide/web/server

And there's info here on watching files specifically: https://www.browsersync.io/docs/options#option-files

As an example, you can set:
```
fractal.web.set('server.syncOptions', {
  notify: true,
  files: ['public/**/*', 'config/tokens/**/*']
});
```
Hope that helps!

**Comment by BrianWalters** [comment]
Hi, sorry for being sluggish following up. I figured out it was because my HTML didn't have a <head> and <body>, which BrowserSync relies on for injecting its reload script. When I added them, BrowserSync started live-reloading correctly.
