### ISSUE TITLE
Bug: Component names cannot contain underscores

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/fractal#25]
…which gets bit tricky if you wish to use BEM-like naming for your component names.

**Comment by allmarkedup** [comment]
Can you provide me with some examples (maybe even a screenshot of your components directory file/folder structure)? It seems to be working fine for me so I'm guessing I haven't got underscores in the same place as you!

**Comment by allmarkedup** [comment]
Don't worry - found the issue! It currently converts underscores to dashes. I'll change this though as I can see why that might be confusing.
