### ISSUE TITLE
Leaking partials scope

### ISSUE THREAD

**Issue by Igloczek** [frctl/fractal#252]
Let's assume that we have a helper which use some data from second parameter and a partial defined in the project.

```js
hbsEngine.handlebars.registerHelper('helper', (input, data) => {
  return data.data.root._self.baseHandle + ' ' + input; // it's the handle of component which use this helper
});
```

And then in `home.hbs` file we use it:

```hbs
{{ helper 'before' }}
{{> @partial }}
{{ helper 'after' }}
```

I expect that the `helper` remain in the same scope, but unfortunately, scope after importing the partial is set to the partial (or even if we import another partial inside also via `{{> }}` there will be its scope)

Current output:
```
home before
<rendered partial>
partial after
```

But expected result is:
```
home before
<rendered partial>
home after
```

Do you have any idea what should I check to debug it and help you with fixing it or maybe it's just expected behavior and I'm doing something wrong?

**Comment by allmarkedup** [comment]
@Igloczek that does not sound like expected behaviour! Pretty sure this is a bug... rendering a partial should not affect the template data in that way. I'll try and look into it as soon as I can.

**Comment by antoniozzo** [comment]
Looks like it's this in https://github.com/frctl/handlebars adapter.js (line 68):

```
if (entity) {
    args[2].data.root._self = entity.isComponent ? entity.variants().default().toJSON() : entity.toJSON();
} else {
    args[2].data.root._self = null;
}
```

Since it's mutating the data makes it so it bleeds outside.

Tried changing it to cloning instead of mutating and seems to work:

```
if (entity) {
    args[2].data = _.clone(args[2].data);
    args[2].data.root = _.clone(args[2].data.root);
    args[2].data.root._self = entity.isComponent ? entity.variants().default().toJSON() : entity.toJSON();
}
```

**Comment by dkhuntrods** [comment]
@antoniozzo thanks so much for tracking this down! 
@allmarkedup Shall I update the adapter?
