### ISSUE TITLE
Allow toggling context data in the UI

### ISSUE THREAD

**Issue by julmot** [frctl/fractal#256]
To test a component with different context data it would be helpful to specify values in the UI. Either based on pre-defined values or by entering values into an input field.

For pre-defined values it would be required to implement a way to only allow specify a range of values in the config files (can be helpful when including subcomponents too).

**Comment by allmarkedup** [comment]
Hi @julmot yes this is definitely something that has been requested before (and I'd like myself). 

Dynamic values are difficult is that at the expectation is that the static build and the dev server both support the same set of features, but because templates are rendered server-side it's not possible to support this functionality in the static build (as data needs to known ahead of compile time).

Being able to toggle between an known set of context data would be good. A feature request for 'scenarios' (https://github.com/frctl/fractal/issues/149) already exists which sounds similar to what you are requesting (although that does not presuppose a UI toggle).

**Comment by julmot** [comment]
Maybe we're misunderstanding ourselves but what I mean would also work with static builds due to the fact that you're just toggling pre-generated files.

Let me elaborate my use case. I have a website with a varity of "states", for example logged in or not logged in. Usually, this would be a "preview" template (root template). But, all my components must work with all of the preview templates ("states"). Therefore it would be invalid for me to assign preview template X to component Z if it should also work with preview template Y. So, what I'd need is either a way to toggle the context in the UI or a toggle for preview templates in the UI. It's a pain currently since I'm creating one component for each state. This means unnecessary redundancy and complexity. Awful, but I just don't know a better way.

**Comment by julmot** [comment]
Btw.: There's another painpoint. You'd need to save redundant meta-tags when having multiple preview templates, because I don't think `yield` can be provided when including a preview template as partial (if this would be possible at all).

**Comment by julmot** [comment]
This also applies to [variants](http://fractal.build/guide/components/variants)

**Comment by julmot** [comment]
Another approach to the one described above: A component "generic content" has context data like this:

```javascript
{
  "product": "DS–Sofie",
  "title": "Eleganz pur – die neue Damen Handtasche",
  "paragraph": [
    "Etiam porta sem malesuada magna mollis euismod. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
  ],
  "image-left": null,
  "image-right": null,
  "background-image": "/static/images/generic-content-background.jpg",
  "centered": null,
  "button": {
    "title": "Mehr zu Sofie",
    "link": true
  }
}
```

Now, in the current Fractal implementation I would have to create a variant for all of these cases. E.g.

- centered
- background-image
- centered-background-image
- image-right
- centered-image-right
- background-image-image-right
- ....

But what I would rather like to have is a select field in the Fractal UI to toggle between context information. Then I wouldn't need to create so many variants.
