### ISSUE TITLE
CLI feature request: Create components tool

### ISSUE THREAD

**Issue by julmot** [frctl/fractal#260]
To avoid creating .hbs and .config.yml files all the time, a CLI tool like in Angular 2 would be helpful.

**Comment by allmarkedup** [comment]
Hey @julmot - before replying to this issue I just wanted to quickly say thanks for all the input you've been putting into the issue tracker. I'm really slammed for time right now so I'm sorry that it's taking so long to reply to all of your (and everyone else's!) comments, but I just wanted to let you know that I've seem them and am not just ignoring them. 

A lot of the things you have mentioned are common pain points that people have with Fractal, and are definitely on the roadmap for addressing in future releases. I'm hoping to share more about that roadmap when I've managed to carve out a bit of time away from client work, hopefully soon ;-)

Anyway, regarding this specific issue - this is definitely something that will get added in in the future. In the meantime, it's not a fix but it's possible to write bespoke CLI commands to do this sort of thing if you are handy with JS and can put up with the current lack of docs around the API: http://fractal.build/guide/cli/custom-commands

Alternatively, @FrancisVega has created a pretty sweet bash CLI tool which does (I think) exactly what you need: https://github.com/FrancisVega/fractalcomp

Let me know if either of those options are useful ;-)
