### ISSUE TITLE
Allow overriding context data without @handle

### ISSUE THREAD

**Issue by julmot** [frctl/fractal#263]
A component X has 10 options. When you want to include that component, but only want to override one of the options, you need to specify `@handle` 9 times. It should be possible to use the components context data by default and only override those options that were specified.

Btw.: A namespace of each included component should be specified in the parents component context. For example if a parent component X includes two sub-components, both with a `aria-level` context option, then there is no namespace for each component.

**Comment by dkhuntrods** [comment]
@julmot Re Namespacing: as it is now, you can control what data gets passed down globally and what is specific, in the structure of your config data and templates, so it doesn't necessarily make sense for Fractal to do this in a way that could restrict many use cases.
As to your first suggestion, there are many ways around this - creating helper functions, creating variant partial files with 'baked-in' options, etc. I agree that having default context data would be ideal, but unfortunately we were restricted by having chosen Handlebars as the default engine. 
This is something planned for v2.

**Comment by julmot** [comment]
You said the restriction is due to Handlebars. What template engine will be used in the next major version?

**Comment by dkhuntrods** [comment]
The new system is plugin based, so --much the same way Babel works-- you will be able to choose the bundle (or parts thereof) that best suits your needs. Most likely, the basic starter bundle will use Nunjucks.

**Comment by julmot** [comment]
Is there a release date?
