### ISSUE TITLE
Compiled JS throwing error "unexpected token import"

### ISSUE THREAD

**Issue by gward35** [frctl/fractal#266]
Hi All I have a js file that is getting all of its content through the import function via modules.

It looks something like this

/**

App Entry Point
*/
/* global $ */

// Load site fonts
import './libs/fonts';

// import js libaries that require global scope such as jQuery, jQuery-Migrate, Foundation, etc
import './libs/global-includes';

// import the Module Controller and instantiate it
import ModuleController from './modules/module-controller';
const MC = new ModuleController();

$(document).ready(() => {
MC.loadModules($('html'));
});

However when I try and load this file into the fractal preview I get the unexpected token error import error. Is this a known issue? Is there a work around for people who have set up their projects this way ?

A good deal of the component functionality relies on JS

**Comment by allmarkedup** [comment]
@gward35 Fractal does not do any transpiling or precompilation/minification of assets for you. You likely need to run your JS through babel or similar to get this to work, and the reference the transpiled file, as native browser support for ES6 imports is not quite there yet :-)
