### ISSUE TITLE
Use HTML tags in YAML

### ISSUE THREAD

**Issue by tonimain** [frctl/fractal#267]
Heyho and thanks for this great piece of software. Makes a lot of fun to work with.
One Question . Is it  somehow possible to use html markup in our yaml files like so:
```
text: new module
context:
      fieldLabel: |
                   <strong>
                       Some Bold Text
                   </strong> and now normal continued.
```

**Comment by tlenex** [comment]
I personally think it's a good practice to mix YAML and HTML markup.
I tried different way to use config properties to hold component handlers like `@component-name`. I even managed to get an working example: https://github.com/frctl/fractal/issues/239 but it don't know if it is a bug or a feature of fractal :(

**Comment by tonimain** [comment]
Is there something new on this question? Sometimes it"s useful to use html tags inside yaml. Like using <strong> or other small attributes for text formatting, or you are ending up in splitting up every little piece into vars.

**Comment by iamkeir** [comment]
@tonimain I won't comment on suitability of using HTML in YAML... but you can already do it:
`
title: My Module
context:
  someHTML: <p>Yehaw!</p>
`
Then in your module, be sure to use three curly braces to parse HTML (2 curly braces will encode the HTML):
`
{{{someHTML}}}
`
See: http://handlebarsjs.com/expressions.html

**Comment by samuells** [comment]
Hmm, you can create sample.html file and then define this file in yaml. Or you can create lot with .js as config file ;)

**Comment by iamkeir** [comment]
@samuells oh cool, a separate HTML file is a smart idea. How do you reference an external file in the config YAML?

**Comment by samuells** [comment]
I've created js helper/parser for it kind of. I've used as advantage, that you can create component config file as .js. But we didn't want to switch configs into js - so we have a special cases, where we have config.yml and config.js. Than I just use js module to load yml settings and inject the content from specific html. 

*Sample - breadcrumb.config.yml*
```yaml
title: Breadcrumb Navigation
status: 'wip'
preview: '@preview'
context:
  breadcrumbs: ''

```

*Sample - breadcrumb.config.js*
```javascript
const configHelper = require('fractal-config-helper');
const configObject = configHelper.loadYml(__filename);
configObject.context.breadcrumbs = configHelper.sampleLoader('_breadcrumb.html');
// Export config
module.exports = configObject;
```
in `fractal-config-helper` are defined few helper functions, which I can use to load config.yml content according to the folder into the `configObject` and after that I can inject content of html file also into this `configObject`. In this case it's static definition of html, but you could build the html variable same as `__filename`.

Than you have to export  `configObject` - this is from fractal documentation. And config.js has higher priority as config.yml

**Comment by dennisgaebel** [comment]
@samuells Do you have a full gist somewhere for this type of workflow?

**Comment by samuells** [comment]
@dennisgaebel I don't have any, but if you copy paste the sample in my post it should work ;)
