### ISSUE TITLE
JSDoc, ESDoc, documentation.js support in `fractal.docs`

### ISSUE THREAD

**Issue by tlenex** [frctl/fractal#271]
Are there any plans to support JavaScript documentation generators for projects based on fractal?
Basically they all generate HTML output with all sorts of static files, and on the other hand fractal's documentation files are based on markdown with handlebars markup.

Some of those generators can generate markdown output via various plugins, but HTML output is sooo much more readable.

Was anyone able to successfully connect them?

**Comment by dkhuntrods** [comment]
Hi @tlenex, I should think this will be possible as a plugin for v2! It may not something we'd write ourselves, but v2 has been re-architected to make writing plugins as simple as possible.
We're not planning on adding any new features to v1, but a beta release for v2 is very close now.

**Comment by tlenex** [comment]
Cool, I can't wait to get my hands on stable v2
