### ISSUE TITLE
How to get fractal into directory on production?

### ISSUE THREAD

**Issue by gward35** [frctl/fractal#272]
Hi there is absolutely no documentation on how to move fractal from the localhost to a development or production server where clients can see the product i.e something like www.mysite.com/fractal/

Does anyone have the steps or knowledge to do this ?

**Comment by allmarkedup** [comment]
Hey @gward35 - this section of the docs: http://fractal.build/guide/web/builder covers how to generate a static build of the web UI. This is just plain HTML files + assets, so you can then upload and host that on a server as required. You might want to also check the [config section](http://fractal.build/guide/web/configuration) for settings that you can tweak to get the output to match your specific requirements.

**Comment by dkhuntrods** [comment]
Hi @gward35, closing this now as we haven't heard from you, but feel free to re-open if this is not yet resolved.
