### ISSUE TITLE
Linking to assets from CSS/SCSS

### ISSUE THREAD

**Issue by julmot** [frctl/fractal#274]
The [docs](http://fractal.build/guide/web) describe to use the `path` helper for view templates. However, fonts etc. are referenced from SCSS/CSS. I'm currently using absolute paths as a workaround, as this works in the Fractal environment. However, when distributing the library absolute paths aren't always correct. So I need a SCSS feature for relative paths, provided by Fractal.

I've also noticed that the `env` variable passed to templates is always `production`. It should be `development` if you're not running the build.

**Comment by dkhuntrods** [comment]
@julmot Building SCSS isn't really within the scope of Fractal. There are a number of approaches you can take here, such as rewriting paths on export, for the required environments. 

As to the `path` helper, it's not necessary to use it - I simply use eg. `/assets/resource.[ext]` in my link href and scss both, and this works fine for dev and build. The docs could do with updating on that point.

If you could open a separate issue for the `env` issue, I can investigate that. Thanks.

**Comment by nickirios** [comment]
How would one rewrite the paths for export?

**Comment by LeBenLeBen** [comment]
@nickirios This is the role of a module bundler, such as Webpack. If you use relative paths within your CSS, you can set a `publicPath` in the webpack configuration and it will rewrite your paths accordingly when it bundles everything. Checkout [liip/styleguide-starterkit](https://github.com/liip/styleguide-starterkit) for a demo of Fractal integrated with Webpack.

If you need more help, I'd suggest you to [join us on Slack](https://slack.fractal.build/).
