### ISSUE TITLE
Error: The partial @XYZ could not be found

### ISSUE THREAD

**Issue by kyleknighted** [frctl/fractal#275]
I am just getting into Fractal and have two components that live next to each other. Whenever I try to use the partial import it gives me the error that the partial can't be found. Here is my current setup.

```
├─ fractal/
│   ├─ icons/
│   │   ├─ 01-icon.hbs
│   │   ├─ 02-circle-icon.hbs
│   │   ├─ style.scss
│   │   ├─ icon.config.json
│   │   ├─ circle-icon.config.json
```

> _01-icon.hbs_
```hbs
<svg class="k-icons">
  <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#k-{{icon}}"></use>
</svg>
```

> _icon.config.json_
```json
{
  "title": "Standard Icons",
  "default": "success",
  "variants": [
    {
      "name": "close",
      "context": {
        "icon": "close"
      }
    },
    {
      "name": "success",
      "context": {
        "icon": "success"
      }
    }
  ]
}
```

> _02-circle-icon.hbs_
```hbs
<span class="k-icon-circle k-icon-circle--{{type}}">
  {{> @icon }}
</span>
```

> _circle-icon.config.json_
```json
{
  "title": "Circle Icons",
  "variants": [
    {
      "name": "default",
      "context": {
        "type": "default"
      }
    },
    {
      "name": "alert",
      "context": {
        "type": "alert"
      }
    }
  ]
}
```

Whenever I try to render `{{> @icon }}` the preview pane just has an error screen with `Error: The partial @icon could not be found`

Any idea how I can render the default icon? I don't even need it to do any of the variants as of now...

**Comment by kyleknighted** [comment]
After some digging, I realized that I set `fractal.components.set('default.prefix', 'ABC');` in my Gulpfile.

So, for anyone coming along behind me trying to figure out the same thing.

`{{> @ABC-icon }}` and the sub-component will render.

But, where I originally claimed I wasn't worried about a Variant, it looks like it doesn't automagically render with the default variable and if I use `@ABC-icon--close` it won't render the proper `icon` variable and instead just renders blank.

**Comment by dkhuntrods** [comment]
Hi @kyleknighted glad you figured out the initial issue.
The render on variant doesn't display anything, as there's no hbs template with that name - `{{@component-name}}` is just a shorthand for `{{/path-to-handlebars/component-name.hbs}}`.
To render variants with only context data, you'll need to call the name of the default component, and pass in the variant info in the context data.
