### ISSUE TITLE
Implement new panel "usage" or "use case" 

### ISSUE THREAD

**Issue by gward35** [frctl/fractal#276]
Hi I see the available panels for this project are set and are pretty rigid. If a developer needed to add a new tab to the project it would require not an insignificant amount of change to the source code and .nunj files.

I will have to do that in the interim but my request is two fold:

1. Make it easier for users to add tabs via the custom theme 
2. Consider making "usage" or "use" case a part of the fractal build

Specific to #2 I can not tell you how many times already my client has requested a usage feature to demonstrate how a component ought to be used do's and dont's within a page etc

I think it would be highly valuable and would like to know if anyone else has received a similar request 

Thanks

**Comment by sbaechler** [comment]
I haven't had any issues creating my own tab for Disqus comments. But there is no documentation,
I had to figure it out by looking at the source code.

You just have to override the theme config as described [here](http://fractal.build/guide/web/default-theme#template-customisation).

The correct file and folder structure is important:
`theme-overrides/partials/browser/panel-<mypanel>.nunj`.

The html of the override has a context object `entity` that contains a unique id and the handle.

**Comment by gward35** [comment]
Thanks Simon I had no issues creating the table however I think adding tabs
should be part of the packages functionality. Rather than having to do a
fork and maintain or risk changes getting lost if another dev does an npm i

**Comment by sbaechler** [comment]
But there is no need to fork anything. In your project there should be a fractal.js configuration file. Within that file you can override the tabs configuration.

Here is my example:
```
const mandelbrot = require('@frctl/mandelbrot');

// create a new instance with custom config options
const myCustomisedTheme = mandelbrot({
    skin: "black",
    // Add the comments panel
    panels: ['html', 'info', 'notes', 'comments']
});
myCustomisedTheme.addLoadPath(__dirname + '/src/theme-overrides');

fractal.web.theme(myCustomisedTheme);
```

**Comment by gward35** [comment]
Yes but when you make a new nunjucks file that must be preserved somehow as
it's not apart of the current build. If someone updates the package those
custom changes are gone

**Comment by samuells** [comment]
Where are you creating new nunjucks files? Because you can create `override folder` for your custom templates and if you than update it - nothing should be lost. 

http://fractal.build/guide/customisation/web-themes

**Comment by gward35** [comment]
Simon, forgive me I am just realizing what you are saying. The
/theme-overrides folder should be placed in the same directory as where the
components live? Also by setting this path to the override the data wont
get overwritten? I will try this out. Thanks so much.

**Comment by gward35** [comment]
Hi I tried this and got some errors

I added the custom panel usage in fractal js
"panels": ["html", "view", "context", "info", "notes", "usage"],

I set the path to the directory with the theme-overrides
        customTheme.addLoadPath('../../src/theme-overrides');

I use the theme
fractal.web.theme(customTheme);

**Comment by gward35** [comment]
Sorry early send, in addition to the previous email my folder structure
looks like

src
 - theme-overrides
  -partials
    -browser
     panel-usage.nunj

I get the a bunch of errors on the build but its looking in the wrong place
Error: template not found: partials/browser/panel-usage.nunj

**Comment by gward35** [comment]
Nevermind this was a path error thanks for your guidance

**Comment by sbaechler** [comment]
Glad I was able to help. Don't forget to close the issue if this solved it.

**Comment by dkhuntrods** [comment]
Thanks for helping on this @sbaechler and @samuells 💯
