### ISSUE TITLE
Support for handlebars SVGs or request for documentation on how to implement

### ISSUE THREAD

**Issue by gward35** [frctl/fractal#277]
Hi, I use an svg sprite sheet for icons on my site thus icons in the components. 

To add in an svg the syntax looks something like {{{svgSprite 'share' 'share options'}}} which renders the html 

<span class="svg-sprite -share"><svg role="img" aria-label="share options">
<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#share">
<svg id="share" viewBox="0 0 19 19" width="100%" height="100%">svg stuff here</svg>
</use></svg></span>

How can I get this working with the fractal components either through context or through some other method? My icons dont show up at all and I get no errors in the console so I think it sees my sprite sheet 

I have already loaded my svgSprite helper into fractaljs but that hasnt made a difference.

**Comment by ryanhagerty** [comment]
Hey, saw this post and thought I might be able to help since I'm employing an SVG sprite sheet with my Fractal.

I use a gulp task to build all my SVG assets into a sheet.

Then I have an `icons.html` file with: 
```<svg class="icon icon--{{modifier}}">
  <use xlink:href="/assets/icons/sprite-sheet.svg#{{modifier}}"></use>
</svg>```

Then in my JSON config I have a bunch of variants like, 
```{
      "name": "clock",
      "label": "Clock",
      "context": {
        "modifier": "clock"
      }
    }```

To load an individual asset, I just use `{{render '@icons--clock'}}`

No need to use fractaljs. Hope this helps!

**Comment by dkhuntrods** [comment]
@gward35 Hi there, the approach @ryanhagerty describes above is essentially how we approach it as well. 
(Worth mentioning that for ie11 support, you'll need something like [svgxuse](https://github.com/Keyamoon/svgxuse)) 
I'm closing this as it's more in Stackoverflow+handlebars related territory than Fractal specifically, but if you do run intro troubles do comment here again.
