### ISSUE TITLE
Render partial via config variable

### ISSUE THREAD

**Issue by iamkeir** [frctl/fractal#278]
I was hoping to use some config data (YAML) to dynamically specify another partial to render/include.

Handlebars' documentation suggests this is possible, like so:
```
{{> (lookup . 'myVariable') }}
```
See: http://handlebarsjs.com/partials.html

This however results in `The partial could not be found`.

I also found #195 and #239 regarding this.

I tried using the 'workaround' specified here but no luck: https://github.com/frctl/fractal/issues/239#issue-223851818

Is this possible?

**Comment by iamkeir** [comment]
Ah, more in depth instructions in #239 worked: https://github.com/frctl/fractal/issues/239#issuecomment-315387941

Would be good to fix the 'proper way' though.

**Comment by dkhuntrods** [comment]
Hi @iamkeir 

This is definitely possible:

1. Define the template name in your config data (note the double backslash, this escapes the component name and so prevents Fractal trying to inject context data): 
```
context: {
  inputTemplate: '\\@input-pair'
}
```
2. Render your dynamic partial in your `.hbs` file:
```
{{>(lookup . 'inputTemplate') }}
```

Let me know if this helps.

**Comment by iamkeir** [comment]
@dkhuntrods yippee, thank you so much! Although it was actually a single backslash I needed in the end: `\@input-pair` - two slashes threw `The partial \@input-pair could not be found`.

Thanks very much - @tlenex will be pleased :)

**Comment by tlenex** [comment]
I'am. Thanks @dkhuntrods !

**Comment by Januszpl** [comment]
@dkhuntrods could you tell me how I can pass the context data with merge=true in the example blow?


<details open>
<summary>buttons.hbs (list of different components based on buttons.config.js)</summary>

```handlebars
    {{#each items}}
        <div class="buttons__item {{ this.itemClass }}">
           {{render '@button-dev' this.buttonTemplate merge=true }}

            {{>(lookup . 'inputTemplate') tag="button" text=this.buttonContext.text merge=true}}

        </div>
    {{/each}}
```

</details>

**Render**
renders properly button--secondary (based on value of this.buttonTemplate in buttons.config.js for each item). However how I can pass here context for specific items in buttons.config.js to modify for example text propert?


**lookup**
renders proper template based on current item data context - inputTemplate variable.
However I need to pass all properties like tag, text, etc to be able to see proper button. 
It doesnt use default context from button-dev or its variants button-dev--secondary
 

<details open>
<summary>with buttons.config.js</summary>

```javascript
 context: {
    items: [
      {
        id: 'button-dev',
        btnName: 'Default button used in many places 2',
        class: '',
        buttonTemplate: '\@button--secondary',
        inputTemplate: '\\@button-dev--primary'
      },
      {
        id: 'button-dev--secondary',
        btnName: 'Default button used in many places 3',
        buttonTemplate: '\@button--secondary',
        inputTemplate: '\\@button--secondary',
        buttonContext: {
          text: 'AAA'
        },
      }
    ]
  }
```
</details>

**Default button dev used in above examples**

<details>
<summary>Default button-dev.hbs</summary>

```handlebars
<{{{ tag }}} class="button {{ class }}" {{{ attributes }}}>
    {{#if textWrapper }}
       <{{ textWrapper }}>
    {{/if}}
       {{ text }}
    {{#if textWrapper }}
       </{{ textWrapper }}>
    {{/if}}
    {{#if iconId }}
        <svg title="{{ iconId }}" class="{{ iconClass }}">
            <use xlink:href="{{ svg iconId }}"></use>
        </svg>
    {{/if}}
</{{{ tag }}}>
```
</details>


 <BR>
<details>
<summary>button-dev.config.js</summary>

```javascript
  context: {
    tag: 'button',
    class: '',
    attributes: 'type="button" aria-label="button"',
    text: 'I am a button'
  },
  variants: [
    {
      name: 'primary',
      context: {
        text: 'Primary btn',
        class: 'button--primary',
        attributes: 'type="button" aria-label="button"'
      }
    },
```
</details>

**Comment by thomasaull** [comment]
Is this also possible using the nunjucks-adapter?

**Comment by flepp** [comment]
Hi, I was wondering the same as @thomasaull. Has anyone managed this with nunjucks?

**Comment by LeBenLeBen** [comment]
I'm doing it like this, maybe there's a nicer way though.

component.config.yml

```yaml
context:
  childTemplate: card--zoom
  childContext:
    foo: bar
```

component.nunj
```html
{% render '@' + childTemplate, childContext %}
```

**Comment by flepp** [comment]
Thank you @LeBenLeBen . Works as intended!

**Comment by thomasaull** [comment]
@flepp, @LeBenLeBen Another way to do it is to set your childTemplate like `\\card--zoom' and render it like

```
{% render childTemplate, childContext %}
```
