### ISSUE TITLE
Better {{render '@

### ISSUE THREAD

**Issue by tonimain** [frctl/fractal#281]
It's very difficult to relate from the code where to found an specific element. Actual I have a style guide with 500+ elements. So for better navigation it makes a lot of sense to use the @ name space with the concurrent folder where the element exists.  Something like `{{render '@atoms/button@}}`

Is this somehow possible?

**Comment by tlenex** [comment]
This can be achived with new collection directory (lets say it will be called `my-collection`), and defining `prefix` (see [docs](http://fractal.build/guide/components/configuration#prefix)) property in it's config file in that folder (its name should be the same as new directory, so:  `my-collection.config.json`).

More on collections here: http://fractal.build/guide/components/configuration#collection-properties

**Comment by dkhuntrods** [comment]
@tonimain does @tlenex's suggestion help?
Alternatively, you can use the full path to the component rather than the '@' identifier shorthand, but then you do lose out on the ability to move things as easily.
