### ISSUE TITLE
env variable is always production

### ISSUE THREAD

**Issue by julmot** [frctl/fractal#282]
I've noticed that the `env` variable passed to templates is always `production`. It should be `development` if you're not running the build.

Issue created like wished in #274.

**Comment by dkhuntrods** [comment]
Thanks @julmot, will look into it

**Comment by dkhuntrods** [comment]
Hi julmot, there is an `env` variable that defaults to `'production'`, but it is only set in config and doesn't really get passed down to templates in the same form, so we're not entirely sure what `env` you're referring to. Can you give a bit more detail?
Either way, we wouldn't be setting default values on those for build vs. dev: we can't assume how someone might be running Fractal, so we can't really make those kinds of assumptions. If an actual `NODE_ENV` variable is set though, the config will pick them up.

**Comment by julmot** [comment]
I guess this is exactly what I'm referring to: `_config.env` and it's always `production`. For cases like described in #321 it would be helpful to set it to `development` when you're using Fractal with `start`.

> we can't assume how someone might be running Fractal

Sorry, I don't understand what you mean. What other ways can be possible than `start` and `build`?
