### ISSUE TITLE
Cant pass data to new tab?

### ISSUE THREAD

**Issue by gward35** [frctl/fractal#284]
I created a new tab using the method in the docs 
http://fractal.build/guide/customisation/web-themes

It looks like this 
```
// require mandelbrot for custom themeing
const mandelbrot = require('@frctl/mandelbrot');

// new instance of theme with custom options
const customTheme  = mandelbrot({
	"panels": ["html", "view", "context", "info", "notes", "usage"],
  	"skin": "orange"
});

//add specific load path for template to get custom tab/template src/theme-overrides
customTheme.addLoadPath(paths.template);

// use custom theme instead of default
fractal.web.theme(customTheme);
```

However when I go to a components config and try to add data ie. 

`usage: "This is some stuff"`

Nothing gets passed. If you can customize a theme and tabs how do you pass data to them without touching the source code? 

FWIW my custom template looks like this:

```
<div class="Browser-panel Browser-usage" data-role="tab-panel" id="browser-{{ entity.id }}-panel-usage">
    <div class="Prose Prose--condensed">
        {% if entity.usage %}
        {{ frctl.docs.renderString(entity.usage, renderEnv) | async }}
        {% else %}
        <p class="Browser-isEmptyUsage">There are no use cases for this item.</p>
        {% endif %}
    </div>
</div>
```

I essentially need the functionality of two notes tabs but they need to be called different things and have different data

**Comment by matt-tyas** [comment]
Did this ever get resolved? I need to do the same thing.
