### ISSUE TITLE
Collection `title` not obeyed in nav

### ISSUE THREAD

**Issue by ChrisBAshton** [frctl/fractal#285]
I have a dir structure like this:

```
components/
    layouts/
        layouts.config.yml
        layout-1/
        layout-2/
        etc/
```

The YML file contents:

```
title: "Website Layouts"
status: "ready"
context:
    title: "My Website"
```

We're using a theme inheriting from mandelbrot.

I would expect the collection title in the left navigation to be `Website Layouts` but it stays as `Layouts`.

I know the config file is being obeyed because if I add `hidden: true` to the config, the collection gets removed from the nav. Is this a bug or have I not configured it correctly?

**Comment by dkhuntrods** [comment]
Hi @ChrisBAshton, in this case I think you're looking for the `label` property, see here: 
http://fractal.build/guide/collections/configuration#collection-properties
