### ISSUE TITLE
Bug: TypeError: Handlebars.create is not a function

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/fractal#30]
When adding notes to a component, thus:

```yaml
status: ready
notes: Use `block` to segregate content into a grid. Each child `block__item` will alongside siblings at larger breakpoints, its width dictated by the number of siblings in a block.
```

Fractal throws an error: `TypeError: Handlebars.create is not a function` and the list of components in the navigation disappears.

**Comment by allmarkedup** [comment]
Fixed with latest release of `frctl/handebars-adapter`.
