### ISSUE TITLE
Add the ability for users to filter components list based on the status

### ISSUE THREAD

**Issue by citation-nm** [frctl/fractal#301]
Hi all,

Not sure if this has been requested before, but I think it would be a neat feature to allow users to be able to filter the components list (in the left menu) by the status of each. I.e. Only show components that are ready. It would also be beneficial to store this preference in local storage so that it becomes persistent for each user.

Many thanks,

Neil

**Comment by dkhuntrods** [comment]
Hi @citation-nm, filtering is actually being implemented for v2, although I don't know if we'd looked at persistence as yet - definitely worth exploring  👍

**Comment by macandcheese** [comment]
Related - an "index" sheet or Table of Contents that lists all components and their status would be awesome - something like this: https://vmware.github.io/clarity/documentation
