### ISSUE TITLE
Enhancement: Add support for running on Windows

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/fractal#31]
The use of `kexec` in https://github.com/frctl/fractal/blob/57f8d8d67c0ee9bb63814d05439a5c58f191025b/src/commands/reboot.js is a barrier to successfully installing Fractal on a Windows machine.

**Comment by paulrobertlloyd** [comment]
Just to add some context to this bug, of the last two projects I’ve worked on that involved handing over a pattern library, both involved a development team that use a Windows-based software stack.

**Comment by allmarkedup** [comment]
@paulrobertlloyd  - I've just released v0.10.1 which removes the dependency on the kexec module. It's a shame as the fractal CLI now cannot be rebooted from within itself (which was useful if you make changes to the fractal.js file) but I think windows compatibility is more important!

I haven't actually tested it on windows to see if everything else runs on but this should certainly address the installation issue.

**Comment by paulrobertlloyd** [comment]
Thanks Mark!
