### ISSUE TITLE
Merge all the components

### ISSUE THREAD

**Issue by sorknes** [frctl/fractal#330]
Is there a way of looping trough all the hbs files stored in the components folder (and subfolders), and displaying them on e.g. all.hbs file?

Something like [this](https://cdn-images-1.medium.com/max/1600/1*Hz0Z4NpYRVlgTaqfVTrVCQ.png).

I've tried using handlebars partials, but cannot figure this out. When trying to use partials all I get is an error saying: The partial @partial-block could not be found

**Comment by VolleMelk** [comment]
Yes! That would be cool.

Something like Pattern Labs "all" or Fabricator's page view

**Comment by tjnicolaides** [comment]
This is something our team has been working on with limited success so far. Our approach has been to make a new route in our theme repo and repurpose some of the navigation.nunj logic to print our component tree. We're stuck at the part where the components are actually rendered. Warning: what's below is experimental and not very DRY at the moment:

1. In src/theme.js: 
```
   theme.addRoute('/components/dossier', {
        handle: 'dossier',
        view: 'pages/components/dossier.nunj'
    });
```

2. New file called views/pages/components/dossier.nunj:
```
{% import "macros/dossier.nunj" as nav %}

{% if frctl.components.size %}

{{ nav.tree(frctl.components, entity, request) }}

{% endif %}
```

3. New file called views/macros/dossier.nunj (which is mostly a copy of views/macros/navigation.nunj, so this is truncated for illustration purposes ): 
```
{% macro leaves(items, root, current, depth, request) %}
    {% for item in items %}
        .............
             <li><strong>Name:</strong> <a class="think-nav-list-entityLink" href="{{ path( (item | url), request) }}" data-pjax>
                <span>{{ item.label }}</span>
                {% if item.status %}{{ status.unlabelled(item.status) }}{% endif %}
            </a>
            <strong>Handle:</strong> <code>@{{ item.handle }}</code>
            <!-- SOMETHING HAPPENS TO RENDER THE COMPONENT HERE --> 
          </li>
       .............
    {% endfor %}
{% endmacro %}
```

A few of the things we've tried so far to render components in that tree view we've created include:

logic borrowed from: views/layouts/render.nunj
```
{% set rendered = item.render(null, renderEnv, { preview: true, collate: true }) | async(true) %}
{{ rendered }}
```

render helper (throwing an error - researched from docs here: http://fractal.build/guide/components/sub-components)

```
{{ render '@' + item.handle }}
```

Any suggestions or ideas are welcome here as we continue to get familiar with Fractal and Handlebars. If we figure out the theme-based solution we'll be sure to share here.

**Comment by tjnicolaides** [comment]
Hey @shooftie! No real progress since then. We were excited about the ability to do this with Fractal v2 but ultimately we decided to ship our pattern libraries without this in the time since then.

**Comment by shooftie** [comment]
Thanks mate. I will persevere for the time being then and i guess I'll join you in the welcoming committee for V2.
