### ISSUE TITLE
Possible to disable template renderer for specific components/parts of components? 

### ISSUE THREAD

**Issue by querkmachine** [frctl/fractal#337]
Hey all, 

I'm in a situation where some components use [Vue.js](https://vuejs.org) for rendering parts of the component. Vue's templating syntax is fairly similar to those used by Handlebars, Nunjucks, Angular, et al. and unfortunately does not work within Fractal. 

As per the title, is there a way to disable the template renderer (Handlebars, Nunjucks) for specific components; or alternatively, to disable the template rendering for only parts of the page (e.g. with some sort of escaping tag)? If not, is this a feature worth consideration? 

Thanks! 
~ Kim

**Comment by dkhuntrods** [comment]
Unfortunately not in v1, however in v2 (in progress) there is the option to use more than one type of engine to render your components, which should enable you to compose larger patterns as needed. 

An escaping option feels like it could get messy, but I'd be interested in @allmarkedup's take.

**Comment by ajkandy** [comment]
I have a similar issue, where our project is dependent on Angular to render everything. Fractal ticks a lot of boxes for what we want to do, certainly could work for code, but it'd be hard to include live previews; the need for Angular to control the entire view context means we can't use it for now. Looking forward to see what v2 brings. 

On that note, I had read a few things about how Shadow DOM might be used to create encapsulated views separate from the parent context - might that be a solution? (Designer, not coder here).
