### ISSUE TITLE
Allow for template include functions to call arbitrary paths

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/fractal#34]
I wish to use a path within a nunjucks `{% include %}`, as allowed by that templating language. However, Fractal only allow authors to use a `@handle`. Reason: I wish to keep all SVGs within their own folder within my assets directory, and then include them inline.

From @allmarkedup:
> no that is not currently possible… arbitrary includes would be quite a nice feature but it would have to be template-engine specific. Open and issue and I will try to get to it!

**Comment by allmarkedup** [comment]
@paulrobertlloyd - I've just implemented this in the latest release of the nunjucks adapter (v0.4.5). I've updated the [README with instructions](https://github.com/frctl/nunjucks-adapter#including-and-extending-non-component-view-templates), let me know if you have any probs.

**Comment by paulrobertlloyd** [comment]
Thanks—works a charm!
