### ISSUE TITLE
possible script injection on error pages

### ISSUE THREAD

**Issue by FND** [frctl/fractal#341]
I just noticed that error messages are not sanitized, which means it's possible to inject `<script>` tags:

```html
<code class="Error-stack">
        <pre>…/sample.jsx:3
    return <script>alert("foo");</script>
           ^
SyntaxError: Unexpected token</pre>
</code>
```

(In this case, that error resulted from using JSX.)

I don't think this is a huge deal, but figured it might be worth mentioning.

**Comment by dkhuntrods** [comment]
Thanks @FND, will ensure this is address in v2
