### ISSUE TITLE
Double Scrollbar

### ISSUE THREAD

**Issue by julmot** [frctl/fractal#342]
The actual Fractal doc contains two scrollbars, and they are cut-off at the top due to the gradient:

![2017-09-17 21_12_41-fractal user guide _ fractal documentation](https://user-images.githubusercontent.com/8310677/30524075-11f1b840-9bed-11e7-9538-4dd2f3234a71.png)

Browser: Latest FF on Windows

**Comment by dkhuntrods** [comment]
Hi @julmot, thanks for spotting. I don't know if the docs have been tested in latest FF on Win: @paulrobertlloyd?

**Comment by dgautsch** [comment]
Confirmed on Mac Firefox too:

![screenshot 2017-09-29 11 36 06](https://user-images.githubusercontent.com/165664/31023630-73ea118e-a50a-11e7-8a6b-7282a36252bf.png)

**Comment by paulrobertlloyd** [comment]
I wouldn’t know the answer to this off-hand, as I didn’t code the docs site.

**Comment by dkhuntrods** [comment]
@paulrobertlloyd apologies, thought you'd worked on that. Thanks.
@julmot We're rewriting and recoding the docs for v2, so this is fairly low priority at the moment.
