### ISSUE TITLE
`sudo npm install -g @frctl/fractal` fails at css-beautify.js

### ISSUE THREAD

**Issue by dsiegel1** [frctl/fractal#343]
Hi, 

I wanted to setup fractal on my Mac (10.12) and came across some error I cannot source. After running `sudo npm install -g @frctl/fractal` the process fails with the following output:

> npm verb stack Error: ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/@frctl/fractal/node_modules/js-beautify/js/bin/css-beautify.js'
> npm verb stack     at Error (native)
> npm verb cwd /Users/xx/Sites/xx.loc
> npm ERR! Darwin 16.7.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "@frctl/fractal" "-verbose"
> npm ERR! node v6.11.3
> npm ERR! npm  v3.10.10
> npm ERR! path /usr/local/lib/node_modules/@frctl/fractal/node_modules/js-beautify/js/bin/css-beautify.js
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall chmod
> 
> npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/@frctl/fractal/node_modules/js-beautify/js/bin/css-beautify.js'
> npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/@frctl/fractal/node_modules/js-beautify/js/bin/css-beautify.js'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent 
> npm verb exit [ -2, true ]

The directory `/usr/local/lib/node_modules/@frctl/fractal/node_modules/` is properly created during the process (.. and gets deleted when the error pops). Any idea what the actual problem is? Note: I am behind a corporate proxy.

Best

**Comment by jnachtigall** [comment]
I've just hit the same error on Windows 10. Any workaround?

**Comment by jnachtigall** [comment]
FWIW, pinning js-beauty in package.json to the following seems to be a good workaround:
```
"js-beautify": "1.6.14"
```

**Comment by dkhuntrods** [comment]
Hi @dsiegel1, thanks for bringing this to our attention. There's an issue with the latest build of `js-beautify`, see: https://github.com/beautify-web/js-beautify/issues/1247
We'll pin the version for now, as @jnachtigall suggests, until a fix is made.

**Comment by dkhuntrods** [comment]
@dsiegel1 I've released a new version, v1.1.6; can you let me know if that fixes it for you?

**Comment by dsiegel1** [comment]
@dkhuntrods it works! Thanks a lot
