### ISSUE TITLE
Greenkeeper update broke fang API use

### ISSUE THREAD

**Issue by alexrussell** [frctl/fractal#346]
I might be wrong about this, but I'm having an issue whereby the output of fang@2.x is inconsistent with the output of fang@1.x, which the code in the config loader relies on.

The config loader relies on a key `mode` coming back from fang (see https://github.com/frctl/fractal/blob/master/src/core/data.js#L50), but fang no longer returns a `mode` key, instead going for two possible separate `*_mode` keys: `ace_mode` and `codemirror_mode`.

As such, either the `fang` dep should be reverted to `^1.0.0` or the code should be updated to use the `ace_mode` or `codemirror_mode` key (though it's worth saying that different languages in `fang` appear to sometimes not have the `codemirror_mode` key in v2, `ace_mode` appears to be consistent, though).

**Comment by julmot** [comment]
Experiencing the same issue. Can't build anymore. Ping @allmarkedup

**Comment by julmot** [comment]
Or @dkhuntrods

**Comment by julmot** [comment]
Tried to fix it with #348.

**Comment by dkhuntrods** [comment]
Thanks @alexrussell, @julmot 
I'll look into this now

**Comment by dkhuntrods** [comment]
@alexrussell @julmot 
Updating all `ace_mode` references stopped the immediate error, but the localhost issue was still present, so I've reverted the dependencies for now until we have time to look in more detail as to why that's occurring.

**Comment by julmot** [comment]
That's what I've done [here](https://github.com/frctl/fractal/pull/348#issuecomment-330352712) so this should fix it.

**Comment by alexrussell** [comment]
v1.1.7 fixes the fang issue for me.
