### ISSUE TITLE
Collating a single element does not use the collator() function

### ISSUE THREAD

**Issue by imsky** [frctl/fractal#349]
If I have a config with a collator function defined and only one variant, the collator is not run.

This is a little annoying since then the only other option is creating a custom preview layout (as I understand). Unless there's a technical reason for this, I think it's a bug.

**Comment by allmarkedup** [comment]
hey @imsky - I haven't dived into to this yet but if that is the case then yes, I'd agree it's a bug. Can I just check that as well as specifying the collator function you are setting the `collated: true` property in your component config?

**Comment by imsky** [comment]
that's right, collated is `true`
