### ISSUE TITLE
fractal start fails to start on windows due to an error in the example

### ISSUE THREAD

**Issue by bux** [frctl/fractal#350]
After running `fractal new fractal-test` and trying to start fractal using `fractal start --sync` the process throws an error:
![image](https://user-images.githubusercontent.com/1235520/30585506-64ac9488-9d2d-11e7-934d-5753038c58fa.png)

Though getting the message that the server "is running", the process stopped and the server doesn't start.

Inspecting the example files I kinda doubt that.

**Comment by dkhuntrods** [comment]
Hi @bux, this is due to #346 - I'm investigating that now, so will close this as duplicate
