### ISSUE TITLE
slack.fractal.build returns a 502 error

### ISSUE THREAD

**Issue by bux** [frctl/fractal#351]
Not an issue in particular with fractal:

When navigating to http://slack.fractal.build/ the server returns a 502 Bad Gateway error.

**Comment by dkhuntrods** [comment]
Thanks @bux, I've let @allmarkedup know and am going to close this as it's not directly a Fractal issue.

**Comment by blaasvaer** [comment]
This still return a 502 Bad Gateway?

**Comment by bux** [comment]
no

**Comment by sabsaxo** [comment]
Well, it did. And seems to have done before ... so maybe something unstable is going on?
