### ISSUE TITLE
Copy updated static assets when building fractal

### ISSUE THREAD

**Issue by mascardoso** [frctl/fractal#352]
Hi there.
This is not a issue but a possible improvement.
I really like Fractal but there was something that I was missing that actually could belong perhaps to it's core in some way, or not... 

Keeping my assets files always updated is essential.
For instance. If I change `colors.scss` in my core project and I find relevant that this file belongs to the fractal styleguide assets folder I would just normally copy it, correct? If I change again I might fall in forgetting to copy again and therefore the styleguide is not inline with my core project.

So everytime I do a build I do a couple of things. (I'm using webpack for fractal btw)

In my fractal `component.config.json` file I added the following to it:

```json
{
  "assetsToCopy" : {
    "outputPath": "styles/colors",
    "files": [
      {
        "src" : "scss/",
        "name" : "colors.scss"
      },
      {
        "src" : "scss/config/",
        "name" : "colors-config.scss"
      }
    ]
  }
}
```

`path` is just a reference of where it should go within the src of my
`files` is an array with the files that I should have / copy

So, on my webpack on the build process I just find my source file and send it to the styles/colors folder:

```js
const path = require('path')
const find = require('find') // nice dependency to search for files
const fs = require('fs')
const log = console.log

class CopyPatternsAssets {
  constructor (regex, pathFolder) {
    this.regex = regex
    this.pathFolder = pathFolder || {}
  }

  checkPatternsJsonsToRead () {
    find
      .eachfile(this.pathFolder, (jsonFile) => {
        const filename = path.basename(jsonFile)

        if (filename.match(this.regex)) {
          const config = require(jsonFile)
          if (typeof config.assetsToCopy !== 'undefined') {
            this.copyFilesToAssetsFolder(config.assetsToCopy)
          }
        }
      })
      .end(() => {
        log('finished copying assets for each component')
      })
  }

  copyFilesToAssetsFolder (assetsToCopy) {
    for (const file of assetsToCopy.files) {
      fs
        .createReadStream(path.resolve(__dirname, `../front/${file.src}${file.name}`)) // read src file
        .pipe(fs.createWriteStream(`./ui/src/${assetsToCopy.outputPath}/${file.name}`)) // copy it to fractal 
    }
  }


  apply (compiler) {
    compiler.plugin('done', () => {
      this.checkPatternsJsonsToRead()
    })
  }
}


module.exports = {
 ....
  plugins: [
    new CopyPatternsAssets(
      /.*\.(config)(.*\.(json))$/,
      path.resolve(__dirname, 'src')
    )
  ]
}


```

For me it looked like a very easy way to always keep the `colors.scss` file for instance always updated... or any other file, which is the reason of having a "living styleguide".

Let me know your thoughts

**Comment by allmarkedup** [comment]
Thanks for this @mascardoso. At the moment we have intentionally left any asset handling out of Fractal as people's workflows and setups are so varied and we have wanted to avoid being too prescriptive. However I realise that this is a pretty big stumbling block for a lot of people and it's something we are definitely looking to try and improve in the future. We are looking at webpack as a possible option so will definitely keep your suggestion in mind 👍

**Comment by mascardoso** [comment]
Great @allmarkedup. Keep up the good work!

**Comment by mahish** [comment]
I find it as a core feature as well. First, I wrote npm script for it. But since Fractal uses gulp, I switched to gulp task instead. I simply read filenames of source `less` files in `fractal/source/assets/components/` folder where I have all component-related less files. Then copy them to the the folder of the same name in `fractal/source/components/` folder. Still need to figure out how to handle subfolders. Feels kinda hacky tho… 

```javascript
// Generate CSS file for every component and move it to the component folder
gulp.task('css:components', () => {
  return gulp.src([`${paths.src}/assets/c/components/**/*.less`, `!${paths.src}/assets/c/components/components.less`])
    .pipe(plumber())
    .pipe(ignoreLessWithoutComponent())
    .pipe(less())
    .pipe(rename(path => {
      path.dirname += "/" + path.basename;
    }))
    .pipe(gulp.dest(`${paths.src}/components/`));
});


// Copy component .less files to the component folder
gulp.task('less:components', () => {
  return gulp.src([`${paths.src}/assets/c/components/**/*.less`, `!${paths.src}/assets/c/components/components.less`])
    .pipe(rename(path => {
      path.dirname += "/" + path.basename;
    }))
    .pipe(ignoreLessWithoutComponent())
    .pipe(gulp.dest(`${paths.src}/components/`));
});
