### ISSUE TITLE
Adding handlebars layouts helper

### ISSUE THREAD

**Issue by magnify** [frctl/fractal#355]
Hi,

I am trying to add the layouts helper to Fractal, but having some trouble getting it to work.

I have added it to fractal.js following the the guide located here: http://fractal.build/guide/core-concepts/views#customising-handlebars

I have added the needed packages (@frctl/handlebars, handlebars-helper and handlebars-layouts).

I have a file named "grid.hbs" and want to extend that in "grid-full-width.hbs".

**fractal.js**
```
const instance = fractal.components.engine();

// Using handlebars-layouts (https://www.npmjs.com/package/handlebars-layouts)

const layouts = require('handlebars-layouts');
layouts.register(instance.handlebars);

// Using handlebars-helpers (https://github.com/assemble/handlebars-helpers)

const helpers = require('handlebars-helpers');
helpers({
    handlebars: instance.handlebars
});
```

**grid.hbs**
```
<div class="grid">
  {{#block "content"}}
    Fallback content
  {{/block}}
</div>
```

**grid-full-width.hbs**
```
{{#extend "grid"}}
  {{#content "content"}}
    New content
  {{/content}}
{{/extend}}
```

**Output**
```
[object Object]
```

Anyone have an idea what I am doing wrong?

**Comment by acespace90** [comment]
Hi, here http://fractal.build/guide/core-concepts/views#customising-handlebars i found the solution for the same issue. I solved adding these lines of code into `fractal.js`


```
const hbs = require('@frctl/handlebars')({
    helpers: {
        uppercase: function(str) {
            return str.toUpperCase();
        }
    }
    /* other configuration options here */
});

const instance = fractal.components.engine();

// Using handlebars-layouts (https://www.npmjs.com/package/handlebars-layouts)

const layouts = require('handlebars-layouts');
layouts.register(instance.handlebars);
```



I don’t know if is the best solution, but it worked for me :wink:

**Comment by magnify** [comment]
Thanks for the input, it send me in the right direction and with a few modifications it looks like it works!

Here is my final snippet:
```
/*
 * Add layouts helper
 */
const hbs = require('@frctl/handlebars');

const instance = fractal.components.engine(hbs);

// Using handlebars-layouts (https://www.npmjs.com/package/handlebars-layouts)

const layouts = require('handlebars-layouts');
layouts.register(instance.handlebars);
```
