### ISSUE TITLE
web UI 'close' start of svg is a little odd in Firefox

### ISSUE THREAD

**Issue by sturobson** [frctl/fractal#36]
I've not managed to work out why (as yet) but the close icon is a little 'squished' in Firefox (Dev Edition v47).

<img width="45" alt="screen shot 2016-04-03 at 11 59 07" src="https://cloud.githubusercontent.com/assets/925197/14232070/a3a56762-f993-11e5-8d2c-dbe0b902850b.png">

**Comment by paulrobertlloyd** [comment]
This is a known issue: https://github.com/frctl/mandelbrot/issues/13

It seems as if Firefox gets its co-ordinates muddled during the transform.

**Comment by sturobson** [comment]
Thanks @paulrobertlloyd -- I didn't think to look in 'the right place' before raising this. Closing as it's a duplicate of [frctl/mandelbrot#13](https://github.com/frctl/mandelbrot/issues/13)
