### ISSUE TITLE
From where does Fractal (compile and) serve files on localhost:3000?

### ISSUE THREAD

**Issue by sabsaxo** [frctl/fractal#360]
In order to try and track down path issues, I'm looking for the compiled files served on localhost. But I simply cannot figure out where those files get »put and served«. I'm on Mac OS X ... if that matters.

**Comment by dkhuntrods** [comment]
Hi @sabsaxo, do Mark's comments on #359 address this issue?

**Comment by blaasvaer** [comment]
Well, not really. I'm still struggling with the paths to fonts relative to css files ... so I'm simply trying to figure out what's going on »behind the scenes« if you like. I've found a spot in the mandelbrot theme where various routes are set. But I'd like to know how to eliminate this error:

```
http://localhost:3000/static/main/font/proxima-nova-light/mark_simonson_-_proxima_nova_light-webfont.ttf?c=u32777e7c
```
in relation to my css files ... hmm.

**Comment by blaasvaer** [comment]
I did solve some of the issues by adding a symlink in my assets folder that points to a folder outside the directory where the fractal.js file sits. But this one seem to bug me even more ... I can't seem to get my head around the paths, relative or absolut doesn't matter.

My css files contain paths to fonts, and I can't seem to figure out where to put what in relation ... everything works fine in all other contexts but fractal.

**Comment by sabsaxo** [comment]
Well, I finally (!) managed to fix the issue(s) by creating a symlink that points a few levels out of the src folder and then adjusting all paths by adding some dot dot slash prefixes, and a bit of renaming and stuff. Messy, but it (sort of) works.

**Comment by dkhuntrods** [comment]
Hi @blaasvaer, glad to hear you've found a solution. It does sound like what you're trying to do might be pushing the limits of what scenarios v1 was intended for :)
