### ISSUE TITLE
Where to put assets (since preview and build render different paths)?

### ISSUE THREAD

**Issue by blaasvaer** [frctl/fractal#363]
When running:

`fractal build`

I can access my assets correctly from within the dir at: build/assets

But when I run:

`fractal start --sync`

I get a `‼︎ 404: No matching route found for /components/preview/assets ...<assets here>`.

Now, where should I put my assets to have them work in both cases?

It seems it's the internal Mandelbrot theme file that sets a route:

```
    theme.addRoute('/components/preview/:handle', {
        handle: 'preview',
        view: 'pages/components/preview.nunj'
    }, getHandles);
```

So I guess(!), that I have to put them in a VERY specific place!?

**Comment by dkhuntrods** [comment]
Hi @blaasvaer, do Mark's comments in #359 address this issue?
