### ISSUE TITLE
Moving Fractal in a different way with webpack

### ISSUE THREAD

**Issue by tlenex** [frctl/fractal#366]
Fractal is a build system, same as webpack, but webpack can do so much more and has a huge community around it.

I was just wondering. Why not move fractal engine mechanic into webpack configuration? Why developing the wheel again?

This could work in form of a webpack plugin: https://webpack.js.org/concepts/plugins/

1. Before compilation, define an entrypoint link for each component (eg. hbs) https://webpack.js.org/concepts/entry-points/
2. Each entry point is loaded along with it's dependencies based on it's file extension https://webpack.js.org/concepts/loaders/
3. Compile the templates including fractal "previews" defined as plugin options and transform other dependencies.
4. Output as html https://webpack.js.org/concepts/output/ and give an option in plugin configuration to do it with and/or without styleguide, posssibly limit output components by prefixes for non-styleguide output(so you can retrive plain pages)

What do you think about this idea?

Some template engine loaders:
https://github.com/webpack-contrib/awesome-webpack#component--template
https://www.npmjs.com/package/twig-loader
https://github.com/at0g/nunjucks-loader

**Comment by blaasvaer** [comment]
And why tie is specifically to webpack? How about Gulp, Grunt, Brunch, Pint etc. ... ?

**Comment by tlenex** [comment]
You're right on this point. Decision on which to choose would case a lib wars. 

Currently i'm struggling with connection of those two systems, mainly for performance reasons (lazy-loading and chunk generation) in some of my projects, that's why i came up with this idea.

But, as mark already said on slack, fractal v2 is aiming to expose an API for everybody needs. :crossed_fingers:

**Comment by blaasvaer** [comment]
Just a little curious. I'm new to this Slack thing, how do I find that comment from Mark : ). Can't seem to sign into the workspace fractal.slack.com.
