### ISSUE TITLE
"Maximum call stack size exceeded" with '@component-name' in context

### ISSUE THREAD

**Issue by fvsch** [frctl/fractal#374]
I'm trying to expose the context of some components everywhere, like this:

```js
fractal.components.set('default.context', {
  'footerContext': '@footer'
});
```

Or by putting `context: {'footerContext': '@footer'}` in a config file at the root of my components folder (`prototype/prototype.config.js` in my case).

This results in an error logged in the console:

> ✘ RangeError: Maximum call stack size exceeded

And template rendering failing in several vues, with the same kind of message.

Using the `"@component-name"` syntax for context values lower down in the folder tree worked well enough.

**Comment by dkhuntrods** [comment]
@fvsch that sounds like an infinite loop error, which could occur if you're including the context of a component inside itself. In this case, it looks as though @footer will be included inside all component, including @footer... you see where this is going? 😄 
To avoid that, you might try creating a separate file that exports the shared data, and then including that file in the footer context data, and again, separately, in the default context data. Does that makes sense?

**Comment by fvsch** [comment]
I think that would work. I’m going to close this issue, and document what we did to use component context in includes from "pages", if anyone finding this issue is interested. :P

We had two needs:
1. Getting the default context of the footer and header components in the preview template
2. Getting the default context of lots of components components 'page' templates

### For the preview template

```js
// components/preview.config.js
module.exports = {
  context: {
    headerContext: '@header',
    footerContext: '@footer'
  }
}
```

```twig
{# _preview.twig #}
{% include '@header' with headerContext %}
…
{% include '@footer' with footerContext %}
```

### For 'page' templates

We made a `components/page` folder, with each mock-up page being a sub-component. And in their common config, we import the context of components that live outside that page folder, so there is no loop going on.

```js
const exposedComponents = `
  alert
  footer
  header
  hero
  nav
  paginate
  sharebar
`;

module.exports = {
  context: namesToIds(exposedComponents)
};

/**
 * Return an object like { "component-name": "@component-name" }
 * When used in the "context", Fractal will replace every "@component-name" string
 * with the component's context.
 * @param {string} nameString
 * @returns {object}
 */
function namesToIds(nameString) {
  const obj = {};
  for (let name of nameString.trim().split(/\s+/)) {
    obj[name.replace('--','') + 'Context'] = "@" + name;
  }
  return obj;
}
```

and in the page templates we can do things like:

```twig
{# components/page/something/something.twig #}
{% include '@hero' with heroContext %}
{% include '@alert' with alertContext %}
{% include '@paginate' with paginateContext %}
etc.
```
