### ISSUE TITLE
How to process raw component JS for previews

### ISSUE THREAD

**Issue by zawilliams** [frctl/fractal#375]
I was including a JS file for specific components with the suggestion here: https://github.com/frctl/fractal/issues/93#issuecomment-236429871

I realize this imports the raw JS and I'm writing some ES6 with some imports, etc. Is there any way to process the raw JS files for component previews?

I realize I could just glob component JS into an app.js file and include it in the preview template, but I am mainly using the component JS files for examples. For example, I might include a selectize.js component and style it, then include an an example.js file that imports jQuery and selectize.js and then I setup the selectize options for the component preview - but I wouldn't include that code in a an a build file. It would only be used for the styleguide preview and that specific component.

**Comment by 7iomka** [comment]
Also interested in this issue.
The only thing that can be done now, and then with a big desire,
it's for the component to set its preview: '@ my-component-prev'
This is a dirty solution, considering how many components can be on the project (for example, to take a button component, it may have variations that should be shown in combination with other components - that is, write test styles that are not needed in the assembly, but for demonstration - solutions...)
