### ISSUE TITLE
Fractal not loading css, getting 404

### ISSUE THREAD

**Issue by phaniwithu** [frctl/fractal#377]
Hi,

We are trying to evaluate Fractal to show our demos.

I  am facing an issue where we are able to see the component but not its css.   Below is my Fractal.js config.  I am not using Handlebars. 
```
/* Create a new Fractal instance and export it for use elsewhere if required */
const fractal = module.exports = require('@frctl/fractal').create();

/* Set the title of the project */
fractal.set('project.title', 'FooCorp Component Library');

/* Tell Fractal where the components will live */
fractal.components.set('path', __dirname + '/components');

fractal.components.set('ext', '.html');
```

Below is one of my components HTML file located in folder `Components/componentname/abc.html`

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../../dist/mdc-button/mdc-button.css">
</head>
<body>
<button class="mdc-button">
    Baseline
</button>
</body>
</html>
```

I am seeing the error 404 for mdc-button.css which is in dist folder.
I am able to see the component but not its CSS.
How can I load the css files that are in component templates.

Should I mention anything in the configuration.

**Comment by dkhuntrods** [comment]
Hi @phaniwithu, can you confirm that you've let Fractal know the location of your assets?

From here:
https://fractal.build/guide/project-settings#example-project-setup-file

Specifically:
```
/* Specify a directory of static assets */
fractal.web.set('static.path', __dirname + '/public');

/* Set the static HTML build destination */
fractal.web.set('builder.dest', __dirname + '/build');
```
