### ISSUE TITLE
Why does the view file have to be named the same as the directory?

### ISSUE THREAD

**Issue by zackphilipps** [frctl/fractal#378]
Per [this section of the docs](https://fractal.build/guide/components/creating#associating-related-files), the view file of a component has to be named the same as its directory in order to enjoy the awesome benefits of the assets tab and putting notes inside a `README.md`. But whyyyyyyyyy? D':

We've been using Fractal with this component structure for a while now...

```tree
modules/
├── organisms/
│   └── example/
│   │   ├── module-example.config.yml
│   │   ├── module-example.js
│   │   ├── module-example.scss
│   │   └── module-example.twig
```

...and just now discovered this. Not sure which would be more work at this point: we rename all of our files, or edit Fractal core functionality to just look for the `.twig` file regardless of its name. What do you think @allmarkedup ?

**Comment by dkhuntrods** [comment]
@zackphilipps you should be able to override the name in the component's config: https://fractal.build/guide/components/configuration#name
Still not ideal, but better than renaming *all* your files! :)

**Comment by zackphilipps** [comment]
@dkhuntrods that did not work. D':
