### ISSUE TITLE
Themes for entire pattern libraries?

### ISSUE THREAD

**Issue by nsteiner** [frctl/fractal#379]
I think this is a feature request, unless there's a way to do this already that I'm missing. I'd like to be able to demo all the same components in my pattern lib, but with different "themes" (different css/js references, but same markup).

Thanks in advance to anyone who can point me in the right direction on how to do this currently!

**Comment by zawilliams** [comment]
@nsteiner - one way you can do this is with different previews outlined here: https://fractal.build/guide/components/preview-layouts

So essentially you'd have your build process build out your two different themes, create two different preview handlebars templates (one with theme #1 css, and #2 with theme #2 css) and call them from your components .config.js file like this:

```
// component.config.json
{
    "preview": "@preview--theme-one"
}
```

**Comment by nsteiner** [comment]
@zawilliams thanks so much for the quick response. Am I understanding correctly that I'd need to duplicate the components to associate a different preview for each theme?

**Comment by zawilliams** [comment]
@nsteiner no prob. No, you don't need to duplicate the components to associate a different preview.

Within your component's *.config.json file (or .yml or .js), you can define a preview template for variants like so:

```json
{
	"context": {
		"label": "Button"
	},
	"variants": [
		{
			"preview": "@preview--theme-two",
			"name": "tiny"
		}
	]
}
```

You would define your default preview template in your `fractal.js` file:

```js
fractal.components.set('default.preview', '@preview--theme-one');
```

**Comment by nsteiner** [comment]
@zawilliams this is perfect! Thanks so much.

**Comment by zawilliams** [comment]
@nsteiner no prob!
