### ISSUE TITLE
Pass context to _preview file

### ISSUE THREAD

**Issue by leonsaysHi** [frctl/fractal#380]
I am trying to pass a context to a `_preview.hbs` [like it is described in the documentation](https://fractal.build/guide/components/preview-layouts#context-in-preview-layouts) :

```
|-- Components
     |-- _preview.hbs
     |-- components.config.json
          |-- 01-My-sub-component1
               |-- ...
          |-- 02-My-sub-component2
               |-- ...
```

`components.config.json`: `{ "context": { "message": "preview context message here" } }`
`_preview.hbs` : `{{ message }} {{{ yield }}}`

But it does not work. Any advice ?

Thanks,

**Comment by tlenex** [comment]
previews in fractal are just special components that are injected as root for other components via `{{{ yield }}}`, but still they are components. According to this, you could create file `Components/preview.config.json` with:
```json
{
  "context": {
    "message": "preview context message here"
  }
}
```

Give it a try.

**Comment by leonsaysHi** [comment]
Thanks for your answer. 
I've simplified my case and tried your suggestion : 
`
|-- Components
     |-- _preview.hbs 
     |-- preview.config.json
     |-- test.hbs
`

_preview.hbs: 
`message:
<pre>{{ message }}</pre>
<br> yield:
<pre>{{{ yield }}}</pre>`

preview.config.json:
`{
  "context": {
    "message": "preview context message here"
  }
}`

test.hbs:  `test yielded` 

But this only output: 
`
