### ISSUE TITLE
there is no component styles under documentation

### ISSUE THREAD

**Issue by taurni** [frctl/fractal#382]
Hi. I wold like to add some rendered component examples to my documentation page but there is no styles for that. 
Is there a way to set a default preview for docs as it is for components?:

fractal.components.set('default.preview', '@preview');

fractal.docs.set('default.preview', '@preview'); do not work.

Any other solutions?

**Comment by tlenex** [comment]
I think you can style docs using custom mandelbrot css files 
https://fractal.build/guide/web/default-theme#styles
