### ISSUE TITLE
Build get stuck on 13 of 14 items

### ISSUE THREAD

**Issue by mikaelkarlsson-se** [frctl/fractal#385]
Hi,
When I run the fractal build command, the build process gets stuck on "Exported 13 of 14 items". The export has got stuck in an endless loop, building/exporting over and over again generating sub folders in sub folders.
This happens only if the builder.dest folder starts with build. For example, ``__dirname + '/build/fractalstyleguide'`` will create an endless loop of exports into fractalstyleguide folders (sub folders in sub folders in subfolders..). Though, ``__dirname + '/fractalstyleguide'`` works as supposed, and also if build is later in the chain of folders.

The only other content in the build folder is a sub folder with some files, so I can't see any conflict happening.
I run the command via the Powershell terminal in Visual studio Code, Fractal v1.1.7 installed via NPM.

Any ideas what might cause this weird issue..?

**Comment by pmelab** [comment]
I'm having the same issue. To me it happens "often" but not always. Still trying to reproduce it properly.

**Comment by pmelab** [comment]
Okay, I was able to reproduce it. It was a `{{ dump() }}` statement (using twig).

**Comment by colourgarden** [comment]
@pmelab @mikaelkarlsson-se Was it an erroneous `dump()` within Fractal or an issue with authored components?
