### ISSUE TITLE
Error on with access to fractal-beta on windows 10

### ISSUE THREAD

**Issue by 7iomka** [frctl/fractal#387]
Hello friends!
I have installed latest beta version of fractal on windows 10;
Screenshot:
http://s1.micp.ru/zh5k4.png
When i try to access a fractal-beta i get an error:
`× **Octal escape sequences are not allowed in strict mode.**
  at Function (<anonymous>)
  at render (C:/Users/7iomka/AppData/Roaming/npm/node_modules/@frctl/cli/node_modules/@allmarkedup/climate/src/render.js:65:20)
  at log (C:/Users/7iomka/AppData/Roaming/npm/node_modules/@frctl/cli/node_modules/@frctl/console/src/log.js:7:15)
  at Object.handler (C:/Users/7iomka/AppData/Roaming/npm/node_modules/@frctl/cli/bin/fractal:129:11)
  at <anonymous>`

At the same time, when I create a new project with command fractal-beta new v2 (for example) i see that the fractal works,
http://s1.micp.ru/GsyN5.png
After that I want to run the inspector
but I get the same error
http://s3.micp.ru/FiOF0.png

Help me please;
I want to completely rewrite the existing project using fractal2!

**Comment by allmarkedup** [comment]
@7iomka Thanks for the report, I'll look into it.

Please think carefully before rewriting your whole project using the v2 beta - this is the first beta release and there may be some significant breaking changes before the first full release candidate is ready. You may need to spend quite a while updating between beta releases so you may want to hold off a bit until it's stabilised a bit :-)

**Comment by allmarkedup** [comment]
@7iomka can you just confirm what version of Node you are using please? .

**Comment by 7iomka** [comment]
@allmarkedup, after I read in the documentation that I need to use the version above 7, I went to the site https://nodejs.org/en/ and downloaded the version 8.8.1

**Comment by 7iomka** [comment]
As well as the last time, I'm not lucky with the fact that I'm facing a task, the solution of which is almost realized, but there is not enough time.
I'm interested in the 2nd version, because:
I'm using custom build (based on https://github.com/24ways/frontend)
and I divided my components like this:
common - common components (small and small)
partials - like a small containers (header, footer, aside) for all other components and custom user stuff
sections - sections of the site that differ from partials in that they are intended for private use (for example, the section "About Us" or "Reviews")

**templates** - site templates, is the largest container that includes all sections.

Accordingly, when I have the task of creating a Landing that has a header, footer and 5 sections that use common components such as "button, section-title, responsive-img etc ..", I create these 5 sections using custom fractal commands gui, and connect all these sections in the desired order in the template.

At the moment, I did not have a standard project.
Originally planned to do 3 lending
http://srv.group/
http://trading.srv.group/
http://mining.srv.group/

And then came the idea to expand the project to a multi-page site. To build each of the pages, I used a separate assembly based on fractal.
And now in front of me is the task of integrating all the pages within the framework of 1 assembly, because the client does not want internal pages to be on subdomains.
However, I am experiencing a number of problems, because of the limitations of the assembly itself:
1 - You can not use a component with the same name within an environment, just as you can not make nested components. This imposes strict limitations. For a multi-page project structure slightly changes.
In the "sections" folder, a folder is created that would somehow intuitively be associated with the name of the template, to which the sections in it reside.
I.e
```
sections / home / about-us / ...
templates / home-template / ...
```

And it becomes painful when we have a similarly intended section / component or page, and we, instead of doing so
```
sections / pageX / about-us / ...
templates / pageX-template / ...
```

are forced to do so
```
sections / pageX / about-us-X / ...
templates / pageX-template / ...
```
That is, always to control the uniqueness of the component name to the whole environment.

2 - By the examples above, you see that the components in the templates folder have the form XXX-template - I did this for the custom gulp-task, which instead of the classic build, took only the templates and rendered them.
But this is inconvenient, and I need to constantly rename after the production-assembly files
```
about-template.html -> about.html
```
And there is no way to make a local namespace so that the assembly distinguishes 
```
common / about, 
sections / home / about,
templates / about
```

I looked at version 2 and saw that the logic of the fractal operation had changed radically, because at first I wanted to try how it works, but I did not succeed.
I'm very used to fractal. I've been doing projects with him for 1 year, and so far I can not move on to something else, although I understand that there are many shortcomings that do not allow me to make my work comfortable.
I'm glad that you are developing and making progress, but if you could help me how to find a temporary solution to my problems in version 1.x, I would be glad.
Or at least give guidance when you can roughly try the 2nd version in production.
Thanks!

**Comment by risker** [comment]
Closing since v2 is probably not happening, at least not in the near future. We'll reopen if circumstances change and this is still relevant.
