### ISSUE TITLE
Razor view adapter 

### ISSUE THREAD

**Issue by nickdunn** [frctl/fractal#388]
From time to time I have to create templates that will be integrated into ASP.NET projects with CMS like Sitecore or Episerver. Rather than getting the CMS to render handlebars (a big challenge) I'm exploring writing a Razor (https://docs.microsoft.com/en-us/aspnet/web-pages/overview/getting-started/introducing-razor-syntax-c) adapter for Fractal. Now that .NET core will run on a Mac (https://www.microsoft.com/net/core#macos) I think an integration is within reach.

My current thought is to write a small command line app (.NET core) that accepts a template string and a data model and returns HTML (e.g. http://www.codemag.com/article/1312081). The Razor adapter would simply shell out to this.

Are you aware of any Fractal integrations with other templating engines beyond Handlebars and what Consolidate offers that could be used as a reference?

**Comment by mattsalmon** [comment]
I'd be interested in whether you've gotten any further with that @nickdunn - seems like a good idea for Microsoft based shops who want to use fractal.

**Comment by nickdunn** [comment]
I didn't get a chance, and the project need has since subsided. But I'm sure it will keep coming back with .NET CMS projects that don't currently have a component library architecture. There are big projects out there in the Sitecore/Episerver/Umbraco space where Fractal could become the go-to tool if we can solve the Razor integration.

**Comment by AlbertoLeon** [comment]
> I didn't get a chance, and the project need has since subsided. But I'm sure it will keep coming back with .NET CMS projects that don't currently have a component library architecture. There are big projects out there in the Sitecore/Episerver/Umbraco space where Fractal could become the go-to tool if we can solve the Razor integration.

Sounds a super idea. In fack, I think it is necessary to lead Sitecore one step ahead on front-end
