### ISSUE TITLE
Fractal V2 - Page Builder

### ISSUE THREAD

**Issue by ossvn** [frctl/fractal#390]
Hello,

I just knew that Fractal V2 have a feature called "page builder", using the component that can be drag - drop to create a complete template.

I tried the fractal-demo but it seems that page builder feature is not there yet, right?

Do we have a timeline that I can expect?

Also, I have 2 other questions:

- Can I have the global component and project component?
- With page builder and export to HTML, can I modify the folder structure, class, prefix...?
- Currently, Fractal-demo is the main commandline, but it's v2 already, so, in the mean time waiting for your page builder, I will prepare the components, when v2 stable released, I just need to update and the CLI will turn to "fractal", in stead of "fractal-demo"?

Thank you!

**Comment by allmarkedup** [comment]
Hi @ossvn - I think there has been some confusion here! I'm afraid that Fractal v2 doesn't include a drag-and-drop interface of any sort. It _is_ something that could be build on top of the core v2 engine but is not on the roadmap at the moment.

The Fractal 'Pages' extension is a static site builder (somewhat similar to [Jekyll](https://jekyllrb.com/)) and this _is_ implemented in the beta release, although it's still missing some functionality.

Regarding global/project components - I'm not quite clear on what you mean here. Can you give me a little more detail or an example?

When the v2 release is ready, the binary executable will indeed be renamed from `fractal-beta` to `fractal`. So You will just need to update the CLI to the stable version and you should be ready to go.

Just a heads up, there is still a lot of work to do on v2 (especially around documentation!) and it may feature breaking changes still so please be cautious when using it for anything other than experimentation for the time being.

**Comment by ossvn** [comment]
Hello @allmarkedup 

Thank you for your reply Mark, I will answer one by one so you can keep them in track

1/ For drag-drop interface, I mean, can I use "Pages" extension, to make a template from my component by either drag-drop or anyway like that?

I tried to use v2 but without the documentation so I can't imagine the function or how to use it.

And it would be great, if you can show me the documentation for how to use "pages" extension? Or do you think a drag-drop component to a specific template is a great idea, at the moment, any way that I can achieve that, like the custom extension or the other app that can connect to Fractal's component and build it separately?

2/ For the global/project component, it's like, there's a pool of component with tag, if the component tagged with "global", then I can access it anywhere, else, project only available inside that project. Something like that.

Thnak you for your patient!

Andrew
