### ISSUE TITLE
How to keep Fractal running after I close my SSH

### ISSUE THREAD

**Issue by ossvn** [frctl/fractal#391]
Hello,

It's me again, I'm really newbie to Nodejs, and want to know how to keep the Fractal running, after I close my terminal? (I'm using CLI by the way).

This is what I tried:

- nohup npm start &
- cd /home/internal-docx
- fractal
- start
- close the terminal

Then I tried with the url:3000, it didn't work, so can you please help me out or point me a method to keep it running?

Thank you!

**Comment by sabsaxo** [comment]
Not sure, but maybe this will help?

https://stackoverflow.com/questions/26568135/keep-alive-express-process-after-close-the-terminal

**Comment by ossvn** [comment]
Hi @sabsaxo 

I have tried, using:

- nohup npm start &

But didn't work, any other suggestion please, pleaseeeee!

**Comment by tlenex** [comment]
Why not to build your fractal and serve only static filles?

If that's not the case, try:
https://www.npmjs.com/package/pm2

**Comment by VolleMelk** [comment]
Why you would want this, is beyond me. But you could take a look at `screen`. Install it using your package manager (or compile from source). Start a new screen session using `screen`. This will give you a new shell. Start fractal and then detach your screen using CTRL + A and D (https://askubuntu.com/questions/124897/how-do-i-detach-a-screen-session-from-a-terminal)

You will now return to the initial terminal, which you can exit as usual. Your process will remain alive inside the screen session.

If you wish to re-attach to the screensession, use `screen -r`.

But then again, you really don't want this. Besides, this is out of scope for this repository
