### ISSUE TITLE
Bundle helpers not working correctly for dynamic documentation

### ISSUE THREAD

**Issue by deporter** [frctl/fractal#392]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
When using the following syntax in the docs:
```
{{view @button}}
```
and 
```
{{context @button}}
```
My alert component code is shown instead of button. I can only get alert to show via this code in any of the docs. I believe this might be because it is alphabetically the first component in my list.

**If the current behaviour is a bug, please provide the steps to reproduce.**

1. Create a fractal project
2. Create two components
3. In docs try and render component using syntax provided above.

**What is the expected behaviour?**
When using a component handle in docs with the view and context helpers the details should show for the component specified.

**Please mention your Node.js & Fractal version and the operating system you are using.**
Fractal 1.1.7, NodeJS 8.1.3, MacOS 10.12.6

**Comment by dkhuntrods** [comment]
Hi @deporter apologies, this is an issue in the docs (which I'll look at updating asap).
The name of the component needs to be a string - ie {{ context '@button' }}
