### ISSUE TITLE
preview working with nunjucks

### ISSUE THREAD

**Issue by trickydisco78** [frctl/fractal#394]
I'm getting a blank page when using {{yeild}} using the nunjucks renderer in components.

I know the example is using handlebars {{{ yield }}

How do i get the content to show in my preview pane?

**Comment by JulianMar** [comment]
maybe try to write {{ yield }} not {{ yeild }}

**Comment by trickydisco78** [comment]
Oh my god.. i'm such a dufus!!!!!

**Comment by JulianMar** [comment]
Happy to help :)

**Comment by trickydisco78** [comment]
thanks :)
