### ISSUE TITLE
Code unformatted when aXe extension enabled in Chrome

### ISSUE THREAD

**Issue by maya** [frctl/fractal#397]
See: https://github.com/18F/web-design-standards/issues/2273

**Comment by jaasum** [comment]
I noticed this too, but it's no longer occurring for me. Guessing aXe or Chrome got an update that fixed it.

**Comment by maya** [comment]
Great to hear, closing this out.

**Comment by AstiV** [comment]
For the record: Issue returned :(

But great to have found the ticket, so I just gonna wait for their next update that hopefully fixes it ^^
