### ISSUE TITLE
Browsersync watchOptions.ignored doesn't seem to work

### ISSUE THREAD

**Issue by garytokyo** [frctl/fractal#398]
I am trying to get css injection working so as not to cause a browser refresh. So I am trying to ignore all files in my src folder so the browser isn't forced to refresh but I cannot get it to work. I have tried a few different ways but this is my current config for the syncOptions:

```
fractal.web.set('server.syncOptions', {
  injectChanges: true,
  files: ['public/**/*.css', 'src/components/**/*.twig', 'public/**/*.js'],
  watchOptions: {
    ignoreInitial: true,
    ignored: /^\/src\/.*[\/].*$/i,
  },
});
```

As far as I can tell none of those settings are actually doing anything. I am not sure if this is a bug or I am doing something wrong...

Does my config look correct?

**Comment by guschilds** [comment]
I had this issue as well. I then came across https://github.com/frctl/fractal/issues/134 and was able to get it working by wrapping my paths in `path.resolve()` (thanks to https://github.com/frctl/fractal/issues/134#issuecomment-365666401). I wasn't using a regex pattern like the example above, but I think if you want to ignore all of `src` you could use `path.resolve('src/**/*')`. Hope this helps!
