### ISSUE TITLE
Upload styleguide to subfolder

### ISSUE THREAD

**Issue by risker** [frctl/fractal#40]
I'd like to upload the built styleguide to a subfolder on my server (instead of having to make a subdomain for every demo) Is there a way to configurate the web UI plugin or fractal to make the URLs relative instead of absolute?

**Comment by sturobson** [comment]
I'd like this too. I've looked at using some .htaccess redirects on @allmarkedup's suggestion but haven't got it working perfectly yet. 

Doing this each time could be laborious though. It'd be great if we could add something into `fractal.js` that on `fractal build` would 'insert' the subfolder where appropriately 

fractal.set('build.relativePath', 'patterns');

or something and `/patterns` gets injected as needed.

**Comment by allmarkedup** [comment]
Yep this sounds like a pretty common use case so I'll have a look at this today and see if I can get something in place.

The tricky thing however will be what to do with absolute paths in asset CSS files. Fractal basically copies the contents of the static assets  directory into the build directory. That means that absolute URLs (i.e. for bg images) in the CSS may not resolve correctly if the build directory is placed in a subdirectory.

I'll have a think about how to mitigate this, but just being able to prefix the path URLs in the build will definitely be a good first step.

**Comment by allmarkedup** [comment]
@risker @sturobson I've implemented this now in the latest release of the web UI plugin/theme. You can set the desired build root path in your fractal.js file like this:

```js
fractal.set('plugins.web.build.root', 'foobar');
```

All generated paths will then be prefixed with `/foobar` - e.g. `/foobar/components/example`.

If you are linking to assets in your public directory (stylesheets, images etc) using absolute URLs anywhere you'll probably need to change them to use relative paths as these will not be rewritten in any way.

@sturobson - there are a few changes to the Mandelbrot theme that I made to support this, so if you are using a forked version you'll need to pull in changes from the upstream repo. If you didn't for it then this compare view should outline the changes I made: https://github.com/frctl/mandelbrot/compare/6b09c95871aae898c6528291b9adf0dd8ad541a5...b88046d21b01c75879d85440de5896404c815b97

If anything isn't working or you have any questions please let me know! Cheers.

**Comment by sturobson** [comment]
Hi Mark - just a thought - does this work dev environments? My use case would be having the component ibrary in a folder `/patterns/` for an 'overview' of all the things available and then using them within the `root` or `dev` folder when creating pages from it. Does that make sense? Is it possible?

**Comment by sturobson** [comment]
I've now managed to test this on a server and it works perfectly.

**Comment by allmarkedup** [comment]
Ok great. I'm going to go ahead and close this now then.
