### ISSUE TITLE
passing NODE_ENV to view templates

### ISSUE THREAD

**Issue by trickydisco78** [frctl/fractal#401]
Hi.. wondering how i pass NODE_ENV settings to the template.

What i want to do is pass this env to the view template in the preview file

if it's development then link to /css/ locally.. But if it;s using fratal build then i want the address to be my CDN URL

https://cdn.assets/css/style.min.css

presumably i set a global?

**Comment by kolin4** [comment]
im getting same problem. I wanted to add conditionaly gaTag and sentry script when only node_env is production.. but it seems to be imposible to read node_env variables in overided theme/views
