### ISSUE TITLE
V2 beta available anywhere?

### ISSUE THREAD

**Issue by sabsaxo** [frctl/fractal#402]
Any idea when a V2 beta is available?

**Comment by tlenex** [comment]
https://github.com/frctl/fractal/tree/v2 it is available

**Comment by sabsaxo** [comment]
Thanks, and any idea when an RC is available (can't seem to find any info in the various read me's)? Just in the need of component library of sorts at the moment, and wondering whether I should wait for this to be closer to a release.

**Comment by simondib** [comment]
Yep keen to know how v2 is tracking also! v1 has been hugely helpful for our team.
