### ISSUE TITLE
add nunjucks filter to theme

### ISSUE THREAD

**Issue by scottnath** [frctl/fractal#403]
Hi team,

Is it possible to add a nunjucks filter for use in the mandelbrot theme via configuration in the main `fractal.js` file?
Or...is it possible to add filters in a `theme-overrides` directory which was detailed in the [Template customization section](https://fractal.build/guide/web/default-theme)?

If neither of those is there another way...or is my only option to create a copy of mandelbrot and make changes in my copy?

thank you,
Scott

**Comment by plumpNation** [comment]
I also am looking at this.

We could set the engine the same way that we set it on docs and components.

```
const nunj = require('@frctl/nunjucks')({filters: { ... }});

fractal.web.engine(nunj);
```

Does anyone agree with this approach?
