### ISSUE TITLE
Ignore index.html in /public static assets folder

### ISSUE THREAD

**Issue by JulianMullins** [frctl/fractal#407]
I have setup my static assets directory to the following:
`fractal.web.set('static.path', __dirname + '/public');`

In this public folder is an index.html file and when I start the web UI, the fractal overview/documentation page is replaced by this index.html page (I am still able to access the rest of my pattern library).

I have verified that this is the issue by deleting the index.html page and relaunching the fractal web UI; the docs loaded without error. However, I need this index.html page for use by the rest of my application so I can't simply delete it each time I want to run the web UI.

How can I resolve this issue? Is there a way to give the fractal documentation overview precedence over this index.html page?

**Comment by Sylphony** [comment]
Why does the application rely on the location of where the docs are?  The docs should be separate from the components.  That's why there are two types of Fractal config props: `fractal.components` and `fractal.docs`.

**Comment by JulianMullins** [comment]
My docs are separated from the components though. Here's my fractal folder structure:

app
-fractal
-- docs
-- scss (components folder)

fractal.js

And within fractal.js I have the location of both the docs and components set as normal:

```javascript
/* Tell Fractal where the components will live */
fractal.components.set('path', __dirname + '/app/fractal/scss');

/* Tell Fractal where the documentation pages will live */
fractal.docs.set('path', __dirname + '/app/fractal/docs');
```

**Comment by JulianMullins** [comment]
When I remove the line:

```javascript
/* Tell Fractal where the static assets live */
fractal.web.set('static.path', __dirname + '/public');
```
and relaunch the fractal server, everything loads fine, except then the component styles aren't applied because they don't have access to my compiled css files in the public folder...

**Comment by Sylphony** [comment]
You have this issue because `index.html` should not be located at the root of the static asset folder; `index.html` should be located at the root of the docs folder.

To have the compiled CSS file be usable in the docs and components views requires a different method for each one.

For components, you need to include the file inside your `_preview.html` which lets you load assets into the iframe.  The [docs](https://fractal.build/guide/components/preview-layouts) provide an example to doing that; the key is using `{{ path '/build.css' }}`, where `path` is the location of the static asset directory.

For docs, you need to include it inside the Fractal config when you set the theme.  e.g.

```js
fractal.web.theme(mandelbrot({
  styles: ["default", "/build.css"],
}));
```


In the end, your directory structure should look something more like this:

```
+--app
|  +-- fractal
|      +-- docs
|          +-- index.html
|      +-- scss
|      +-- static
|          +-- build.css
```

**Comment by JulianMullins** [comment]
I'm (mostly) setup the way you're recommending. Here's a more detailed view of my current folder structure so I can explain the issue better.

```
+-- app
|  +-- fractal
|      +-- docs
|          +-- index.md
|      +-- scss
|          +-- demos
|          +-- layoutrules
|          +-- modulerules
|          +-- preview.hbs
|          +-- styles.scss

+--public
|  +-- app.css
|  +-- app.js
|  +-- index.html

+-- fractal.js
```

And here's the contents of `fractal.js`:

```javascript
'use strict';

/* Create a new Fractal instance and export it for use elsewhere if required */
const fractal = module.exports = require('@frctl/fractal').create();

/* Tell Fractal where the components will live */
fractal.components.set('path', __dirname + '/app/fractal/scss');

/* Tell Fractal where the documentation pages will live */
fractal.docs.set('path', __dirname + '/app/fractal/docs');

// /* Tell Fractal where the static assets live */
fractal.web.set('static.path', __dirname + '/public');

/* Tell Fractal the default preview wrapper to use */
fractal.components.set('default.preview', '@preview');

/* Tell Fractal where to build the static directory */
fractal.web.set('builder.dest', __dirname + '/componentlibrary');

//use BrowserSync when the server is started
fractal.web.set('server.sync', true);
```

My preview.hbs file:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ _target.label }} | TripRiff Component Library</title>
    <link rel="stylesheet" href="{{ path '/app.css' }}">
  </head>
  <body>
    <div id="app">
      {{{ yield }}}
    </div>
    <script src="{{ path '/vendor.js' }}"></script>
    <script src="{{ path '/app.js' }}"></script>
    <script>require('index');</script>
  </body>
</html>

```

I'm using [brunch.io](http://brunch.io/) for my build tasks and the public folder is what gets generated when I `npm start`. This folder gets placed at the root directory, rather than within my fractal folder. However, I don't think this is an issue since I'm pointing fractal to this folder with my static assets declaration in `fractal.js`

My `index.md` file located in the fractal docs folder is the file I want fractal to use for the documentation view. This file is different from the `index.html` file found in the `/public` folder.

When I `fractal start` and view the web UI locally, the server loads the `index.html` page rather than the `index.md` page that I had specified fractal to use for the documentation. I can still view the components that I've created by visiting the url (e.g. `localhost:3000/components/detail/button`) but I'm unable to view the actual docs page because this has been replaced by index.html.

The fractal components load the static assets correctly from within the public folder. I'm just having trouble with the documentation page...

When I deleted `index.html` from the public folder and relaunched the fractal server, I was able to see the docs and components exactly as I'd expect. However, manually deleting the `index.html` file every time I want to launch the fractal server obviously isn't a viable solution.

Hopefully this helps clarify the issue a bit more. I can't seem to figure out what I'm missing/why fractal would prioritize the `index.html` file over `index.md`...

**Comment by Sylphony** [comment]
I have no clue why Fractal fails to render anything when it finds `index.html` inside the root of the static path.  It's probably an implementation thing they did.

The best thing you can do is to just create a separate folder outside of `public`, copy the build files over to that folder and then config Fractal to use that path.  There are many tools out there that can automatically do that as part of the build process.

**Comment by JulianMullins** [comment]
Yeah that sounds like the right way to deal with this, barring any input from the fractal team on the matter. Thanks so much for the help @Sylphony!
