### ISSUE TITLE
Error at the end of a CLI build

### ISSUE THREAD

**Issue by mindplay-dk** [frctl/fractal#408]
At the end of a successful build, I get an error message:

```
$ npm run build

> @ build /mnt/c/workspace/test/admin_ui/styleguide
> rm -rf ../assets/styleguide && fractal build

✔ Build started...
⚑ Exported 187 of 187 items
✘ Error copying '/mnt/c/workspace/test/admin_ui/assets' ==> '../assets/styleguide'
‼︎ Build finished with 1 error.
```

The output in the `styleguide` folder works just fine, and it says it completed "187 of 187 items", which presumable is all of them, so this is a bit baffling.

My `fractal.js` looks as follows:

```js
const fractal = require('@frctl/fractal');

const project = fractal.create();

project.set('project.version', 'v0.2');
project.set('project.title', 'AdminUI styleguide');

project.components.set('default.status', 'wip');
project.components.set('path', 'components');

project.docs.set('path', 'docs');

project.web.set('static.path', '../assets');
project.web.set('builder.dest', '../assets/styleguide');

module.exports = project;
```

Based on the paths I've configured, it appears it's trying to copy from `static.path` to `builder.dest`, which in this case isn't possible, because one is a subfolder of the other.

According to the manual section on [project settings](https://fractal.build/guide/project-settings):

> ### Configuring the web UI
> #### Web UI configuration is done using the fractal.web.set() method.
> 
> To serve a directory of static assets via the web UI (so that you can link to stylesheets from your preview layouts, for example), you can specify the path to the directory using the static.path setting

I took this to mean that the configuration setting is for the web UI - and I do want the `watch` command to serve static assets (images and CSS) from the assets folder, but apparently the build command also attempts to copy the contents of this folder?

Is there any way to switch off this feature?

Note that changing my folder structure is not an option, as our conventions and framework requires each module to place all public assets in the `assets` folder - the styleguide is just one set of public assets, others include CSS (from SASS) and images etc., which must be accessible to the styleguide.

**Comment by Fcog** [comment]
I had the same issue, and I fixed it by moving the styleguide's build folder from the assets folder.
