### ISSUE TITLE
Known security vulnerabilities detected on Github

### ISSUE THREAD

**Issue by frazerf** [frctl/fractal#410]
Hi there, 

I'm getting an alert from Github saying there's a security vulnerability in fractal in the 'marked' dependency. It's saying to upgrade to ~> 0.3.9. Is there a way I can do this? 

Thanks

**Comment by LeBenLeBen** [comment]
You can install the latest version of marked in your own project as an usual dependency and it will take precedence on the one required by Fractal until they update it.
