### ISSUE TITLE
Setting NODE_ENV to "development" throws a warning when loading a component page

### ISSUE THREAD

**Issue by Sylphony** [frctl/fractal#412]
I use [cross-env](https://www.npmjs.com/package/cross-env) which allows a cross-OS compatible way to set NODE_ENV.  If I set it to development and load a components page, I get the following warning:

```
Warning: a promise was created in a handler at eval at _compile (path\to\node_modules\nunjucks\src\environment.js:565:24), <anonymous>:28:1 but was not returned from it, see http://goo.gle/rRaMUw
    at ret (eval at makeNodePromisifieEval(path\to\node_modules\bluebird\js\release\promisify.js:1:0), <anonymous>:8:21
```

**Comment by tobystokes** [comment]
If you set node to run in development mode, you get more warnings, for the developers. 

If you just want to set an environment variable that you can use for your own use in config, then I found it better to use a different variable, like ENV, as per #442

**Comment by LeBenLeBen** [comment]
See #235 to disable Bluebird warnings
