### ISSUE TITLE
Logger causes issues when used with Gulp 4

### ISSUE THREAD

**Issue by emilbjorklund** [frctl/fractal#416]
Using Fractal 1.1.7

I've had a weird issue with Gulp complaining about tasks not finishing correctly, which I finally narrowed down to this line in my gulpfile:
```
const logger = fractal.cli.console;
```
When removing that statement, the problems go away.

From what I can see, there have been a couple of issues with Vorpal & async stuff previously (e.g. #245), so I suspect there is something going on there – not sure exactly what, but it seems something is convincing gulp that there are async tasks still running as long as the logger is used.

I've put up a [minimal test case as a GitHub repo](https://github.com/emilbjorklund/gulptest-fractallogger), with a gulpfile, fractal file and a couple of fake tasks.

**Comment by hhsl** [comment]
Faced the same issue with gulp4. Fixed it by replacing `const logger = fractal.cli.console;` with:
`const logger = require('fancy-log');`
