### ISSUE TITLE
Fractal Crashes and doesn't recover automatically when using BrowserSync

### ISSUE THREAD

**Issue by jamesf-deeson** [frctl/fractal#417]
**Setup:**
In our scenario we are using BrowserSync in tandem with a separate Webpack process, having Webpack compile our assets continuously and Fractal display them.  The command that we're using to kick this process off is ```fractal start --sync & webpack --watch```

**Problem:**
If we make a syntax error, which we do most commonly in our Fractal component config files (`component.config.js`) then Fractal will throw an error, eg:

```
✘ Error parsing data file /Users/james/repositories/components/03-components/promo/promo.config.js: SyntaxError: Unexpected token {
✘ SyntaxError: Unexpected token {
```

Unfortunately Fractal doesn't automatically recover from this when we do fix the syntax issue, which means stopping and restarting build process for the project, which is frustrating.  Webpack in contrast has no issues, and will happily detect that the files have changed and successfully recompile when the syntax is correct.

Is there some change that we can make to our build process to be more reliable, or some feature we're missing with Fractal which provides a better experience when using the `--sync` flag?

**Comment by guschilds** [comment]
I've had the same issue on a couple of projects and for what it's worth, I think Webpack is unrelated.

**To reproduce:**

1. Start the Fractal server (whether with the `fractal` CLI or a Gulp command) with `sync` enabled.
2. Verify that valid changes to a `component.config.js` file is properly reflected when the page refreshes.
3. Introduce a JS syntax error into the `component.config.js` file and save it. From here, the console will log an error like the one in the issue description.

**Expected result:** After fixing the error and saving the file, Fractal continues to read from the file and if it is valid, any changes to the data are reflected in the browser.

**Actual result:** After fixing the error and saving the file, Fractal does not read from it again. The browser refreshes, but any valid changes are not reflected in the browser. To continue working, the Fractal server must be restarted before it will continue reading valid changes within the file. This can be frustrating and burn a lot of time.

---

A co-worker and I were able to trace the issue to a `Promise.reject()` call within `src/core/data.js`. As soon as that is called, changes to that file (valid or not) will no longer be read. Unfortunately I'm not familiar enough with the Fractal codebase, Node, Promises, etc. to find a solution that feels truly appropriate, but I was able to patch Fractal in a way that lets us know which file has an error without requiring the server to be updated. We're now using [`patch-package`](https://www.npmjs.com/package/patch-package) to create and install this patch:

```
patch-package
--- a/node_modules/@frctl/fractal/src/core/data.js
+++ b/node_modules/@frctl/fractal/src/core/data.js
@@ -62,7 +62,8 @@ module.exports = {
                 }
                 return Promise.resolve(data);
             } catch (e) {
-                return Promise.reject(e);
+                Log.error(`You've got an error in ${filePath.split('/')[filePath.split('/').length - 1]}`);
+                return Promise.resolve({});
             }
         } else {
             return fs.readFileAsync(filePath, 'utf8').then(contents => this.parse(contents, format)).catch(err => {
```

(A side effect of returning the empty object is that the component will disappear entirely from the UI until the file is fixed, but that's also actually a bit helpful if you're familiar with why it's happening.)

I'm including the patch to hopefully help others get around this issue until it is resolved and to help the maintainers reproduce the problem and find a more appropriate solution. Maintainers: let me know if I can help in any other way - and I appreciate your work on this project!

**Comment by dkhuntrods** [comment]
Thanks @guschilds, that is really helpful.

**Comment by sun** [comment]
We also noticed this with simple mistakes in Faker/dummy data generation code in .config.js files.

The suggested patch by @guschilds actually sounds like a very good solution. Do you want to create a PR?

**Comment by Chapabu** [comment]
@sun @guschilds If one of you could submit a PR that would be greatly appreciated, if not I'll try and get onto it this week at some point 👍

**Comment by guschilds** [comment]
Thanks @sun and @Chapabu,

I just created a PR here: https://github.com/frctl/fractal/pull/509. Let me know if you need any help with it or would like to see anything different. Thanks again!
