### ISSUE TITLE
'fractal new project-name' not generating anything

### ISSUE THREAD

**Issue by Steviant** [frctl/fractal#42]
Hi, this looks like a great project, but so far I'm getting no output from the `fractal new` command. I've tried reinstalling Fractal globally and it hasn't made any difference. Am I missing something? I've copypasted my Terminal output below.

```
 10:41:44  ...code/planetary/fractaltests  ⬡ system 
👉 fractal new project-test

⚑ Creating new project.... just a few questions:

? What's the title of your project? Project Test
? Where would you like to keep your components? components
? Where would you like to keep your docs? docs
? What would you like to call your public directory? public
? Will you use Git for version control on this project? Yes

 10:42:01  ...code/planetary/fractaltests  ⬡ system 
👉 ll

 10:42:03  ...code/planetary/fractaltests  ⬡ system 
👉
```

Any help much appreciated!

**Comment by allmarkedup** [comment]
Nope you are not missing anything - that looks like a bug that must have crept in when I updated the dependency that handles the prompt-style questions. I'll look into it now! Thanks for the bug report :-)

**Comment by allmarkedup** [comment]
@Steviant - I've just released a new version (v0.10.7) that should fix the issue - please let me know if you still have any problems!

**Comment by Steviant** [comment]
Wow, from bug report to fixed in half an hour, good job! Worked straight away, thanks for your help!

**Comment by allmarkedup** [comment]
You just caught me at a good time :-) Glad it's working for you now though - I'll mark this as closed.
