### ISSUE TITLE
Ideas for scaffolding / refactoring

### ISSUE THREAD

**Issue by nqthqn** [frctl/fractal#420]
I built this tool called [sancho](https://www.npmjs.com/package/@nqthqn/sancho) for scaffolding and refactoring fractal components. I realize folks likely do things wildly different; though some workflows might be shared — like a command for deeply renaming a module.

This is more of a call for ideas than a feature request. 

**Related Issues**
 - https://github.com/frctl/fractal/issues/197 
 - https://github.com/frctl/fractal/issues/390
 - https://github.com/frctl/fractal/issues/84

**Comment by upstroke** [comment]
Hi nqthqn
Your repro is missing some more information how to use it. Other than that great idea.

**Comment by nqthqn** [comment]
@upstroke what would you like to know? you run the command `sancho` with flags and names and it outputs code in directories or modifies code in directories. Here is some example usage: https://asciinema.org/a/7nKXOBGvWFPEincrJKPnZQl9y

**Comment by upstroke** [comment]
Thx, got it.
