### ISSUE TITLE
Multiple subcomponents of a same type

### ISSUE THREAD

**Issue by patrikniebur** [frctl/fractal#425]
Hey, 
Thanks for a great tool! Hopefully I'll get to give back and contribute.

Is there a way to include multiple subcomponents of a same type and and provide different context values for them separately?

Thanks

**Comment by nategreen** [comment]
Yes: https://fractal.build/guide/components/variants

**Comment by nategreen** [comment]
Ah. Do you mean something like one of these? (Assuming you're using Handlebars...)

```handlebars
{{> @button thisButton }}
{{> @button--inverted thatButton }}
```

```handlebars
{{#each buttons }}
  {{#if this.inverted }}
    {{> @button--inverted label=this.label}}
  {{ else }}
    {{> @button label=this.label }}
  {{/if }}
{{/each }}
```

Is that what you're getting at? How to provide a specific property as context?

**Comment by patrikniebur** [comment]
Yes, or providing context in supporting config.yml file like:  

```
context:
  button:
    text: Login
  button--inverted:
    text: Sign up
```
