### ISSUE TITLE
fractal:build ends up recursively copying onto itself

### ISSUE THREAD

**Issue by lsmith77** [frctl/fractal#429]
I have `static-export` set as the `builder.dest`. When I run `fractal:build` I then end up with recursive directory structure where I have `static-export` inside `static-export` inside `static-export` etc.

I guess when copying the `builder.dest` path should be ignored and currently isn't?

In the same spirit it would be nice to be able to exclude certain files and directories but that would just be a nice to have.

**Comment by mikaelkarlsson-se** [comment]
Hi,
I have the same issue: https://github.com/frctl/fractal/issues/385
Maybe the last answer can help you in some way.

**Comment by lsmith77** [comment]
So it seems to me like the fix is to manually set the ignore path:

```
    fractal.web.set('builder.dest', path.resolve(rootPath, "static-export"))
    fractal.web.set('builder.static.ignored', [path.resolve(rootPath, "static-export")])
```
