### ISSUE TITLE
Variants do not seem to work

### ISSUE THREAD

**Issue by jbatchelor** [frctl/fractal#431]
I've created a variants array in both the json and js formats, and neither of them seem to pass along the context data I send in, no matter how I name the variant. I have 

```
components
    buttons
        03-Default
             Default.config.js
             00-button-default.hbs
             _01-button-default--Icon-Only.hbs
```

Default.config.js:
```
module.exports = {
    title: "Default Button",
    context:{
        label:"Submit",
        class:"btn-default"
    },
    variants: [
        {
            name: "Icon-Label",
            context: {
                label: "Icon label"
            }
        }    
    ]
};
```

00-button-default.hbs and _01-button-default--Icon-Only.hbs are inheriting the context label from the top, but the context label from the Icon-Label is NOT being inherited by the _01-button-default--Icon-Only.hbs, even though your documentation indicates that I should be able to set config info for that item. Oh, also, virtual variants (variants that are specified in the config file but have no actual hbs file) do not work at all.

**Comment by LeBenLeBen** [comment]
I’m not sure prefixing a template with both a number and an underscore is supposed to work, that might be the problem for the file-defined variant. I recommend you to put the order in the config file, that will prevent you from renaming all files the day you want to change it.

Also I’ve never seen capitals inside Fractal file names, maybe also something worth to check. In the interface names are "humanized" anyway so you could keep them all lowercase.

Also I think your "button-default" and "button-default--Icon-Only" are supposed to be in a folder named "button-default". See https://fractal.build/guide/components/variants for details.

Finally, you should probably share your templates, that could help find what’s wrong.

**Comment by jbatchelor** [comment]
Thank you. I didn't see anything in the documentation in regard to case-sensitivity, but once I got everything changed over to lower-case, I was able to get the variants to work.
