### ISSUE TITLE
Fractal not being added to path

### ISSUE THREAD

**Issue by sitrobotsit** [frctl/fractal#433]
After running `npm i -g @frctl/fractal` in terminal, fractal is available in my path. I get `-bash: fractal: command not found` when running `fractal start --sync` or any other fractal command. 

The only warning I get when installing fractal is `npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)`

mac: 10.13.4
node: v8.9.4
npm: 5.6.0

**Comment by FedPete** [comment]
I use a workaround in the `package.json`
```json
  "scripts": {
    "start": "node ./node_modules/@frctl/fractal/bin/fractal start --sync",
    "build": "node ./node_modules/@frctl/fractal/bin/fractal build"
  },
````

**Comment by LeBenLeBen** [comment]
@sitrobotsit npm usually install global packages within `/usr/local/bin`. Is this folder part of your $PATH? You can run the following command to check:

```bash
echo $PATH | grep /usr/local/bin
```

Are you having the same issue with other global npm packages or only Fractal?

**Comment by Chapabu** [comment]
Closing this one until we get more info 💁‍♂️
