### ISSUE TITLE
Documenting Sass variables, mixins and functions

### ISSUE THREAD

**Issue by lawlesscreation** [frctl/fractal#434]
I want to try and document our Sass variables/mixins/functions and wondered if anyone had any suggestions of how to do this? I've tried:

1. Documenting them as components, but a component requires a `.hbs` file. I could create an empty file but then the documentation has a blank component in the preview. Perhaps my `config.json` file could have a value of `preview: false` which I could use in the theme to remove the preview - _but nobody likes empty files sitting around_.
2. Documenting them in the Docs section using `.md` files. The problem with this is Fractal only allows 1 path to be set for the docs location which means either splitting the documentation from the Sass or creating a task to bundle all documentation into one folder before running Fractal.

I thought about using SassDoc and getting Fractal to <iframe> in the SassDoc export but that seems a little messy.

So, I'm curious to know if anyone has done something similar or could suggest how best to document Sass?

**Comment by sattes-faction** [comment]
If your scss-files are within the components folders, you can add a new component tab with the raw scss files as content. In your `fractal.js` add this:

```
fractal.components.set('resources', {
  scss: {
    label: 'SCSS',
    match: ['**!/!*.scss']
  },
```

**Comment by lawlesscreation** [comment]
Thanks for the response @sattes-faction. That kind of works but you need to have a blank `.hbs` file otherwise it doesn't generate a component.

For now I've gone with the approach of creating a `.md` file for the Scss mixins then copying them to the `docs` folder when it runs a build so they appear as docs rather than components.

Either approach feels a little messy but the later felt better than creating blank `.hbs` just to trick Fractal into thinking they was a component when actually it's just some Scss mixins.

**Comment by sattes-faction** [comment]
I see, sorry - I misread your first part.

**Comment by mikaelkarlsson-se** [comment]
Hi!
I've managed to gather the variables in a specific scss file using a Handlebars helper which uses [sass-extract](https://github.com/jgranstrom/sass-extract), [https://github.com/jgranstrom/sass-extract-loader](sass-extract-loader) and [https://github.com/adamgruber/sass-extract-js](sass-extract-js) to gather and return the variables.
  
Helper:

````
const sassExtract = require('sass-extract')  
const createSassExtractJsPlugin = require('sass-extract-js/lib/plugin')  

const sassExtractJsPlugin = createSassExtractJsPlugin({ camelCase: false })  
const scssVariables = sassExtract.renderSync({  
    file: 'path/to/file.scss'  
}, {  
    plugins: [sassExtractJsPlugin]  
})  

fractal.docs.engine(hbs).handlebars.registerHelper('getSassVariables', () => {  
    const variables = []  
    // Note: sass-extract-js returns a object with the keys stats, css and vars and vars is the one needed.  
    Object.entries(scssVariables.vars).forEach(property => {  
        variables.push({  
            variable: property[0],  
            value: property[1]  
        })  
    })  
    return variables  
})  
````

_index.hbs (my documentation file located in components/docs):

````
<ul>
    {{#each (getSassVariables)}}
    <li>{{this.variable}} - {{this.value}}</li>
    {{/each}}
</ul>
````
  
I hope it can help you. :)

**Comment by lawlesscreation** [comment]
@mikaelkarlsson-se I'll take a look thanks!
