### ISSUE TITLE
fractal.build is down

### ISSUE THREAD

**Issue by finneganh** [frctl/fractal#436]
Visiting https://fractal.build/guide shows a billing error page.

**Comment by jbatchelor** [comment]
Just as I was winding up my first project with it and looking for the documentation on building the static css representation, too...

**Comment by bhenbe** [comment]
Yes, the website is down. I notice Clearleft on Twitter about it. Not sure it's the best place to do that but...

**Comment by adamlindqvist** [comment]
It's up again!💥

**Comment by tjnicolaides** [comment]
This is a little late, but in case something like this should ever happen again - the source for the docs site is here, with instructions to spin up a local server: https://github.com/frctl/fractal.build
