### ISSUE TITLE
Deprecation errors in Craft 3 that conflict with Fractal

### ISSUE THREAD

**Issue by mnimmz** [frctl/fractal#444]
I noticed some compatibility issues with Craft 3 and the Fractal plugin or just Fractal in general. In Craft 3, you cannot directly reference query, but instead you have to use the `.all()` filter. This clears the error in Craft but this filter is not recognized in Fractal because it is not a Twig filter, but is a Craft one. Also, in order to access the first item in a query, Craft 3 now uses the `.1()` filter, which is not a Twig filter, therefore Fractal does not recognize this either. Has anyone else had this issue, and if so did you find a solution or is there a plan for this to be corrected in Fractal?

**Comment by Chapabu** [comment]
I'm making a grand assumption here that you're using the [Twig adapter](https://github.com/frctl/twig). I'm not sure it should be the responsibility of the Twig adapter to have support for specific frameworks. However I do think it's a good idea to explore the ability to extend the Twig adapter and perhaps add some documentation.

I'm going to close this one off, as I'm sure it's referencing https://github.com/frctl/twig - if you wanted to continue the discussion or offer any suggestions please feel free to open an issue there :)
