### ISSUE TITLE
Can't figured out how to register handlebars-helper and other single helpers

### ISSUE THREAD

**Issue by micheloa** [frctl/fractal#450]
Hi,
I'm trying to register [handlebars-helper](https://github.com/helpers/handlebars-helpers/), [handlebars-helper-repeat](https://github.com/helpers/handlebars-helper-repeat) and a custom dump helper.

This is my last attempt:
```js
const extra_helpers = require('handlebars-helpers')();
const repeat = require('handlebars-helper-repeat');
const hbs = require('@frctl/handlebars')({
  helpers: {
    repeat,
    dump: function(str) {
              return JSON.stringify(str);
          },
    extra_helpers
  },
 
});
fractal.components.engine(hbs);
fractal.docs.engine(hbs);
```
The error thrown, when I try to use, for example, '{{#contains ...}}' is: 
```
ERROR RENDERING COMPONENT
Missing helper: "contains"
```

For me [handlebars-helper](https://github.com/helpers/handlebars-helper-repeat) works only alone defined like this:
```js
const helpers = require('handlebars-helpers')();
const hbs = require('@frctl/handlebars')({
  helpers
});
fractal.components.engine(hbs);
fractal.docs.engine(hbs);
```

Can you help me?

**Comment by ajilderda** [comment]
Hi @micheloa,

First things first. I see you have an extra `,` after your `helpers`-object. Does removing this fix it for you? If not, here's how I set up my Handlebars-helpers: 

```
const helpers = require('./handlebars-helpers')(fractal);

// Register Handlebars helpers
const Handlebars = require('@frctl/handlebars')(helpers);
fractal.components.engine(Handlebars);
fractal.docs.engine(Handlebars);

// Use the handlebars-layouts helpers
const layouts = require('handlebars-layouts');
const instance = fractal.components.engine();
layouts.register(instance.handlebars);
```

So what I did here is register some helpers that are in a seperate file and add handlebars-layouts into the mix with `.register()`. Does that help?

**Comment by Maybach91** [comment]
unfortunately the solution from @LeBenLeBen and @ajilderda are not working for me. i try this with https://www.npmjs.com/package/handlebars-helpers and https://www.npmjs.com/package/just-handlebars-helpers :/

**Comment by Maybach91** [comment]
hej @LeBenLeBen ,

thanks for your help! i restarted it of course but i got an error on my page, thats its not able to export the url:
```
✘ Failed to export url /components/detail/atom-button--default - (/src/resources/fractal/themes/medi/views/pages/components/detail.nunj)
  Template render error: (/src/resources/fractal/themes/themeName/views/partials/pen/browser.nunj)
  Template render error: (/src/resources/fractal/themes/themeName/views/partials/browser/browser.nunj)
  Template render error: (/src/resources/fractal/themes/themeName/views/partials/browser/panel-notes.nunj) [Line 5, Column 40]
```
(this error occur only when i try to use handlebar helpers, which are not there. so the panel-notes.nunj is fine)

my config:
```
    "@frctl/fractal": "^1.1.7",
    "handlebars-helpers": "^0.10.0",
    "handlebars-layouts": "^3.1.4",
```
_______
```

const fractal = module.exports = require('@frctl/fractal').create();
const extraHelpers = require('handlebars-helpers')(fractal); // https://www.npmjs.com/package/handlebars-helpers

const hbs = require('@frctl/handlebars')({
  helpers: {
    splitName(stringName) {
      const t = stringName.split(' / ');
      return t[0];
    },
    ...extraHelpers,
  },
});

fractal.docs.set('engine', hbs);

fractal.docs.set('path', `${cfg.src.base}docs`);
```
the variable extraHelpers is defined with all the functions
