### ISSUE TITLE
Component Notes are not displayed

### ISSUE THREAD

**Issue by Maybach91** [frctl/fractal#451]
No matter if i set the notes via the config file (json/yaml) or an added README.md file within the component folder. In the built Fractal no notes are shown at all. It displays always `There are no notes for this item.`

Same like #145 i guess

**Comment by dkhuntrods** [comment]
Hi @Maybach91 can you try adding it in lowercase, so `readme.md` rather than `README.md`?

**Comment by marchdoe** [comment]
@Maybach91 - I am working on something related to the README.md file right now (trying to set it up locally so it doesn't have to be named README). However, I didn't have any problems setting it up (or the other way of leveraging `"notes":`.

I am wondering if this is a weird environment/config issue. When you have some time do you mind sharing your config?

**Comment by Maybach91** [comment]
Okay, still open. Because when i change the ext via the config to ".html", then no readme.html will be rendered as readme/documentation.
