### ISSUE TITLE
`bundle error` on `require` when using Karma

### ISSUE THREAD

**Issue by scottnath** [frctl/fractal#452]
Hi fractal team!

We're using fractal's components to create a set of urls which get fed into karma to do integration tests. When we try to add fractal (via `const fractal = require('@frctl/fractal');`) to any file used by karma we get:

```
19 07 2018 13:55:56.823:ERROR [framework.browserify]: bundle error
19 07 2018 13:55:56.826:ERROR [framework.browserify]: Error: Cannot find module 'bubleify' from '/Users/meowmeowmeow/development/gitrepos/meowmeow/node_modules/is-number-like'
19 07 2018 13:55:56.925:ERROR [framework.browserify]: bundle error
19 07 2018 13:55:56.925:ERROR [framework.browserify]: Error: Cannot find module 'utf-8-validate' from '/Users/meowmeowmeow/development/gitrepos/meowmeow/node_modules/ws/lib'
19 07 2018 13:55:56.925:ERROR [framework.browserify]: bundle error
19 07 2018 13:55:56.925:ERROR [framework.browserify]: Error: Cannot find module 'bufferutil' from '/Users/meowmeowmeow/development/gitrepos/meowmeow/node_modules/ws/lib'
19 07 2018 13:55:56.934:ERROR [framework.browserify]: bundle error
19 07 2018 13:55:56.934:ERROR [framework.browserify]: Error: Cannot find module 'browser-sync/lib/server/utils' from '/Users/meowmeowmeow/development/gitrepos/meowmeow/node_modules/browser-sync-ui/lib/plugins/network-throttle'
```

I have traced this to `src/web/server.js`: `syncServer.init` (https://github.com/frctl/fractal/blob/master/src/web/server.js#L183)

I don't have a workaround. We had to use fractal in a separate, non-karma process to create a `json` file to pull the urls from.

cheers,
scott

**Comment by scottnath** [comment]
bump

**Comment by dkhuntrods** [comment]
Hi Scott, can you possibly create a reduced test-case repo for us to investigate? Without a bit more context it's tricky to track down. Thank you!

**Comment by LeBenLeBen** [comment]
@scottnath It seems you're using the "watch" server mode which use BrowserSync to automatically watch for file changes and reload the browser. I guess this is not necessary in your context. Have you tried to run the server in default mode, without the watch flag?
