### ISSUE TITLE
https://fractal.build/ is down; Payment required

### ISSUE THREAD

**Issue by weenzeel** [frctl/fractal#453]
Hi,

As of 2 august 2018, the website seems to have gone down.
Gets a payment required message.

Thanks.

**Comment by tomdavies** [comment]
Hey @weenzeel, thanks for reporting this. The lead maintainer for Fractal is on vacation this week and we're still in the middle of onboarding new maintainers (like me). I've contacted some other people at Clearleft to see if we can get this sorted, but it may take a little while to sort out.

In the meantime, while it's not ideal if the docs being down is blocking you, you can access all of the docs in Markdown format via [the repo for fractal.build here](https://github.com/frctl/fractal.build/tree/master/docs)

For anyone else following this issue - please bear with us and have no fear, Fractal is alive and well. We've had really strong interest from the community in getting involved with the maintenance and future development of the project.

**Comment by allmarkedup** [comment]
@weenzeel @tomdavies This should be fixed now :-) The slack signup page is still down however but I'll hopefully get that sorted shortly.

**Comment by weenzeel** [comment]
Great! Thanks for sorting this out so quickly :)

**Comment by exside** [comment]
I can not access the project settings page here:

https://fractal.build/guide/project-settings

it will show an error:

```
(/Users/mark/Projects/frctl/v1/fractal.build/theme/views/page.nunj) Template render error: (unknown path) [Line 2, Column 7] Error: marked(): input parameter is of type [object Object], string expected
```

**Comment by Chapabu** [comment]
@allmarkedup @dkhuntrods Was this one fully resolved?

**Comment by allmarkedup** [comment]
@Chapabu Yep this should all be sorted now. Closing the issue :-)
