### ISSUE TITLE
Readme Files for Variants

### ISSUE THREAD

**Issue by Maybach91** [frctl/fractal#454]
Is there any way to create Readme Files for Component Variants?

Like this Plugin https://github.com/Itrulia/fractal-variant-readme is doing it for V2. I’m looking for a solution for the V1.

readme-variant.md
or readme--variant.md does not work.

**Comment by Maybach91** [comment]
noooooo please dont close it @stale! :D

**Comment by LeBenLeBen** [comment]
@Maybach91 It looks like this is indeed not possible in version 1 at the moment. Let's see if we can add this feature in an upcoming version. Meanwhile you can use the `notes` key of the variant within the config file.

**Comment by risker** [comment]
This was recently implemented in #566 .
