### ISSUE TITLE
YAML's date type is incorrectly parsed by Fractal

### ISSUE THREAD

**Issue by querkmachine** [frctl/fractal#455]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Fractal Documentation for information about your issue: https://fractal.build/guide
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Afrctl

### Description

Sorry if this is a duplicate or I've missed something obvious, my Google-fu has failed me thus far.

When given a piece of context data containing an ISO formatted date, Fractal seems to return an empty object instead of the context data. I'm assuming this is because ISO 8601 format timestamps are considered a basic type in YAML and Fractal doesn't know how to parse them into a JavaScript equivalent. 

### Steps to Reproduce

Create a component with YAML-formatted context data including an ISO timestamp. For example:

```
context:
  updated: 2018-08-15
```

In the component, try rendering the context data with `{{ updated }}`. For me this is returning the string `[object Object]`.

Dumping the data with `{{ updated | dump }}` returns an empty object: `{}`. 

I've had the same result with other ISO timestamps such as `2018-08-15 17:13:00` and `2018-08-15 17:13:00+01:00`. Currently I can bypass this behaviour by quoting the timestamp, turning it into a string. 

Ideally the context data would be returned as a string, if not an object with date information. I'm also using the [Nunjucks adaptor](https://github.com/frctl/nunjucks), though I wouldn't expect that to be changing how the data is interpreted, just how it's templated (you know what they say about assumptions, though!) 

### Versions

Fractal version: 1.1.7
Node version: 10.4.0

**Comment by marchdoe** [comment]
@querkmachine - Thanks for the great write-up!

I went in and recreated the issue

```
context:
  updated: 2018-08-15
```
and was able to solve it locally with

```
context:
  updated: "2018-08-15"
```

I don't have a lot of familiarity of the inner workings of how YAML/Fractal works so am not sure if this is a 100% solution.

**Comment by querkmachine** [comment]
Yeah, making it into a string is how I've been dealing with it. I'd just consider normal YAML dates returning nothing to be unexpected (and dare I say, *buggy!*) behaviour.
