### ISSUE TITLE
Update v1 dependencies and address any security issues

### ISSUE THREAD

**Issue by dkhuntrods** [frctl/fractal#456]
- [x] Update packages with security issues
  - [x] Mocha (growl) HIGH
  - [x] Vorpal HIGH
  - [x] ShellJS HIGH
  - [x] debug LOW 
  - [x] lodash LOW
- [x] Update all packages to latest versions possible.
- [x] Fix any resulting issues.
- [ ] Apply any remaining Snyk patches (if still applicable)

**Comment by dkhuntrods** [comment]
Mocha (growl) and vorpal:  #461

**Comment by dkhuntrods** [comment]
ShellJS #458

**Comment by Chapabu** [comment]
@dkhuntrods I've just gone to look at the remaining packages, and unfortunately they're dependencies of packages that have no fixes in the latest releases.

I think we can _probably_ ignore them for now. The Lodash advisory is a dependency of Vorpal, and the Debug advisory is a dependency of Browser Sync, both of which are only used during development so they aren't really attack vectors at all unless someone is running the Fractal server in production (hopefully this never happens).

Checking them for now, Snyk and Greenkeeper will let us know when we can fix them,

**Comment by Chapabu** [comment]
Update remaining packages/fix remaining issues: #468

**Comment by Chapabu** [comment]
Snyk patches are all being applied or are being actioned in other ways, so closing this one off :)
