### ISSUE TITLE
Launch 2 instances of Fractal at the same time

### ISSUE THREAD

**Issue by gaetanmarsault** [frctl/fractal#463]
Hi,
I'ld like to know if it possible to launch 2 instances of Fractal at the same time ?
I've this project : 

-- fractal1
&nbsp;&nbsp;&nbsp;-- components
&nbsp;&nbsp;&nbsp;-- docs
-- fractal2
&nbsp;&nbsp;&nbsp;-- components
&nbsp;&nbsp;&nbsp;-- docs
-- fractal.js

How to launch fractal1 and fractal2 simultaneously, with for example : 
http://localhost:3333 (for fractal1) and http://localhost:4444 (for fractal2)

Thanks for your help !

**Comment by dkhuntrods** [comment]
Hi @gaetanmarsault, 
Thanks for your interest in Fractal! 

In general, we try to keep our github issue focussed on bugs and security, but to get you moving in the right direction, I'd say you will need to have two separate config files that each live under their `fractal1`/`fractal2` directory. Then you can specify the port in the config, and start each one concurrently using an `npm` script command. 

If you need any more assistance, there's a great community at [Fractal Slack](https://slack.fractal.build/) - I'm @dkhuntrods on there - with loads of experience in pretty much every configuration you can image!
