### ISSUE TITLE
Empty HTML panel

### ISSUE THREAD

**Issue by supermueller** [frctl/fractal#464]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Fractal Documentation for information about your issue: https://fractal.build/guide
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Afrctl

### Description

If the notes panel is on first position and is not empty, then the HTML panel shows no content.

### Steps to Reproduce

1. Rearrange the panels in `fractal.js`

```js
const mandelbrot = require('@frctl/mandelbrot');

const myCustomisedTheme = mandelbrot({
    panels: [
        "notes", "html",
    ],
});

fractal.web.theme(myCustomisedTheme);
```
2. Start Fractal web UI server

3. Add a Note to a component by adding a file `readme.md` with some content.

4. The HTML code disappears in the HTML panel.

**UPDATE:** The HTML panel is only empty, if the component view includes another component by using the render helper, e.g.: 

```
<div class="this-component">
    {{render '@another-component' }}
</div>
``` 

**Expected behavior:**

The HTML panel should still show the HTML code.

**Actual behavior:**

The HTML panel doesn’t show the HTML code.

**Reproduces how often:**

100%

### Versions

* What version of Fractal are you running? (run `npm list @frctl/fractal` / `yarn list @frctl/fractal`

```bash
└─┬ @frctl/fractal@1.1.7 
  ├─┬ @frctl/handlebars@1.1.4
  │ └── @frctl/fractal@1.1.7  deduped
  └─┬ @frctl/mandelbrot@1.2.0
    └── @frctl/fractal@1.1.7  deduped
```

* What version of Node.js are you running? (run `node -v`)

```bash
v8.11.3
```

**Comment by dkhuntrods** [comment]
Thanks @supermueller - I suspect this is a Mandelbrot (Fractal theme, rather than Fractal itself) issue, but we'll look into it.

**Comment by pdreij** [comment]
Having the same problem, can be temporary solved by moving "notes" panel after "html".

**Comment by LeBenLeBen** [comment]
Potentially related to https://github.com/frctl/nunjucks/issues/5

**Comment by LeBenLeBen** [comment]
@supermueller On my side, the HTML panel is empty only if the component includes another one with the `render` helper. Can you confirm you have the same behavior?

This is definitely related to https://github.com/frctl/nunjucks/issues/5 for me since commenting out the circular markdown renderer reference fixes the issue. The Handlebars adapter also use `JSON.stringify` (https://github.com/frctl/handlebars/blob/master/src/helpers/render.js#L35) but for some reasons fails silently while Nunjucks throws.

**Comment by supermueller** [comment]
@LeBenLeBen You are right: When the component includes a render helper the HTML panel will be empty.

**Comment by Chapabu** [comment]
Closing based on above PR.
