### ISSUE TITLE
Status dot is not really visible

### ISSUE THREAD

**Issue by MKlblangenois** [frctl/fractal#475]
Hello !

When I define statut for my components, I got a white dot with a simple border on this.
But, why the dot is in white ? Can we set the same color for the background-color ?

Thanks

**Comment by LeBenLeBen** [comment]
Hey @MKlblangenois,

The style of the dot is defined in https://github.com/frctl/mandelbrot, which is Fractal's default theme. You are free to customize it, for example by loading a custom CSS file that would override the dot style. Check out https://fractal.build/guide/web/default-theme.html for more information, especially the "styles" section.

If you'd have any other question, I'd recommend you to join us on Slack (https://slack.fractal.build/).

🖖 

/cc @ajilderda, as you might want to take this feedback into account for the next design iteration.
