### ISSUE TITLE
Build failed with API Context data (async call with promise)

### ISSUE THREAD

**Issue by bhenbe** [frctl/fractal#476]
If you tried to get API Context Data regarding the documentation (https://fractal.build/guide/core-concepts/context-data.html#dynamic-data), the build call doesn't work properly. No more pages are build. 

To reproduce it, you can use this example: 

1. you have to install promises (https://github.com/request/request-promise)
2. you have to create a js config file with this code (for example):

```js
'use strict';

const request = require('request-promise'); // require the request-promise module

// make the request to the API, returns a Promise
var options = {
    uri: 'https://jsonplaceholder.typicode.com/photos?_start=0&_limit=20',
    json: true // Automatically parses the JSON string in the response
};

// do some post-processing on the response to wrangle it into the correct format
var response = request(options).then(function (testApiData) {
    const testData = [];
    for (let test of testApiData) {
        testData.push({
            title: test.title,
            url: test.url
        });
    }
    return testData;
}).catch(function (err) {
    console.log(err);
});

module.exports = {
    title: "Post card",
    status: "ready",
    default: "default",
	context: {
		posts: response // use the response as context data for our template.
	}
};
```

3. launch fractal build 

Expected behavior: having a view of a list containing 20 items (my api call ask for 20 items in this example)

Actual behavior: the build only works on pages and assets but stop before building components so the fractal documentation is empty (no more components listed)

Reproduces how often: always with promises config vars

* What version of Fractal are you running? 1.1.7
* What version of Node.js are you running? 10.0.0

Additional Information

No additional information to add, i think.

**Comment by fohlin** [comment]
@bhenbe: What does `fractal` output when building? Any errors?

**Comment by LeBenLeBen** [comment]
I've experienced similar behavior with `*.config.js` files. When the file produces an error Fractal fails silently and no components files are generated. I suggest you to wrap the whole file into a `try...catch` block and log the error you get in the catch to get more information.

**Comment by bhenbe** [comment]
It's seems that the returned type is the problem.

1. In my example, response is an object and the build fails.
2. If i try posts: response.testData, it returns a null value.
3. If i set the testData array outside the request object, the context tab show me the testData array datas but the html tab is empty when i launch the fractal start command. I think that the problem is about the asynchronous call and that the contact tab is filled in after the build of the html documentation.

**Comment by bhenbe** [comment]
@LeBenLeBen i tried your solution to catch more informations but nothing (more) happens.
