### ISSUE TITLE
parent config file is included within a child component that has it's own config file

### ISSUE THREAD

**Issue by sturobson** [frctl/fractal#48]
I have a group of components - hoff-hair, hoff-shades, hoff-tan that are in a parent folder hoff
I have a hoff.config.yml that has overall data for all of the child components 
If I create a separate config file for hoff-hair - hoff-hair.config.yml this gets outputted in the context data followed by the data within hoff.config.yml

Is there a way to tell the component when it's 'all by itself' to only use the config.yml file that's within the folder?

**Comment by allmarkedup** [comment]
@sturobson yes that is correct - any context data set in parent collections is **merged** with any context data set in downstream child components. The docs on configuration files (hopefully) explain it better than I can here: https://github.com/frctl/fractal/blob/master/docs/configuration-files.md#configuration-inheritance

There is currently no way to say 'include parent collection data in this component but not in this one'. But I'll have a think about how it could be implemented :-)
