### ISSUE TITLE
Change highlight.js style

### ISSUE THREAD

**Issue by Niekes** [frctl/fractal#484]
Is there a easy way to change the `highlight.js` theme?

I can do:

```js
const myCustomisedTheme = mandelbrot({
    ...
    styles: ['default', 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/styles/atom-one-dark.min.css']
});
```
But I this will not affect the background in the `div.FileBrowser` element.

**Comment by risker** [comment]
It seems that we don't add the `hljs` class anywhere, which seems like a bug.

Probably needs changes in mandelbrot too.
