### ISSUE TITLE
Feature request: Expose browserSync server instance

### ISSUE THREAD

**Issue by justrhysism** [frctl/fractal#501]
Currently it's impossible to implement hot reloading features such as what is described in [BrowserSync's docs](https://www.browsersync.io/docs/gulp#gulp-sass-css) as it requires access to the `syncServer` object which is currently contained within `_startSync` in `server.js`.

We _could_ switch to compile Webpack but there are good reasons we don't (particularly around build speed). Also, I believe Fractal should be _independent_ of Webpack to allow greater flexibility and longevity of the project.

**Comment by Marvin1003** [comment]
You can extend the BrowserSync configuration in your ``fractal.js``
```js
fractal.web.set("server.syncOptions", {
  // example
  https: true
});
```

**Comment by justrhysism** [comment]
You have misunderstood my question. I think the title is missing a keyword and people haven’t bothered reading the description. I will update it.

**Comment by baerkins** [comment]
I have a similar want for this (at least, I think it's similar).

I have a gulp file that is used on multiple CMS projects that include Fractal. The gulp file runs several tasks on files inside and outside of the Fractal file path, and spins up a browsersync instance for the CMS, as well as the Fractal server. I can trigger reloads of the CMS browsersync instance when some tasks complete, but I can't get the Fractal server instance to reload. 

I know that you can configure multiple options in `server.syncOptions`, and configure what files the Fractal instance will watch, but it would be ideal if I could trigger a reload of it when needed.

Ideally, there would be a way to expose the Fractal browsersync instance, so in gulp I could run something similar to:

```
const fractalServer = fractal.web.server({
  sync: true
});

gulp.task('fractal-serve', function(done){
	return fractalServer.start();
});

// Trigger a reload of the fractalServer browsersync instance
// as per the BS API (https://www.browsersync.io/docs/api)
gulp.task('fractal-reload', () => {
	fractalServer.reload();
});
```

Dunno how doable it is, but thought I would chime in with a use case.

Cheers
Shaun

**Comment by baerkins** [comment]
Just to tack on here, the Browsersync API has a `create` method to make a named server instance, which can then be retrieved in other files: https://browsersync.io/docs/api#api-get

Not sure if this is helpful or relevant to the existing codebase. I could kick the tires and make a PR if anything comes out of it?

**Comment by Chapabu** [comment]
I'm not 100% sure if the linked issue _actually_ closes this one. If not, please feel free to re-open this issue.

**Comment by justrhysism** [comment]
Will investigate and report back if it solves the issue.
