### ISSUE TITLE
Feature Request: Build path rewrite configuration

### ISSUE THREAD

**Issue by jwir3** [frctl/fractal#502]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Fractal Documentation for information about your issue: https://fractal.build/guide
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Afrctl

### Description

I use Rails for our production website. Currently, I hand-copy the mustache templates from our design system (fractal) to the production application, but I use the generated .css from `fractal build`. Since mustache doesn't run on my final `.css` files, I have to hard-code any visual assets I want in CSS as `../../dist/images/*`.

What I'd like to do is add something like the following to the `fractal.js` file:
```
const context = {
  package: {
    name: pkg.name,
    version: pkg.version,
    path: '../../dist',
    rewritePathOnBuild: 'assets'
  },
};
```

When I then run `fractal build`, it will replace all instances of `../../dist/*.*` with `assets/*.*`. This will enable (in my case) it to use the Rails asset pipeline.

### Versions

* What version of Fractal are you running? (run `npm list @frctl/fractal` / `yarn list @frctl/fractal`
```
─┬ @frctl/fractal@1.1.7
│ └─┬ @frctl/mandelbrot@1.2.0
│   └── @frctl/fractal@1.1.7  deduped
└─┬ @frctl/mustache@1.0.0
  └── @frctl/fractal@1.1.7  deduped
```
* What version of Node.js are you running? (run `node -v`)
```
v8.15.0
```

**Comment by risker** [comment]
Fractal has nothing to do with CSS generation so this is at least currently out of scope for this project.
