### ISSUE TITLE
Missing line breaks in code blocks in Markdown files

### ISSUE THREAD

**Issue by supermueller** [frctl/fractal#517]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Fractal Documentation for information about your issue: https://fractal.build/guide
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Afrctl

### Description

Line breaks will be removed from code blocks in Markdown files (e.g. components readme or documentation files).

### Steps to Reproduce

1. Open documentations index file (`/docs/index.md`).
2. Append a code block using the Markdown syntax (the spaces at the start of each line are only added to prevent Githubs Markdown parser to render the backtickles in the example):

```
    This is a code example in the documentations index file:

    ```
    line 1;
    line 2;
    ```
```
3. Save and check the rendered index page in the browser.

**Expected behavior:** [What you expect to happen]

The code should be displayed with line breaks.

Correct source code for displaying the code with line breaks:

```
<pre>
    line <span class="hljs-number">1</span><span class="hljs-comment">;</span>
    line <span class="hljs-number">2</span><span class="hljs-comment">;</span>
</pre>
```

**Actual behavior:** [What actually happens]

The line breaks beeing removed.

Source code of the actual behaviour:

```
<pre>
    <code>
        line <span class="hljs-number">1</span><span class="hljs-comment">;</span>
        line <span class="hljs-number">2</span><span class="hljs-comment">;</span> 
   </code>
</pre>
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

* What version of Fractal are you running? (run `npm list @frctl/fractal` / `yarn list @frctl/fractal`
* What version of Node.js are you running? (run `node -v`)

@frctl/fractal@1.2.0
@frctl/mandelbrot@1.2.1

Node: v11.7.0

**Comment by vwfs-sasmoe** [comment]
Seems like this is the result of an update of the `marked` package. We expierence a lot of similar issues since an update to `@frctl/fractal@1.2.0`.

**Comment by Chapabu** [comment]
`1.2.0` seems to have had a couple of issues. Unfortunately, the test coverage of Fractal in general isn't great - although it's something we're aware of.

The linked issue suggests that manually adding the latest Mandelbrot to your project will resolve the issue. Might be worth giving that a try until I get time to look at the core dependency.

**Comment by LeBenLeBen** [comment]
This is probably fixed by https://github.com/frctl/mandelbrot/pull/79 which has been merged in Mandelbrot yesterday and should be released early next week.
