### ISSUE TITLE
Slack Workspace invite link not working

### ISSUE THREAD

**Issue by AstiV** [frctl/fractal#525]
Have you read Fractal's [Code of Conduct](/.github/CODE_OF_CONDUCT.md)? By filing an Issue, you are expected to comply with it, including treating everyone with respect

Do you want to ask a question? Are you looking for support? The Fractal Slack channel is the best place for getting support: https://fractalize.slack.com

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Fractal Documentation for information about your issue: https://fractal.build/guide
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Afrctl

### Description

Thanks for providing this great tool! We're considering to use it for our pattern library implementation at work, soon.

I have tried to access the fractal workspace on slack, using the invite link in the documentation
(https://fractal.build/guide/).
Unfortunately, it does not seem to be active (that's what the error message communicates, at least). 

The link above, provided by the issue template is only useful if one's already invited to the workspace and owns an account.

Is there any new source for support? 

Best wishes :)

**Comment by Chapabu** [comment]
How weird. The Slack workspace is active on https://fractalize.slack.com. I don't really know how workspace sharing works. I don't suppose you could grab a screenshot of the error could you? I can't replicate it (probably because I'm a member already).

**Comment by Konafets** [comment]
It says, that the link is not active anymore.

![Screenshot 2019-11-08 at 13 04 22](https://user-images.githubusercontent.com/363363/68475473-81ed9580-0228-11ea-8d55-e60199c8fdf8.png)

**Comment by AstiV** [comment]
@Chapabu thanks for your reply and looking into the problem.
The link you are referring to: (https://fractalize.slack.com) leads to the following screen, that requires a person to already have an account for the workspace:
![Bildschirmfoto 2019-11-08 um 14 24 10](https://user-images.githubusercontent.com/15826773/68479872-ac911b80-0233-11ea-8344-5ea2e1cbc38c.png)

The screen @Konafets is referring to is reached by the link on the first page of the documentation (https://slack.fractal.build/).

Slack shares their info on how to invite guests to workspaces here: https://slack.com/help/articles/201330256-invite-new-members-to-your-workspace

Here's a screenshot of their explanation on how to share an invite link:
![image](https://user-images.githubusercontent.com/15826773/68480086-3b059d00-0234-11ea-8608-a221374553f6.png)

**Comment by Chapabu** [comment]
This...is...amazing! Really useful!

Good news and bad news time. The bad news is that I don't have access to update this link (I think that would need to be @allmarkedup or @dkhuntrods).

The good news, is that if you can get an e-mail address to me, then I should be able to send a manual invite for the time being. I think the best way would probably be via DM on Twitter (https://twitter.com/Chapabu). My e-mail address is also on my profile, but I can't guarantee if it'll get through as I have a fair few filters on there (and don't check that one regularly).

**Comment by Chapabu** [comment]
Looking forward, I've assigned this one to Mark and/or Danielle to either generate a new link, or perhaps appoint another workspace owner who can do it in their absence :)

**Comment by AstiV** [comment]
> The good news, is that if you can get an e-mail address to me, then I should be able to send a manual invite for the time being. I think the best way would probably be via DM on Twitter (https://twitter.com/Chapabu). My e-mail address is also on my profile, but I can't guarantee if it'll get through as I have a fair few filters on there (and don't check that one regularly).

Well @Chapabu, the good news is good enough 👍 :)
I've just DMed you on Twitter, as suggested, thanks a lot for your help!!

**Comment by LeBenLeBen** [comment]
Maintainers are currently working on an alternate support solution, a decision should be made in the following days.

**Comment by LeBenLeBen** [comment]
Please join us on our brand new [Discord server](https://discord.gg/vuRz4Yx) from now on.
