### ISSUE TITLE
Import external libraries

### ISSUE THREAD

**Issue by Konafets** [frctl/fractal#529]
Hello,

I would like to ask how I can import external libraries which I like to use within a component later on. In my case I want to use https://github.com/pixijs/pixi.js.

Can you give me a pointer in the right direction?

**Comment by LeBenLeBen** [comment]
The common way is to create a custom preview layout to have control on the HTML document used within the preview iframe. This way you can import all the assets you need with the standard link and script tags.

See the docs about [creating a preview layout](https://fractal.build/guide/components/preview-layouts.html#creating-a-preview-layout).
