### ISSUE TITLE
Quick Start Stuck

### ISSUE THREAD

**Issue by stephenway** [frctl/fractal#53]
![image](https://cloud.githubusercontent.com/assets/38894/14962465/c0e8f8ee-1053-11e6-93b0-1d039f00d1c6.png)

This is what I get when I try getting started.

**Comment by allmarkedup** [comment]
@stephenway that should only happen if you try and create a new Fractal project within a directory that contains an existing `fractal.js` file (i.e. you can't create a Fractal project within another one). Can you check whether that is the case when you are seeing this message? Otherwise it's a bug!

**Comment by stephenway** [comment]
Nope this was first run.

**Comment by allmarkedup** [comment]
Sorry @stephenway, I can't recreate this here :-( Is there anything else in the `~/code/fractal directory` when you try and run the command? Does it work if you try and run it in a different location?

**Comment by stephenway** [comment]
This consistently happens on the latest version in new folders
