### ISSUE TITLE
Code blocks are not styled correctly

### ISSUE THREAD

**Issue by jwir3** [frctl/fractal#532]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Fractal Documentation for information about your issue: https://fractal.build/guide
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Afrctl

### Description

Code blocks are not rendered correctly.

### Steps to Reproduce

1. Create a markdown file in src/docs with a code block, similar to the following (note that ''' is used in place of the backtick, since I'm writing in github):

```
'''html
<script src="../../dist/js/<Library-Name>.js" type="text/javascript"></script>
<script>
  function initialize() {
    <Library-Name>.show();
  }

  $(document).ready(function() {
    initialize();
  });
</script>

<div style="max-width: 600px" id="content" />
'''
```

2. Load fractal using `yarn start`.
3. Navigate to the created markdown document.

**Expected behavior:** It should render the code block as an actual block, similar to:
![Screenshot from 2019-11-12 14-29-46](https://user-images.githubusercontent.com/997106/68708242-eb3b1480-0558-11ea-925a-aeca5ec51182.png)

**Actual behavior:** It does not render the code block correctly, instead rendering inline code:

![Screenshot from 2019-11-12 14-35-26](https://user-images.githubusercontent.com/997106/68708636-b9767d80-0559-11ea-8074-cf58833e5fb7.png)

**Reproduces how often:** I am able to reproduce all of the time. However, if I revert commit https://github.com/frctl/fractal/commit/6b4506a2fb0dad94360e885c0e70ea5bc144fe42 it does not reproduce.

**Reduced test case:** (if relevant) - this might be a link to a gist of your `fractal.js` file, or a git repo for more complex issues

My fractal.js file:

https://gist.github.com/jwir3/c3806e0d7bdcc12f51c54ad1e138b112

### Versions

* What version of Fractal are you running? I have tried with `1.2.0` and `1.2.1.-beta.1`
* What version of Node.js are you running? (run `node -v`) `v8.10.0`

**Comment by jwir3** [comment]
I noticed that I did not seem to have the latest version of `@frctl/mandelbrot` installed, so I added it to my dependencies in `package.json`. I'm not sure if it will get picked up as a transitive dependency within `@frctl/fractal` or not, but I thought it was worth a try. It doesn't seem to affect anything, though.

**Comment by Chapabu** [comment]
Does the issue persist with the latest Mandelbrot? Might just need a bump in the Fractal core package.json :)

**Comment by Chapabu** [comment]
Actually, if you could follow up on #517 that'd be better as they appear to be the same issue!

**Comment by jwir3** [comment]
Hi Matt:

Actually, it does not resolve with the latest mandelbrot. Also, I believe this is a different issue than #517 because that issue apparently is an issue with a third party package, whereas this one is a regression caused by a specific commit where the mandelbrot styles were not updated accordingly.

**Comment by jwir3** [comment]
It appears I don't have permission to reopen this issue. Can you reopen it?

**Comment by jwir3** [comment]
@Chapabu I could revert commit 6b4506 but I'm not sure why that change was made in the first place, so I'm not confident I know of the side effects of doing this.

**Comment by jwir3** [comment]
Ah... actually, [this PR](https://github.com/frctl/mandelbrot/pull/79), which is a side-requirement of #477 was never merged into @frctl/mandelbrot. Let me test, but I suspect that merging that will fix this issue.

**Comment by Chapabu** [comment]
That'd be awesome. If you let me know if it works I'll try and get a Mandlebrot release out over the next week provided everything else works. I struggled to actually get the tooling up and running and haven't had a chance to unpick it yet, so I've been a bit nervous to touch Mandlebrot since becoming a maintainer.

**Comment by jwir3** [comment]
@Chapabu I've confirmed that @frctl/mandelbrot#79 fixes this issue. I've also left a code review for this on the associated PR.

**Comment by LeBenLeBen** [comment]
frctl/mandelbrot#79 has been merged and should be released this week.
