### ISSUE TITLE
Web app devs unable to copy our docs site code and render it, due to Fractal HBS helpers

### ISSUE THREAD

**Issue by jrmcdona** [frctl/fractal#541]
I was not able to join Slack since the link to that has expired.

I am trying to look at the Handlebar helper code, such as the render helper,  can I get a pointer to the helpers that come with Fractal?

We have a fractal's doc site and use the helpers.  I am trying to make it easy for somebody to take our example code from docs site and build their web app.   However, seeing that Fractal is providing additional helpers it is not apples to apples and causing confusion for the web app devs reading our docs and sample code.

If  I could get these helpers, we could provide a JS file that includes them to the devs.

Thanks

**Comment by LeBenLeBen** [comment]
You can find everything about the Handlebars adapter in [its own repository](https://github.com/frctl/handlebars/). The helpers are all located there: https://github.com/frctl/handlebars/tree/develop/src/helpers
