### ISSUE TITLE
Slack channel inactive | Laravel Blade docs/implementation?

### ISSUE THREAD

**Issue by StanBarrows** [frctl/fractal#560]
Hey there, awesome framework!

I just saw that the current Slack Channel Invitation within your **readme.md** file is not longer active. Could you share a new one with me?

![image](https://user-images.githubusercontent.com/10268813/77823112-133aa700-70f9-11ea-90ed-3592cc95c76c.png)

Has there someone experience with using fractal within Laravel Blade and could share some documentations or setup guide?

Cheers
Stan

**Comment by LeBenLeBen** [comment]
Hey, we moved to Discord, you can find the link on the [latest README](https://github.com/frctl/fractal/blob/develop/README.md).

Was the README you found anywhere public and not outdated? I’m wondering if I missed a link when updating them.

**Comment by risker** [comment]
Found a link to Slack at the bottom of our README, fixed that.

Regarding Laravel Blade, I do not know of any implementations of Fractal x Blade. I've recommended in the past switching to Twig - since Laravel can also work with PHP Twig & there's an existing adapter for twig.js for Fractal.
