### ISSUE TITLE
Allow Highlight.js language configuration within fractal config file

### ISSUE THREAD

**Issue by maximedaoust** [frctl/fractal#582]
It would be ideal to be able to install `highlight.js` (via `npm i highlight.js`), define custom language and configuration and then pass that configuration to fractal. At the moment, it doesn't seem to be possible to overwrite fractal highlight configuration and add custom language.

Something like the following would be nice :
```
const hljs = require('highlight.js');
hljs.registerLanguage('vue', () => ({ ... }));
... 
const fractal = module.exports = require('@frctl/fractal').create();
fractal.components.highlight(hljs);
```

**Comment by Chapabu** [comment]
I like this one a lot. Would be especially useful when writing docs that perhaps show other languages (e.g. PHP and Go are ones I've needed before).
