### ISSUE TITLE
Fractal copy error after build

### ISSUE THREAD

**Issue by Wursthandschuh** [frctl/fractal#586]
### Description

I get an error after `fractal build`
Error copying 'path_to_project/fractal' ==> 'path_to_project/fractal/build'

Also inside my build directory is basically a clone of the project. It includes files like package.json, yarn.lock, which I think should not be there. Furthermore inside the build directory is another build and in that another build and so on ...
![image](https://user-images.githubusercontent.com/32794633/81174945-008e7a00-8fa3-11ea-8edd-2e65f25c0cbb.png)

This is my fractal.js:

```js
'use strict';
const path = require('path');

/* Create a new Fractal instance and export it for use elsewhere if required */
const fractal = module.exports = require('@frctl/fractal').create();

/* Tell Fractal where the components will live */
fractal.components.set('path', __dirname + '/src/components');

/* Tell Fractal where the documentation pages will live */
fractal.docs.set('path', __dirname + '/src/docs');

fractal.web.set('static.path', __dirname, '/dist');

/*
 * Require the Twig adapter
 */
const twigAdapter = require('@frctl/twig')();
fractal.components.engine(twigAdapter);
fractal.components.set('ext', '.twig');

/* theme */
const mandelbrot = require('@frctl/mandelbrot'); // require the Mandelbrot theme module

// create a new instance with custom config options
const myTheme = mandelbrot({
    styles: [
        "default",
        "/dist/css/fractal.css"
    ],
});

fractal.web.theme(myTheme); // tell Fractal to use the configured theme by default
fractal.web.set('builder.dest', __dirname + '/build');
```

### Steps to Reproduce

1. fractal build

**Expected behavior:** no error and only the static files are copied

**Actual behavior:** everything is copied and infinite build inside build

### Versions

* What version of Fractal are you running? @frctl/fractal@1.2.1
* What version of Node.js are you running? v12.13.1

**Comment by LeBenLeBen** [comment]
The problem most probably comes from this line:

```js
fractal.web.set('static.path', __dirname, '/dist');
```

Here you're making the current directory the static path. The static path folder is copied to the build, resulting in this infinite nested folders.

You should fix the setting with something like:

```js
fractal.web.set('static.path', path.resolve(__dirname, '/dist'));
```

Let me know if you're still encountering problems after that change.

**Comment by Wursthandschuh** [comment]
That fixed it. thx!
I only have the html files in the build directory now.
My dist folder which contains css/js is not copied though.
I could easily solve this with webpack or a cp command. 

Is it intended that fractal doesn't copy static.path?

**Comment by LeBenLeBen** [comment]
Fractal does copy `static.path` to the destination. Are you sure your assets exists in the folder *before* building Fractal? See https://fractal.build/guide/web/#static-assets

**Comment by Wursthandschuh** [comment]
actually I had a typo. Assets from dist/ get copied to build/ now. 
I would like to have them in build/dist though. I might have missunderstood some config Settings. 
I'll dig deeper into the docs.

**Comment by LeBenLeBen** [comment]
Sure, and please come to our [Discord server](https://discord.gg/vuRz4Yx) if you need any more help.
