### ISSUE TITLE
Prettier config doesn’t match most of the repository existing style

### ISSUE THREAD

**Issue by LeBenLeBen** [frctl/fractal#590]
There’s a `.prettierrc` file in the repository, which enables my editor auto-formatting on save. The problem is, the current style doesn't match Prettier rules; especially for quotes, Prettier wants doubles but the current code base use mostly singles.

This is an issue because when submitting PRs, a lot of changes happen that are unrelated to the fixes/feature proposed. I can live with "Save without formatting" for a while but that's neither convenient nor good for new contributors.

I think we should update the config to be as close as the existing code base style and then format all the files in a single commit. It should be done when there's almost no PRs open to avoid as many conflicts as possible.

**Comment by risker** [comment]
This also needs a test-level integration to ensure new contributions match the style, something along the lines we have for mandelbrot now. Not everybody has their editors configured to use prettier.
