### ISSUE TITLE
Typescript for the Master Branch

### ISSUE THREAD

**Issue by paull39** [frctl/fractal#591]
Hi all!
Thanks for your great work.
I am getting my Hands on this Project and found your request about increasing test coverage!

While getting deeper in the Source Code i found Troubles of getting Hands on the Context
of most Functions.

I would like to request the Feature of converting Javascript to Typescript of the current Master

### What problem would this feature solve?

Increasing Developer Experience.

The used Data Structure and function Parameters are nice abstracted, but less documented.

To get Hands on the Codebase means for this Project to identify what Data is meant in the Context.

Typing this behaviour is only a little bit more of work in this endeavour.

### What the feature should look like?

* Converting the Codebase to valid Typescript
* TODOs of not described ("any") data Structures

So far im doing the Basic Janitor work.
Getting @types Packages in, and typing Package e.g. @allmarkedup/fang
I would like to use import instead of require.

Do you think, that this is a nice improvement for this Project?

**Comment by risker** [comment]
While I appreciate the need and all the goodies TypeScript would bring, converting a project this size (and this old) is near impossible without a very large refactor. Additionally, while increasing developer experince for some, TypeScript will be a barrier of entry for others. We are not convinced that the benefits outweigh the overhead. 

Our current goals are maintenance of existing features and moving away from some legacy code that is not necessary anymore. A part of this is the need to write tests. Native TypeScript support may still happen in the future - but if, then it will come together with a bigger refactor. For that refactor, we would need tests - so we could move logic around with confidence that we won't break features.

Closing this as I do not see this as actionable in the near future. We can re-open or re-file if circumstances change.

P.S. There are types available for Fractal: https://www.npmjs.com/package/@types/frctl__fractal. I believe currently contributing to make those types better in the DefinitelyTyped repository would be best.
