### ISSUE TITLE
Render collator markup with engine

### ISSUE THREAD

**Issue by AndrewLeedham** [frctl/fractal#593]
### What problem would this feature solve?

When defining a default collator it can only render static markup.

A use-case we have run into is providing a link to the preview route for each of the variants in a collated view. There does not seem to be an easy way of doing this without accessing "private" variables (e.g. those starting with `_`) or hacking together some runtime JavaScript.

Therefore it would seem logically to me to run the collator through the current rendering engine so it can use helpers like `path` to construct said URL.

### What the feature should look like?

This seems to be where the markup is passed to the collator, so perhaps: https://github.com/frctl/fractal/blob/b7c29acaf416b6328fa7dd21b167129a78b921e4/src/api/components/source.js#L229

could just be changed to:

```javascript
return Promise.all(items.map(i => this.engine.renderString(component.collator(i.markup, i.item))).join('\n'));
```

**Comment by mihkeleidast** [comment]
It is possible to specify a component as collator, which should do what you need.

For example, in your config:
```js
module.exports = {
    collated: true,
    collator: '@my-collator',
    variants: [...]
};
```
And `my-collator.hbs`:
```
{{#each _variants}}
    {{{ this.markup }}}
    {{ this.item }}
{{/each}}
```

This should allow full customization of the collator, including using the path helper.

I'll file a docs issue since this functionality seems to be undocumented.
