### ISSUE TITLE
Feature request: Ability to hide component variants

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/fractal#6]
It seems `isHidden` is only available at the root level of a component, yet I have a case where I wish to hide a particular variant (as it goes, the default). Is this possible?

**Comment by allmarkedup** [comment]
No, it's not possible at the moment, but should be pretty straightforward to add. Makes sense to add this at the variant as well as component level too.

**Comment by allmarkedup** [comment]
This has now been added and released in v0.9.8
