### ISSUE TITLE
Allow custom information properties

### ISSUE THREAD

**Issue by julmot** [frctl/fractal#624]
### What problem would this feature solve?

Showing the semantic version out of package.json beside of the information when it was last built.

### What the feature should look like?

Allow passing an object with freely defined key value pairs that will be shown together with `builtOn`. I would also think of replacing this with `builtOn` entirely (or only show it when the custom option is empty) since this would allow passing a custom `builtOn` with custom date formatter, e.g. "01.01.2020" instead of "01/01/2020".

Example:

```js
fractal.web.theme(mandelbrot({
  skin: 'navy',
  panels: ['html', 'view', 'context', 'resources', 'notes'],
  favicon: '/images/common/favicon.ico',
  information: {
    'Version': pkg.version
  }
}));
```

For now I'm going to show the version in the project title:

```js
fractal.set('project.title', `${pkg.description} <b><i style="color:#80a753">v${pkg.version}</i></b>`);
```

**Comment by mihkeleidast** [comment]
This would be nice and useful! Do you think we should only allow string information? The current `builtOn` renders a `<time>` element which should be better semantically. If we allowed strings, I could see feature requests to allow links etc too.

**Comment by julmot** [comment]
Of course numbers could be valid to, even dates when displayed using `toLocaleDateString`. But in the end, everything has to be converted to a string anyway, so I don't think it's a problem to expect a string.
