### ISSUE TITLE
Feature Request: Implement keywords option

### ISSUE THREAD

**Issue by julmot** [frctl/fractal#637]
Use case: A component "product stock" should not only be found when entering "product" or "stock" but also "availability", "ERP" etc.

### What problem would this feature solve?

Let component authors specify a list of keywords like for an npm package that make a component findable under these terms.

### What the feature should look like?

For example allow specifying the following in the components config:

```yml
status: "ready"
label: "..."
keywords:
  - "stock"
  - "ERP"
  - "availability"
default: "..."
variants:
  // ...

**Comment by LeBenLeBen** [comment]
Components already have the concept of [tags](https://fractal.build/guide/components/configuration-reference.html#component-properties), I guess it would be fair to reuse them for that purpose. WDYT?

**Comment by mihkeleidast** [comment]
AFAIK tags are already taken into account when searching, see:
- https://github.com/frctl/fractal/blob/master/packages/mandelbrot/views/macros/navigation.nunj#L37
- https://github.com/frctl/fractal/blob/master/packages/mandelbrot/assets/js/components/search.js#L63 etc

**Comment by julmot** [comment]
Hey guys,
Thanks for the information.
Totally my bad, wasn't aware of `tags`. Just tried it out and it works as expected 🍾
