### ISSUE TITLE
Fractal commands are not working

### ISSUE THREAD

**Issue by shadeed** [frctl/fractal#64]
Hello there,

Thanks for this awesome tool, I'm really excited to explore it. While I'm trying to install it there is an error appear each time I try to run a fractal command.

for example ```fractal start``` will output the following in the terminal:

```
/usr/local/lib/node_modules/@frctl/fractal/bin/fractal:5
const semver         = require('semver');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

This is on the project root and fractal.js file is available. Also, I got the same error when trying to install a project somewhere using ```fractal new my-project```.

Thanks,

**Comment by allmarkedup** [comment]
Hi @shadeed - can you check what version of Node you are using? It sounds like you are using  and older version, Fractal requires v4.0+ to run.

If that is not the case then let me know and I'll look into it further!

**Comment by shadeed** [comment]
My bad! yes it works now after updating Node. Thanks a lot!

**Comment by allmarkedup** [comment]
No worries! Glad it's working for you now :-)
