### ISSUE TITLE
Relative path links from notes accessible both from local server as deployed server.

### ISSUE THREAD

**Issue by ccGabbles** [frctl/fractal#658]
### What problem would this feature solve?

Possibility to access components via the same relative path (with extension) between the local development server and the build variant being hosted elsewhere.

Right now, if you put a relative URL in the notes pointing to another component, for instance: `./component-name`, it will work fine on the local development server. The default settings on the builder make it work so it contains the extension (.html). Therefore when you host the build variant elsewhere, your notes with the `./component-name` the link will result in a 404.

Vice versa this has the same effect, so if we would construct the link to contain the extension, as such: `./component-name.html`, this will work fine in the build variant. But this won't work in the local development server as it will try and match the handle including the extension (stating: Not found - Component 'component-name.html') not found.

It would be a bit more decent, functionality-wise, if these inner links don't break depending on the environment its on.

### What the feature should look like?

A possible solution is to overwrite the default extension the builder script receives from the config, and change the htaccess file to point towards the extension-less build files, this is already implemented. But, as is the case in my current environment, I don't have the opportunity to go and modify that. Therefore, why not have the possibility to inverse this mechanism from the local environment as well?

From the config, it could supply an extension (by default '.html') which then gets retrieved in the local server and somehow knows how to match the appropriate component. That way he will strip off the extension and can match the handle accordingly.

**Proposed solution (direction)**: #659 - see discussion below on cleanliness

**Comment by mihkeleidast** [comment]
What Fractal version are you using? I believe this was fixed some time ago in #575, but if it's still broken, please add a repro.

**Comment by ccGabbles** [comment]
@mihkeleidast - Thank you for the quick response, I'm using the latest version v1.3.0 and still seems to happen!

Did find the place where it occurs though and created a pull request for it: https://github.com/frctl/fractal/pull/659
But I don't know if this is the neatest way to fix this, as the templates itself still generate URLs without extension.

Don't have the time to create a minimal repro now, but will put some effort in this in the upcoming days.

**Comment by mihkeleidast** [comment]
Yeah I'd like to understand the issue better so I could maybe suggest a better fix. I can wait for the repro for a bit :)

**Comment by ccGabbles** [comment]
I did find some time to create a repro! - https://github.com/ccGabbles/fractal-issue-658-reproduction
Contains one self-linking component from the notes which demonstrate the issue.
Basically check those when build and when served locally - readme says it all.

Hit me up if anything is unclear! :)

**Comment by mihkeleidast** [comment]
Aha, I think I figured it out. The automatic rewrite thingy I fixed in #575 works when using the path filter - so using it like `[link name]({{path './component' }})` should give the correct path for both server and builder.

**Comment by ccGabbles** [comment]
I see it does do something, but basically it changes the URL to incorporate the .html extension on both the server as on the builder. So therefore locally it still results in the same problem. After testing a couple of times, I do think it seems to work, as it reloads and I see the correct page, but then it immediately triggers another reload which results in 'Component 'component.html' not found'.

Should the path be set somewhere as a config before this works or maybe it did break over time? if you want me to commit it like such, let me know!

**Comment by mihkeleidast** [comment]
That should be a bug in the path helper in the handlebars adapter, since it should do an early return for server - [see here](https://github.com/frctl/fractal/blob/main/packages/handlebars/src/helpers/path.js#L24). I'm pretty sure this worked when I fixed the related bug though, not sure what has changed since then.

Either way, using the path helper should be the correct way, and this bug in the path helper should rather be fixed than worked around via a new option.

**Comment by ccGabbles** [comment]
I Agree, seems like that would be the appropriate place indeed.
I'll have a look around and see if I can fix it like such in my fork.

Thank you for thinking with me here!

**Comment by ccGabbles** [comment]
Okay after some reverse engineering I noticed that `root._env` object in the conditional is not set for the readme.md files (the notes) is empty. The parent itself though does have a `root.server` located showing the exact same thing. Thus, the updated fix in pull request #659 is to let the if statement look at either one of these two values. 

Basically, It works, but seems not the cleanest way to do so. I feel like the environment should still be set accordingly so it comes from the same location. Any idea where that is being set or if this is sufficient? couldn't track that down easily.
