### ISSUE TITLE
Is it possible to get fractal working with full URLs to component pages?

### ISSUE THREAD

**Issue by matt-bailey** [frctl/fractal#68]
I'm integrating fractal into our frontend design/dev theming workflow to use as a component library generator for our projects. The particular framework/cms we're working in (Magento 2) doesn't like the friendly URLs output by Fractal, it tries to rewrite them. However, it does work if you reference the full URL to the component page.

So this doesn't work: `my-site.dev/pub/static/fractal/components/detail/example`
But this does work: `my-site.dev/pub/static/fractal/components/detail/example/index.html`

The problem is that all the links in the generated Fractal html files are hard-coded without `index.html` on the end, so you can manually visit pages by typing index.html into the address bar, but you can't use the tree menu, which contains links like this:

```
<a class="Tree-entityLink" href="/components/detail/example" data-pjax=""></a>
```

Is there an easy way to solve this?

An option in `fractal.js` where you can set to output friendly/unfriendly URLs might make sense?

**Comment by allmarkedup** [comment]
@matt-bailey there is no way to change that at the moment I'm afraid. But I'll soon be looking at some improvements to the whole build process as there are a few other URL-related issues that people are coming up against, so I'll definitely add this in.

Can you use a folder-specific .htaccess file (or equivalent for whatever server you are using) to work around this in the meantime?
