### ISSUE TITLE
After upgrading from 1.2.0 to 1.5.0 pages and components act strange.

### ISSUE THREAD

**Issue by ruurdv** [frctl/fractal#687]
After a `npm update` (it upgraded the fractal version from 1.2.0 to 1.5.0) we have encountered concerning issues on our side:

Running on localhost (fractal.web.server):
- It sometimes need three refreshes for the template to actually render as it should. For example: first reload would only show half the page, second reload the entire page but one component in it's default stage, third reload is a good render where the page renders fully and the components accordingly (including the correct context)

Browsing the builded files (fractal.web.builder):
Most pages and component work correct, apart from a few. They seem to have no connection and it's strange behaviour.
- Only in two components the merge=true parameter doesn't work accordingly.
- Two components do not get rendered at all.
- One component renders without context.
- One component get rendered odd; does not handle it's IF-statements correctly and also has trouble with it's context.
All these situations do not occur in the development-mode (fractal.web.server). Same components, same config.

We have about 150 components and say another full page 75 templates.

### Steps to reproduce the issue

We are using handlebars as template engine.

We use this package.json:

`
"dependencies": {
    "chromedriver": "^77.0.0",
    "dot-prop": "^5.1.1",
    "gulp-minifier": "^3.5.0",
    "is-obj": "^2.0.0",
    "jimp": "^0.16.0",
    "jpeg-js": "^0.4.0",
    "jquery": "^3.5.1",
    "js-yaml": "^3.13.1",
    "kind-of": "^6.0.3",
    "lodash": "^4.17.19",
    "minimist": "^0.2.1",
    "node-sass": "^4.14.1",
    "set-value": "^2.0.1",
    "webdriver-manager": "^12.1.7"
  },
  "devDependencies": {
    "@frctl/fractal": "^1.2.0",
    "@frctl/mandelbrot": "^1.2.1",
    "@frctl/twig": "^1.0.0-beta.5",
    "autoprefixer": "^9.6.1",
    "backstopjs": "^5.0.1",
    "combobo": "2.0.1",
    "del": "^5.1.0",
    "eslint": "^6.3.0",
    "fastsearch": "^1.11.1",
    "fastselect": "^0.7.3",
    "glob-all": "^3.1.0",
    "gulp": "^4.0.2",
    "gulp-change": "^1.0.2",
    "gulp-changed": "^4.0.1",
    "gulp-clean-css": "^4.2.0",
    "gulp-concat": "^2.6.1",
    "gulp-eslint": "^6.0.0",
    "gulp-header": "^2.0.9",
    "gulp-imagemin": "^6.1.0",
    "gulp-postcss": "^8.0.0",
    "gulp-rename": "^2.0.0",
    "gulp-replace": "^1.0.0",
    "gulp-sass": "^4.0.2",
    "gulp-uglify": "^3.0.2",
    "jasmine-spec-reporter": "^4.2.1",
    "muban-convert-hbs": "^1.1.1",
    "protractor": "^5.4.2",
    "selenium-standalone-jar": "^3.141.59",
    "svgo": "1.3.0"
  }
`

**Reproduces how often:**

Localhost: 20%.
Builded files: 100%

### Context

-   Fractal version: @frctl/fractal@1.5.0, @frctl/mandelbrot@1.6.0
-   Node version: v12.19.0
-   OS: MacOS 10.15.6

I really hope someone knows how to get our environment stable again. Any help is very much appreciated. In need of more documentation or code, please let me know and I'll be more than happy to provide it.

**Comment by mihkeleidast** [comment]
Please create a minimal repo where these issues can be reproduced - it'll help a lot to have specific component/usage examples we can test against.

**Comment by mihkeleidast** [comment]
I do notice that in your deps `@frctl/twig` package is very old. If you're using twig (note that you did not mention what templating engine you're using), update that too for the reproduction repo.

**Comment by ruurdv** [comment]
Thank you for your swift reply.

(We are using handlebars as template engine.)

I'll get back to your first question shorty.

**Comment by mihkeleidast** [comment]
Please still create a minimal repo with clear reproduction steps for these issues - we won't start searching for problems in your repo with hundreds of components.

**Comment by ruurdv** [comment]
Understood. I'll create one.

**Comment by ruurdv** [comment]
Here is a sample repo:
https://github.com/ruurdv/koop-lib-experiment

When you open the template 'oeb-zoek-bekendmakingen' on your localhost (gulp dev), you'll notice it takes three refreshes to show it's full (correct) state.
When you open the template 'oeb-zoek-bekendmakingen.html' as builded package on your machine (gulp fractal-build), you'll notice it doesn't render the element at all. 

Does this repo work for you?

**Comment by mihkeleidast** [comment]
@ruurdv can you try the fix in #688 and see if that resolves all issues?

**Comment by ruurdv** [comment]
On first sight, this fix seems to do the trick! Amazing. I will do some further testing.

I've now manually changed the two lines in the handlebars adapter.js. Is this fix going to be part of some sort of a release? 

How do you suggest we deal with this fix, regarding future updates we would like to run? Do we need to manually edit the two lines, after updating our packages?

**Comment by mihkeleidast** [comment]
We'll release it ASAP once it gets merged.

**Comment by ruurdv** [comment]
Do you have rough estimate how this will take / usually takes? A week? Two? One month?

Thank you so much for your help; quick and helpful responses. Very much appreciated.

**Comment by mihkeleidast** [comment]
I hope not long. Can't make any promises though. I'd say it's a small fix so it'll get released at least next week.

You should be able to pin @frctl/handlebars package to an older version in the meantime - the bug was introduced in v1.2.3

**Comment by mihkeleidast** [comment]
Fixed in `@frctl/handlebars@1.2.4` / `@frctl/fractal@1.5.1`.
