### ISSUE TITLE
Update highlight.js

### ISSUE THREAD

**Issue by mihkeleidast** [frctl/fractal#689]
### What problem would this feature solve?

[Highlight.js v9 has been marked EOL](https://github.com/highlightjs/highlight.js/commit/f54e96c24325f077a027bb950dcd9f8f3ef48b16) and users currently get a warning when installing Fractal. Updating the dependency would clean up the warning and remove our dependency on a legacy version.

### What the feature should look like?

Highlight.js is updated to v10+.

**Comment by portfolioris** [comment]
See https://github.com/frctl/fractal/pull/690

**Comment by mihkeleidast** [comment]
Resolved in #690.
