### ISSUE TITLE
Fatal error while building project

### ISSUE THREAD

**Issue by supermueller** [frctl/fractal#694]
### Steps to reproduce the issue

1. Clone repository [supermueller/fractal-build-error](https://github.com/supermueller/fractal-build-error)
1. Run `npm intall` to install Fractal
1. Run `fractal build`

The build process should then fail with a fatal error (`Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`).

If you remove one item from the context of component "ul", the build process will finish without errors.

**Reproduces how often:**

Every time

### Reduced test case

See [supermueller/fractal-build-error](https://github.com/supermueller/fractal-build-error)

### Context

-   Fractal version: 1.5.1
-   Node version: v12.19.0
-   OS: MacOS 10.14.6

**Comment by mihkeleidast** [comment]
@supermueller can you check if the fix in #695 fixes your issue without any side effects?

**Comment by supermueller** [comment]
@mihkeleidast #695 fixes my problem and it seems that it have no side effects in my project. Thanks a lot for your help.
