### ISSUE TITLE
Missing documentation: components.title and docs.title can be configured

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/fractal#7]
I wanted to rename components in the UI, but saw nothing in the documentation. Looked at the theme, and lo-and-behold, there were references to `components.title` and `docs.title`; these should be documented.

**Comment by allmarkedup** [comment]
Actually it is documented.... but clearly not easy enough to find :-)

It's in the component configuration reference: https://github.com/frctl/fractal/blob/master/docs/components/configuration.md

You can also set a 'label' property that changes what shows up in any navigation, if you want that to be shorter/different.

**Comment by paulrobertlloyd** [comment]
No, no, I’m talking about the main Fractal configuration which allows you to do this:

<img width="250" alt="screen shot 2016-02-23 at 21 04 05" src="https://cloud.githubusercontent.com/assets/813383/13266674/17a78b28-da71-11e5-9aa9-21eba46b6832.png">

```js
fractal.set('components.title', 'Foo');
fractal.set('docs.title', 'Bar');
```

**Comment by allmarkedup** [comment]
Ahhh gotcha. I'd completely forgotten about that to be honest! Handy :-)

(And you are right, in need of documentation... even if it's just so I don't forget about it again...)
