### ISSUE TITLE
A way to dynamically set a starting width of the resizable Preview-wrapper?

### ISSUE THREAD

**Issue by matt-tyas** [frctl/fractal#71]
So small components are near their natural size on load. I could include a grid in the .hbs file, but I am using the partials to build example templates so this is not an option. Is this possible to do something similar to the issue title instead?

**Comment by allmarkedup** [comment]
@matt-tyas Sorry for the slow reply mate... I'm not 100% clear on what you need exactly but you can use the `display` property in a component's configuration to set CSS properties (like min/max width) on the preview 'window': https://github.com/frctl/fractal/blob/master/docs/components/configuration.md#display

Does that help with your issue in any way?

**Comment by anderskleve** [comment]
I would too love to have this feature, as (in our case) a means of enforcing a mobile first workflow by setting the default preview area to be narrow.
