### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by gunzip** [frctl/fractal#72]
It looks like like IE 9 / 8 are not supported because of some es6 features. It's a pity as, one of the main pourposes of a pattern lab, is testing components in older browsers as well. Maybe some es6 polyfill can help ? (ie. runtime babel)

**Comment by allmarkedup** [comment]
Hey @gunzip - you are correct, the default theme currently doesn't support those browsers. Better browser support is definitely high up on my list of todos for post-1.0 release.

All component's do have a full-page preview URL (i.e. with not fractal UI around them) so you can still test components by inputting that URL directly into any unsupported browser. Not a perfect solution by any means but you can definitely still test like this (I do!) :-)

**Comment by gunzip** [comment]
glad to see there's some progress here. i think that frctl is by far the best pattern lab tool available. 
maybe you could point out some issues so contributors can help.

**Comment by allmarkedup** [comment]
@gunzip Thanks! Means a lot to hear people say that :-) I'm current working on getting a 1.0 beta out the door (which will have some breaking changes) and once that is done I'll definitely be working on making it easier for others to contribute.

**Comment by allmarkedup** [comment]
Moved this issue to the Mandelbrot repo: https://github.com/frctl/mandelbrot/issues/29

**Comment by tlenex** [comment]
[IE9+ support PR](https://github.com/frctl/mandelbrot/pull/46) 
IE8 is hell with CSS 😞
