### ISSUE TITLE
Multiple component folders

### ISSUE THREAD

**Issue by kimblim** [frctl/fractal#74]
Feature request:

It would be very nice to have the option to set multiple component folders, ie.:

```
├── components-a
│   └── blockquote
│       └── blockquote.hbs
├── components-b
│   └── blockquote
│       └── blockquote.hbs
```

That way you could have seperate preview-templates for stuff like theming, different brands etc.

**Comment by allmarkedup** [comment]
Hi @kimblim - if I've understood your needs correctly something like this is actually already possible using collections and collection configuration files - have a look at https://github.com/frctl/fractal/blob/master/docs/collections.md for more info. Would that solve your issue?

**Comment by kimblim** [comment]
Hi @allmarkedup,

I tried that at first, but it doesn't work if the components have the same name (in my folder/file structure example above, they are both called blockquote) — this makes components-b/blockquote render with the settings from components-a/blockquote.

I don't know if this a very specific need, but right now I need to build a styleguide for multiple brands that share components, so it would be very handy.

**Comment by allmarkedup** [comment]
@kimblim - sure, I can see how that would be useful!

if you add a configuration file for each of the collections, you can actually then specify a `prefix` within it that will be applied to the handles of all components in that folder.

So if you had `components-b.config.json` within the `components-b` folder, and set a property `"prefix": "compb"` in there, then the handle for the blockquote component would be `@compb-blockquote` and it wouldn't clash with the other blockquote component as they would now have different handles. And all other components in that folder would also have that prefix applied to their handles, making them unique to that folder. The same would apply to any components within that folder used as preview layouts.

Would that help in anyway?

**Comment by kimblim** [comment]
@allmarkedup 

Thanx for your patience :)

I'm not sure I'm doing this right, because I simply can't get it to work.. Right now my folder/file structure looks like this:
```
├── components-a
│   └── _preview.hbs
│   └── components-a.config.yml
│   └── blockquote
│       └── blockquote.hbs
├── components-b
│   └── _preview.hbs
│   └── components-b.config.yml
│   └── blockquote
│       └── blockquote.hbs
```

And the content of the compenents-a.config.yml file looks like this:
```
prefix: "components-a"
preview: "preview.hbs"
```

What am I doing wrong?

**Comment by kimblim** [comment]
@allmarkedup 
I found the problem, so don't worry about it anymore.

For anyone interested, I might as well document it here - changed filestructure from the above to this:
```
components
├── components-a
│   └── components-a.config.yml
│   └── blockquote
│       └── blockquote.hbs
├── components-b
│   └── components-b.config.yml
│   └── blockquote
│       └── blockquote.hbs
├─_preview-components-a.hbs
└─_preview-components-b.hbs
```
and the yml-files look like this now:
```
prefix: "components-a"
preview: "@preview-comp-a"
```
