### ISSUE TITLE
escape partials in documentation-files

### ISSUE THREAD

**Issue by theressophie** [frctl/fractal#75]
If I use partials in a configuration file, he wants to parse them and throws the error:
Error: The partial @headline could not be found

I do not want that the partials are parsed if I use them in a code-section to document something. I just want to use it as a string. How can I escape them?

Examples from my doc-files:
```
context: {
    buttonText: @button.buttonText,
    headlineText: @headline.headlineText,
},
```
or
```
<nav class="c-menu c-menu--button c-menu--{{modifier}}">
    <ul class="o-list-bare c-menu__list">
        <li class="c-menu__headline">
            {{> @headline type="h5"}}
        </li>
        {{#each items}}
            <li class="c-menu__item {{#unless @index}}is-active{{/unless}}">
                {{> @button text=this.key modifier="small"}}
            </li>
        {{/each}}
    </ul>
</nav>
```

Thank you.

**Comment by allmarkedup** [comment]
Hi @theressophie - You should be able to escape handlebars partials by including a backslash (\) before the partial code - for example `\{{> @headline type="h5"}}`. Can you try that and see if it helps?

**Comment by theressophie** [comment]
Yes, it works fine. Thank you for your quick response.
