### ISSUE TITLE
Underscores in the file path cause web UI to fail to load components

### ISSUE THREAD

**Issue by jpolete** [frctl/fractal#76]
On Mac OS X El Capitan 10.11.5, if the path to the location of the fractal project contains an underscore, the web UI appears to start correctly, but none of the components load.

This works fine:
`/Users/username/projects/my-project`

This fails to load any components
`/Users/username/_projects/my-project`

Running Fractal 0.11.4

**Comment by allmarkedup** [comment]
Thanks @jpolete - I think I know why that might be so I'll look into it as soon as I can!

**Comment by jpolete** [comment]
Awesome. Thank you. Fractal has really helped me get on board building component systems.

**Comment by johannestroeger** [comment]
@jpolete could you try to open your components via preview url. e.g. `http://localhost:4001/components/preview/button`

**Comment by jpolete** [comment]
@johannestroeger No. "Error not found" error when I try to open the preview directly.

**Comment by johannestroeger** [comment]
@jpolete just ask because i have the same folder structure and preview URLs work for me.

**Comment by allmarkedup** [comment]
This should be fixed in the new 1.0 version. Docs and upgrade info is now here: http://fractal.build/guide

**Comment by jpolete** [comment]
Awesome. Docs look great.
