### ISSUE TITLE
Additional CLI tool tasks

### ISSUE THREAD

**Issue by allmarkedup** [frctl/fractal#84]
A big part of the next release will be around expanding the functionality of the CLI tool. Some additional task ideas:

- [ ] List components
- [ ] Create new component
- [ ] Rename/move component
- [ ] 'Doctor' - task to help debug issues (like duplicate handles) and help resolve them

... any more?

**Comment by 7iomka** [comment]
Hi!
Do you already have a draft or test versions of these commands?

**Comment by nqthqn** [comment]
@7iomka @allmarkedup I made a tool for some of this called [Sancho](https://www.npmjs.com/package/@nqthqn/sancho). Any thoughts?

**Examples**

| Command                    | Purpose                   |
|----------------------------|---------------------------|
| `sancho -r name1 name2`    | Deeply rename a module    |
| `sancho -d name1 name2`    | Duplicate a module        |
| `sancho -sd name`          | Scaffold a dom module     |
| `sancho -sc name`          | Scaffold a class module   |
| `sancho -sm name`          | Scaffold a mixable module |
| `sancho -st name`          | Scaffold a tabular module |
| `sancho -n name`           | List synonyms             |
| `sancho -scl name "Label"` | Name and label a module   |
| `sancho -sdl "Nice Label"` | Infer name from label     |
