### ISSUE TITLE
deprecated minimatch@2.0.10

### ISSUE THREAD

**Issue by StephenMeehan2016** [frctl/fractal#85]
Hi, 

After a bit of head scratching I've installed Fractal. 

I had to update Node (v4.4.7) and NPM (v3.10.5). I noticed this message in the Terminal:

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/fractal -> /usr/local/lib/node_modules/@frctl/fractal/bin/fractal
```

When I run `minimatch -v`in the Terminal, it shows this:

```
-bash: minimatch: command not found
```

But, when I run `npm list' the latest version of minimatch is shown?

```
/Users/screencasts
└─┬ minimatch@3.0.2
  └─┬ brace-expansion@1.1.6
    ├── balanced-match@0.4.2
    └── concat-map@0.0.1

```

**How do I update minimatch?**

**Comment by allmarkedup** [comment]
Hi @StephenMeehan2016 - out of interest what was causing the initial head scratching? Is there something that could have been made clearer in the docs?

Regarding the minimatch warning - unless you are running the Fractal dev server from a publicly accessible URL I don't think that you need to worry too much. Fractal does not itself use minimatch as a (direct) dependency but one of the libraries it does use must have it as a dependency somewhere... so that library will need to be updated to use the new minimatch version. I'll try and track down which one and open a pull request with them.

**Comment by StephenMeehan2016** [comment]
Hi, thanks for replying.

Not a big deal, but the first instruction assumes familiarity with Terminal

"If you have not already created a folder for your project, do so now and then run npm init from within the folder to initialise your project directory."

I first thought - how?

I created my folder, then remembered I can highlight the folder name copy it. Back in Terminal typed/pasted `cd /path/to/new/folder`

It'd would be useful to add something like that to the docs.

Once I was in the correct folder I ran `npm install --save @frctl/fractal` and was hit with a wall of errors *Scratches head*. 

I thought it may have something to do with the versions of Node and NPM I was running.

It would also be good to drop this into the docs too. 

Once I updated Node and NPM I could install Fractal, this worked but I also wanted to install the Fractal CLI tool - more head scratching :)

When I ran `npm i -g @frctl/fractal` I received an error

```
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
```

I searched Google for this 'EACCES: permission denied' and found [this article](https://ar.al/scribbles/npm-install-g-please-try-running-this-command-again-as-root-administrator/)

Then I hit the minimatch update issue. 

Nothing major, but none of these 'gotchas' are mentioned in the docs.

Hope this helps :)

**Comment by allmarkedup** [comment]
Ok thanks @StephenMeehan2016 all good feedback. It's always a hard balance to strike in the docs about how much prior knowledge about things like Node/NPM to assume. And there seem to be a million ways that NPM can fail :-)

But I think that it will definitely be worth creating a 'troubleshooting' (or maybe 'tips and tricks') section in the docs for issues like these (and their solutions) that I can just add to over time.

Many thanks for taking the time to respond in detail.
