### ISSUE TITLE
Serious performance issues

### ISSUE THREAD

**Issue by julmot** [frctl/fractal#862]
After upgrading to the most recent Fractal and Mendelbrot versions, I noticed a significant performance impact. Component pages, with many sub components, are effectively rendering for several minutes in my app! If there's anything else I can help to enclose the issue, please let me know. For now, I just attach this considerable chart:

![Screenshot 2021-02-07 230539](https://user-images.githubusercontent.com/8310677/107160925-83f95380-6999-11eb-97e7-f0cfd168711e.png)

### Context
-   Fractal: v1.5.3
-   Node version: v12.16.3
-   OS: Windows 10

**Comment by julmot** [comment]
Closing for now. I'm not 100% sure it's caused by the update, I'll try to debug this issue tomorrow and hope to have certainty then.

**Comment by mihkeleidast** [comment]
Hmm this does not look good... we did manage to update pretty much all dependencies in the last release. If you get a chance to debug this and determine which exact commit caused this, it would be great.
