### ISSUE TITLE
Nested render helpers inside partial-block

### ISSUE THREAD

**Issue by ccardinaux** [frctl/fractal#879]
I have a Fractal instance that uses nested `render` helpers inside a `@partial-block`. This method worked in `@frctl/handlebars` version 1.1.5 but fails when I upgrade that package.

### Steps to reproduce the issue

1. Clone the reduced test case repo below, run `npm install`, then `npm start`
2. Visit http://localhost:3000/components/detail/carousel-card-grid and observe that the Card Grid Carousel loads as expected (carousel has 2 slides of 2 cards each)
3. Stop the dev server and update the `@frctl/handlebars` version in `package.json` to the latest (currently 1.2.6)
4. Run `npm install` again then `npm start`
5. Visit http://localhost:3000/components/detail/carousel-card-grid again and observe that the cards do not load in the carousel

**Reproduces how often:**

100%

### Reduced test case

https://github.com/ccardinaux/fractal-dev-sandbox

### Context

-   Fractal version: 1.5.3
-   `@frctl/handlebars` version: 1.2.6
-   Node version: 12.16.2
-   OS: MacOS 10.15.7

**Comment by mihkeleidast** [comment]
@ccardinaux if you have a change to test out the fix in #884 it would be great :)

**Comment by ccardinaux** [comment]
> @ccardinaux if you have a chance to test out the fix in #884 it would be great :)

Looks good, thanks for the quick fix!
