### ISSUE TITLE
missing mandelbrot theme on default install

### ISSUE THREAD

**Issue by airtonix** [frctl/fractal#88]
- windows 10
- nodist
- node 4.4.7
- npm 3.9.2
- powershell (latest?) no idea how to get it to tell me what version i have.

```ps
zenobius@JADAKREN ~\Projects\
$ npm i -g @frctl/fractal
...
zenobius@JADAKREN ~\Projects
$ fractal new fractal-test
...
zenobius@JADAKREN ~\Projects
$ cd fractal-test
...
zenobius@JADAKREN ~\Projects\fractal-test
$ fractal start
┌───────────────────────────────────┐
│ Fractal web UI server is running! │
│───────────────────────────────────│
│ Local URL: http://localhost:3000  │
│───────────────────────────────────│
│ Use ^C to stop the server.        │
└───────────────────────────────────┘
...
# load chrome to localhost:3000
...
‼︎ 404: No matching route found for /_theme/css/default.css
‼︎ 404: No matching route found for /_theme/js/mandelbrot.js
```

see attached
![chrome_2016-07-23_10-21-25](https://cloud.githubusercontent.com/assets/61225/17074793/2e6299fa-50c0-11e6-8072-fbca4c70a586.png)

**Comment by allmarkedup** [comment]
Hi @airtonix - sorry to hear that you are having these issues with getting Fractal up and running. I've got to admit my testing on windows has been pretty limited and I'm guessing this is some sort of paths issue. I'll look into it as soon as I can and let you know if I get it solved (or even reproduced for a start - this is not once I've seen before!).

**Comment by webprofijt** [comment]
I was having the same problem on Windows but on OS X it worked perfectly for me. Submitted a PR. Thanks for this tool @allmarkedup, I think this will be pretty cool to use.

**Comment by allmarkedup** [comment]
Fixed now thanks to @webprofijt's pull request.
