### ISSUE TITLE
Support arbitrary/user-defined data in component configs

### ISSUE THREAD

**Issue by allmarkedup** [frctl/fractal#89]
Currently any properties set in the component configuration that are not used directly by fractal are not accessible in the serialized version of components/doc objects (and hence are not available in templates from the `_target` variable.)

Would be nice to support arbitrary/user-defined data in this way somehow.

**Comment by pyrello** [comment]
Hello. I'm wondering if this is still being considered? We are currently dealing with the issue of how to include the assets of sub-components when they are being rendered as part of the parent component. It seems like this may be the most direct route, being able to statically define the necessary child component assets in the parent to make sure they all get added. Its not as nice as some sort of dynamic system using the component handle or something like that, but it would be better than nothing.

**Comment by mihkeleidast** [comment]
This was released in the 1.1 version way back in 2018, but only recently officially documented: https://fractal.build/guide/components/configuration-reference.html#meta
