### ISSUE TITLE
Setting for build path

### ISSUE THREAD

**Issue by apdrsn** [frctl/fractal#96]
Hi! 
I'm really enjoying Fractal! Thanks a lot!
Just experienced this:
In your new 1.0 documentation at http://fractal.build/guide/web/builder it tells to use this setting to define build path: 
```fractal.web.set('builder.dest', __dirname + '/build'); // this is the correct setting```

However, in your project settings example:
At http://fractal.build/guide/project-settings#example-project-setup-file it looks like this:
```fractal.web.set('build.dest', __dirname + '/build'); // this fails when trying to build```

**Comment by allmarkedup** [comment]
And another good spot... :-) Also should be fixed in the docs now. Many thanks for pointing these issues out!

**Comment by apdrsn** [comment]
@allmarkedup You are very welcome – I'll let you know if I find anything else. Again thanks for making this available for us to use. Great tool! :-)

**Comment by allmarkedup** [comment]
Thanks @apdrsn - appreciate it! And very glad you are finding it useful.
