### ISSUE TITLE
Shadow effect at http://fractal.build/

### ISSUE THREAD

**Issue by apdrsn** [frctl/fractal#97]
A minor issue I've experienced:
![shadow](https://cloud.githubusercontent.com/assets/6361772/17094054/1f48c032-524d-11e6-9b9e-2208f1419bb6.jpg)

You are not able to click links when they are behind the shadow effect in the bottom of the page. Can be resolved by adding pointer-events: none to the :after element..or removing the shadow :)

**Comment by allmarkedup** [comment]
Thanks mate - this should be resolved now. Good spot!
