### ISSUE TITLE
Title attribute on preview link

### ISSUE THREAD

**Issue by apdrsn** [frctl/fractal#98]
The title on the preview link says: Open in new link, but it opens in the same window.

```<a class="Pen-previewLink" href="/components/preview/select" title="Open preview in new window">...</a>```

I assume it should be up to the user if they want a new window?

**Comment by allmarkedup** [comment]
Hi @apdrsn yes it should indeed be up to the user and so yes that text is confusing! I'll amend it, thanks for the heads up :-)

**Comment by allmarkedup** [comment]
Fixed in latest theme release.
